USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_C_LOYALTY;

create or replace TABLE REWARD_TRANSACTION_AUDIT_LOG (
	HOUSEHOLD_ID NUMBER(38,0) NOT NULL COMMENT 'Unique identifier of the Household. The ''aggregateId'' in CHMS service is the HHID unlike the other services where the ''aggegatedid'' we map to the CustomerId',
	TRANSACTION_ID VARCHAR(100) NOT NULL COMMENT 'This contains Transaction Id for the transaction',
	LOYALTY_PROGRAM_CD VARCHAR(300) NOT NULL COMMENT 'This Contains Loyalty Program Code',
	TRANSACTION_TYPE_CD VARCHAR(50) NOT NULL COMMENT 'This contains transaction type code of a transaction',
	UPDATE_TS TIMESTAMP_LTZ(9) NOT NULL COMMENT 'Contains latest updated timestamp for the transaction',
	DW_FIRST_EFFECTIVE_TS TIMESTAMP_LTZ(9) NOT NULL COMMENT 'The timestamp the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_TS TIMESTAMP_LTZ(9) NOT NULL COMMENT 'for the current record this is ''12/31/9999 24.00.00.0000''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 micro second',
	CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'Contains the created timestamp of the transaction',
	BEFORE_SNAPSHOT VARIANT COMMENT 'Snapshot of Reward buckets before the transaction',
	AFTER_SNAPSHOT VARIANT COMMENT 'Snapshot of Reward buckets after the transaction',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d',
	DW_FIRST_EFFECTIVE_DT DATE COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT DATE COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	primary key (HOUSEHOLD_ID, TRANSACTION_ID, LOYALTY_PROGRAM_CD, TRANSACTION_TYPE_CD, UPDATE_TS, DW_FIRST_EFFECTIVE_TS, DW_LAST_EFFECTIVE_TS)
);


create or replace TABLE REWARD_TRANSACTION (
	HOUSEHOLD_ID NUMBER(38,0) NOT NULL COMMENT 'Household_Id',
	TRANSACTION_ID VARCHAR(100) NOT NULL COMMENT 'Transaction_Id',
	LOYALTY_PROGRAM_CD VARCHAR(300) NOT NULL COMMENT 'Loyalty_Program_Cd',
	TRANSACTION_TYPE_CD VARCHAR(300) NOT NULL COMMENT 'Transaction_Type_Cd',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW_First_Effective_Dt',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW_Last_Effective_Dt',
	TRANSACTION_DETAIL_TXT VARCHAR(16777216) COMMENT 'Transaction_Detail_Txt',
	TRANSACTION_TS TIMESTAMP_LTZ(9) COMMENT 'Transaction_Ts',
	REFERENCE_NBR VARCHAR(100) COMMENT 'Reference_Nbr',
	LOYALTY_PROGRAM_DSC VARCHAR(250) COMMENT 'Loyalty_Program_Dsc',
	TRANSACTION_TYPE_DSC VARCHAR(250) COMMENT 'Transaction_Type_Dsc',
	TRANSACTION_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Transaction_Type_Short_Dsc',
	REWARD_DOLLAR_START_TS TIMESTAMP_LTZ(9) COMMENT 'Reward_Dollar_Start_Ts',
	REWARD_DOLLAR_END_TS TIMESTAMP_LTZ(9) COMMENT 'Reward_Dollar_End_Ts',
	REWARD_DOLLAR_POINTS_QTY NUMBER(38,0) COMMENT 'Reward_Dollar_Points_Qty',
	REWARD_ORIGIN_CD VARCHAR(300) COMMENT 'Reward_Origin_Cd',
	REWARD_ORIGIN_DSC VARCHAR(50) COMMENT 'Reward_Origin_Dsc',
	REWARD_ORIGIN_TS TIMESTAMP_LTZ(9) COMMENT 'Reward_Origin_Ts',
	STATUS_CD VARCHAR(16777216) COMMENT 'Status_Cd',
	STATUS_DSC VARCHAR(50) COMMENT 'Status_Dsc',
	STATUS_EFFECTIVE_TS TIMESTAMP_LTZ(9) COMMENT 'Status_Effective_Ts',
	STATUS_TYPE_CD VARCHAR(16777216) COMMENT 'Status_Type_Cd',
	CUSTOMER_TIER_CD VARCHAR(50) COMMENT 'Customer_Tier_Cd',
	CUSTOMER_TIER_DSC VARCHAR(250) COMMENT 'Customer_Tier_Dsc',
	CUSTOMER_TIER_SHORT_DSC VARCHAR(50) COMMENT 'Customer_Tier_Short_Dsc',
	CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'Create_Ts',
	CREATE_USER_ID VARCHAR(100) COMMENT 'Create_User_Id',
	UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'Update_Ts',
	UPDATE_USER_ID VARCHAR(100) COMMENT 'Update_User_Id',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW_CREATE_TS',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'DW_SOURCE_CREATE_NM',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'DW_CURRENT_VERSION_IND',
	ALT_TRANSACTION_ID VARCHAR(100) COMMENT 'Alt_Transaction_Id',
	primary key (HOUSEHOLD_ID, TRANSACTION_ID, LOYALTY_PROGRAM_CD, TRANSACTION_TYPE_CD, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
