--liquibase formatted sql
--changeset SYSTEM:SP_GETNPSSURVEY_TO_BIM_LOAD_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_PRD;
use schema DW_APPL;

CREATE OR REPLACE TASK SP_GETNPSSURVEY_TO_BIM_LOAD_TASK
WAREHOUSE='EDM_ADMIN_WH'
SCHEDULE='120 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.GETNPSSURVEY_FLAT_R_STREAM')
AS CALL SP_GetNPSSurvey_To_BIM_load();

ALTER TASK SP_GETNPSSURVEY_TO_BIM_LOAD_TASK RESUME;