--liquibase formatted sql
--changeset SYSTEM:GET_SURVEY_SENTIMENT_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_APPL;

CREATE OR REPLACE TASK GET_SURVEY_SENTIMENT_TASK
WAREHOUSE='EDM_ADMIN_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.Get_SURVEY_SENTIMENT_Flat_R_STREAM')
AS CALL SP_GetNPS_SURVEY_SENTIMENT_To_BIM_load();

ALTER TASK GET_SURVEY_SENTIMENT_TASK RESUME;
