--liquibase formatted sql
--changeset SYSTEM:F_Multiclip runOnChange:true splitStatements:false OBJECT_TYPE:TABLE


use database EDM_CONFIRMED_PRD;
use schema EDM_CONFIRMED_PRD.dw_c_loyalty;

alter table CLIP_DETAILS set change_tracking = TRUE;

use database EDM_CONFIRMED_PRD;
use schema EDM_CONFIRMED_PRD.dw_c_product;

create table IF NOT EXISTS F_Multiclip
(
HHID   NUMBER(38,0)
,BANNER   VARCHAR(50)
,CLIP_SOURCE_CD   VARCHAR(16777216)
,OFFER_ID   NUMBER(38,0)
,CLIP_TYPE_CD   VARCHAR(50)
,OFFER_DESCRIPTION   VARCHAR(16777216)
,OFFER_TYPE   VARCHAR(16777216)
,DISCOUNT_TYPE   VARCHAR(16777216)
,LIMIT_TYPE   VARCHAR(16777216)
,MULTICLIP_LIMIT   NUMBER(38,0)
,REQUIRED_REWARDS   NUMBER(38,0)
,OFFER_$_VALUE   NUMBER(38,3)
,CLIP_ID   VARCHAR(16777216)
,Clip_Date DATE
,DW_CREATE_TS   TIMESTAMP_LTZ(9)
);
