--liquibase formatted sql
--changeset SYSTEM:BUSINESS_PARTNER_NOTE_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE BUSINESS_PARTNER_NOTE_EXCEPTIONS (
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0),
	PARTNER_NM VARCHAR(250),
	NOTES_TYPE_CD VARCHAR(30),
	NOTES_TYPE_TXT VARCHAR(2000),
	CREATIONDT DATE,
	FILENAME VARCHAR(16777216),
	DML_TYPE VARCHAR(16777216),
	SAMEDAY_CHG_IND VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
