--liquibase formatted sql
--changeset SYSTEM:Business_Partner_Contact_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE BUSINESS_PARTNER_CONTACT_EXCEPTIONS (
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0),
	PARTNER_NM VARCHAR(250),
	PARTNER_CONTACT_TYPE_CD VARCHAR(50),
	PARTNER_CONTACT_DSC VARCHAR(250),
	PARTNER_CONTACT_SHORT_DSC VARCHAR(50),
	PARTNER_CONTACT_NM VARCHAR(50),
	PARTNER_CONTACT_PHONE_NBR VARCHAR(50),
	PARTNER_CONTACT_EMAIL_ADDRESS_TXT VARCHAR(16777216),
	CREATIONDT TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
