--liquibase formatted sql
--changeset SYSTEM:BUSINESS_PARTNER_SITE_ORGANIZATION_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE BUSINESS_PARTNER_SITE_ORGANIZATION_EXCEPTIONS (
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0),
	PARTNER_PARTICIPANT_ID VARCHAR(50),
	PARTNER_SITE_ID VARCHAR(50),
	PARTNER_ID VARCHAR(50),
	PARTNER_SITE_ORGAIZATION_TYPE_CD VARCHAR(50),
	PARTNER_SITE_ORGANIZATION_VALUE_TXT VARCHAR(50),
	CREATIONDT TIMESTAMP_LTZ(9),
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(255),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
