--liquibase formatted sql
--changeset SYSTEM:Business_Partner_Service_Override runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_LOYALTY;

create or replace TABLE BUSINESS_PARTNER_SERVICE_OVERRIDE (
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0) NOT NULL COMMENT 'Business_Partner_Integration_Id',
	PARTNER_NM VARCHAR(250) NOT NULL COMMENT 'Partner_Nm',
	OVERRIDE_TYPE_CD VARCHAR(50) NOT NULL COMMENT 'Override_Type_Cd',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW_First_Effective_Dt',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW_Last_Effective_Dt',
	OVERRIDE_PARTNER_ID VARCHAR(50) COMMENT 'Override_Partner_Id',
	OVERRIDE_PARTNER_NM VARCHAR(250) COMMENT 'Override_Partner_Nm',
	OVERRIDE_IND BOOLEAN COMMENT 'Override_Ind',
	OVERRIDE_TYPE_DSC VARCHAR(250) COMMENT 'Override_Type_Dsc',
	OVERRIDE_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Override_Type_Short_Dsc',
	OVERRIDE_REASON_TYPE_CD VARCHAR(50) COMMENT 'Override_Reason_Type_Cd',
	OVERRIDE_REASON_TYPE_DSC VARCHAR(250) COMMENT 'Override_Reason_Type_Dsc',
	OVERRIDE_REASON_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Override_Reason_Type_Short_Dsc',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW_CREATE_TS',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'DW_SOURCE_CREATE_NM',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'DW_CURRENT_VERSION_IND',
	primary key (BUSINESS_PARTNER_INTEGRATION_ID, PARTNER_NM, OVERRIDE_TYPE_CD, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
