--liquibase formatted sql
--changeset SYSTEM:EDM_EPISODIC_OAMOEEARNS_STAGE_PRDBLOB_INC runOnChange:true splitStatements:false OBJECT_TYPE:PIPE
use database EDM_REFINED_PRD;
use schema DW_APPL;

Create or replace pipe EDM_EPISODIC_OAMOE_EARN_PIPE_PRDBLOB_INC
auto_ingest = true
integration = EDDW_PRD_SNOWPIPEINTEGRATION
as
COPY INTO EDM_REFINED_PRD.DW_R_LOYALTY.EPISODIC_OAMOEEARNS_FLAT
FROM
(SELECT  $1 ,$2 ,$3 ,$4 , $9, $10,$11 ,CURRENT_TIMESTAMP ,METADATA$FILENAME,$5, $6, $7, $8
	FROM @EDM_EPISODIC_GAMING_STAGE_PRDBLOB_INC/Merkle/ 
)
FILE_FORMAT = 'CSV_EPISODIC_GAMING'
PATTERN = '.*merkle_oamoe_earns.*[.]*'
ON_ERROR = 'SKIP_FILE'

--rollback DROP PIPE EDM_REFINED_PRD.DW_APPL.EDM_EPISODIC_OAMOEEARNS_STAGE_PRDBLOB_INC;
