--liquibase formatted sql
--changeset SYSTEM:SP_UBER_TO_BIM_LOAD_TASK runOnChange:true splitStatements:false OBJECT_TYPE:SP

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_APPL;

create or replace task SP_UBER_TO_BIM_LOAD_TASK
	warehouse=<<ENV2>>_INGESTION_SMALL_WH
	schedule='USING CRON 30 21 * * * America/Denver'
	QUERY_TAG='{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_UBER_TO_BIM_LOAD_TASK", "APPCODE":"EDM"}'
	when SYSTEM$STREAM_HAS_DATA ('<<EDM_DB_NAME_R>>.DW_APPL.UBER_ORDER_INFO_FLAT_R_STREAM')
  OR SYSTEM$STREAM_HAS_DATA ('<<EDM_DB_NAME_R>>.DW_APPL.UBER_TRANSACTION_INFO_FLAT_R_STREAM') 
  OR SYSTEM$STREAM_HAS_DATA	('<<EDM_DB_NAME_R>>.DW_APPL.UBER_CUSTOMER_INFO_FLAT_R_STREAM')
	as CALL SP_GetUBER_To_BIM_load();

ALTER TASK SP_UBER_TO_BIM_LOAD_TASK RESUME;
