--liquibase formatted sql
--changeset SYSTEM:OCGP_SWEEPSTAKE_WINNER runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_C_LOYALTY;

create or replace TABLE OCGP_PROGRAM (
	PROGRAM_CD VARCHAR(16777216) NOT NULL,
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL,
	DW_LAST_EFFECTIVE_DT DATE NOT NULL,
	PROGRAM_ID VARCHAR(16777216),
	PROGRAM_NM VARCHAR(16777216),
	PROGRAM_DSC VARCHAR(16777216),
	PROGRAM_TYPE_CD VARCHAR(16777216),
	PROGRAM_START_DT DATE,
	PROGRAM_END_DT DATE,
	MAINTENANCE_MODE_IND BOOLEAN,
	POST_PROGRAM_LIVE_DT DATE,
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
  PRIMARY KEY (PROGRAM_CD, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
