--changeset SYSTEM:KAFKAOUTQUEUE_MANUAL_REPROCESS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database <<EDM_DB_NAME_OUT>>;
use schema DW_STAGE;

CREATE OR REPLACE TRANSIENT TABLE KAFKAOUTQUEUE_MANUAL_REPROCESS AS 
SELECT * FROM <<EDM_DB_NAME_VIEW>>.DW_VIEWS.KAFKAOUTQUEUE WHERE 1=2;
