
--liquibase formatted sql
--changeset SYSTEM:EPE_TRANSACTION_HEADER_TMP_REBATE_REPROCESS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database <<EDM_DB_NAME>>;
use schema DW_STAGE;


create or replace TABLE EPE_TRANSACTION_HEADER_TMP_REBATE_REPROCESS (
	ORDER_ID VARCHAR(16777216),
	TRANSACTION_DT DATE,
	TXN_TM TIMESTAMP_TZ(9),
	HOUSEHOLD_ID NUMBER(38,0),
	STORE_ID VARCHAR(16777216),
	STORE_NBR NUMBER(38,0),
	TRANSACTION_INTEGRATION_ID NUMBER(38,0),
	RNK NUMBER(18,0)
);
