--liquibase formatted sql
--changeset SYSTEM:REDEMPTION_DIGITAL_NEPTUNE_KAFKAOUTQUEUE_O_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_OUT_PRD;
use schema DW_APPL;

CREATE OR REPLACE TASK REDEMPTION_DIGITAL_NEPTUNE_KAFKAOUTQUEUE_O_TASK
WAREHOUSE='PROD_DIGITAL_WH'
SCHEDULE='60 minute'
WHEN SYSTEM$STREAM_HAS_DATA('TXN_FACTS_DIGITAL_NEPTUNE_STREAM')
AS call EDM_CONFIRMED_OUT_PRD.DW_APPL.SP_Digital_Redemption_Neptune_To_KafkaOutQueue
('EDM_CONFIRMED_OUT_PRD.DW_APPL.TXN_FACTS_DIGITAL_NEPTUNE_STREAM' ,'EDM_CONFIRMED_OUT_PRD','EDM_VIEWS_PRD',
 'DW_STAGE');

ALTER TASK REDEMPTION_DIGITAL_NEPTUNE_KAFKAOUTQUEUE_O_TASK RESUME;