--liquibase formatted sql
--changeset SYSTEM:REDEMPTION_INLANE_NEPTUNE_KAFKAOUTQUEUE_O_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_OUT_PRD;
use schema DW_APPL;

CREATE OR REPLACE TASK REDEMPTION_INLANE_NEPTUNE_KAFKAOUTQUEUE_O_TASK
WAREHOUSE='PROD_DIGITAL_WH'
SCHEDULE='60 minute'
WHEN SYSTEM$STREAM_HAS_DATA('TXN_HDR_INLANE_NEPTUNE_O_STREAM')
AS call EDM_CONFIRMED_OUT_PRD.DW_APPL.SP_Inlane_Redemption_Neptune_To_KafkaOutQueue
('EDM_CONFIRMED_OUT_PRD.DW_APPL.TXN_HDR_INLANE_NEPTUNE_O_STREAM' ,'EDM_CONFIRMED_OUT_PRD','EDM_VIEWS_PRD',
 'DW_STAGE');

ALTER TASK REDEMPTION_INLANE_NEPTUNE_KAFKAOUTQUEUE_O_TASK RESUME;