--liquibase formatted sql
--changeset SYSTEM:OCGP_PROGRAM_ATTRIBUTE_FLAT runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<EDM_DB_NAME_R>>;
USE SCHEMA DW_R_LOYALTY;

CREATE OR REPLACE TABLE OCGP_PROGRAM_ATTRIBUTE_FLAT
(
	ID VARCHAR(16777216),
	PROGRAM_CD VARCHAR(16777216),
	SOURCE_NM VARCHAR(16777216),
	EARN_FREQUENCY_CD VARCHAR(16777216),
	EARN_LIMIT_TXT VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	DW_CREATETS TIMESTAMP_TZ(9)
 );


ALTER TABLE OCGP_PROGRAM_ATTRIBUTE_FLAT SET CHANGE_TRACKING = TRUE; 
