--liquibase formatted sql
--changeset SYSTEM:OCGP_PROGRAM_ATTRIBUTE runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_C_LOYALTY;

CREATE OR REPLACE TABLE OCGP_PROGRAM_ATTRIBUTE
(
	PROGRAM_CD VARCHAR(16777216) NOT NULL,
	SOURCE_NM VARCHAR(16777216) NOT NULL,
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL,
	DW_LAST_EFFECTIVE_DT DATE NOT NULL,
	EARN_FREQUENCY_CD VARCHAR(16777216),
	EARN_LIMIT_TXT VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_TZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_TZ(9),
	DW_LOGICAL_DELETE_IND  BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	PRIMARY KEY (PROGRAM_CD, SOURCE_NM, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);

