--liquibase formatted sql
--changeset SYSTEM:Create_rerun_tbl runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TRANSIENT TABLE MEAL_PLAN_INGREDIENT_RESTRICTION_FLAT_RERUN (
RESTRICTIONID VARCHAR(16777216),
INGREDIENTID VARCHAR(16777216),
ISWARNINGONLY VARCHAR(16777216),
DW_CREATETS TIMESTAMP_LTZ(9),
FILE_NAME VARCHAR(16777216),
METADATA$ACTION VARCHAR(10),
METADATA$ISUPDATE BOOLEAN,
METADATA$ROW_ID VARCHAR(40)
);
