--liquibase formatted sql
--changeset SYSTEM:Create_TASK_For_MealPlan runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_APPL;

ALTER TASK GET_MEAL_PLAN_RECIPE_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_RECIPE_TASK
		  WAREHOUSE = '<<WH>>'
		  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
		  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_Meal_Plan_Recipe_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
		  WHEN 
		  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_RECIPE_FLAT_R_STREAM')
		  AS 
		  CALL SP_GETMEAL_PLAN_RECIPE_TO_BIM_LOAD_MEAL_PLAN_RECIPE('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_RECIPE_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_RECIPE_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_CUISINE_TAG_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_CUISINE_TAG_TASK
		  WAREHOUSE = '<<WH>>'
		  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
		  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_CUISINE_TAG_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
		  WHEN 
		  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_CUISINE_TAG_FLAT_R_STREAM')
		  AS 
		  CALL SP_GETMEAL_PLAN_CUISINE_TAG_TO_BIM_LOAD_MEAL_PLAN_CUISINE_TAG('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_CUISINE_TAG_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_CUISINE_TAG_TASK RESUME;

ALTER TASK GET_RETAIL_CUSTOMER_DISLIKE_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_DISLIKE_TASK
		  WAREHOUSE = '<<WH>>'
		  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
		  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_DISLIKE_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
		  WHEN 
		  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_DISLIKE_FLAT_R_STREAM')
		  AS 
		  CALL SP_GETRETAIL_CUSTOMER_DISLIKE_TO_BIM_LOAD_RETAIL_CUSTOMER_DISLIKE('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_DISLIKE_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_DISLIKE_TASK RESUME;

ALTER TASK GET_RETAIL_CUSTOMER_DISLIKE_INGREDIENTS_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_DISLIKE_INGREDIENTS_TASK
	  WAREHOUSE = '<<WH>>'
	  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
	  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_DISLIKE_INGREDIENTS_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
	  WHEN 
	  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_DISLIKE_INGREDIENTS_FLAT_R_STREAM')
	  AS 
	  CALL SP_GETRETAIL_CUSTOMER_DISLIKE_INGREDIENTS_TO_BIM_LOAD_RETAIL_CUSTOMER_DISLIKE_INGREDIENTS('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_DISLIKE_INGREDIENTS_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_DISLIKE_INGREDIENTS_TASK RESUME;

ALTER TASK GET_RETAIL_CUSTOMER_FAVORITE_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_FAVORITE_TASK
              WAREHOUSE = '<<WH>>'
              SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
			  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_FAVORITE_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
              WHEN 
              SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_FAVORITE_FLAT_R_STREAM')
              AS 
              CALL SP_GETRETAIL_CUSTOMER_FAVORITE_TO_BIM_LOAD_RETAIL_CUSTOMER_FAVORITE('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_FAVORITE_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_FAVORITE_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_CUSTOMER_FLAG_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_CUSTOMER_FLAG_TASK
              WAREHOUSE = '<<WH>>'
              SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
			  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_CUSTOMER_FLAG_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
              WHEN 
              SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_CUSTOMER_FLAG_FLAT_R_STREAM')
              AS 
              CALL SP_GETMEAL_PLAN_CUSTOMER_FLAG_TO_BIM_LOAD_MEAL_PLAN_CUSTOMER_FLAG('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_CUSTOMER_FLAG_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_CUSTOMER_FLAG_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_INGREDIENT_RESTRICTION_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_INGREDIENT_RESTRICTION_TASK
	  WAREHOUSE = '<<WH>>'
	  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
	  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_INGREDIENT_RESTRICTION_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
	  WHEN 
	  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_INGREDIENT_RESTRICTION_FLAT_R_STREAM')
	  AS 
	  CALL SP_GetMeal_Plan_Ingredient_Restriction_TO_BIM_LOAD_Meal_Plan_Ingredient_Restriction('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_INGREDIENT_RESTRICTION_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_INGREDIENT_RESTRICTION_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_INGREDIENT_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_INGREDIENT_TASK
	  WAREHOUSE = '<<WH>>'
	  SCHEDULE ='USING CRON 0 20 * * * Asia/Kolkata'
	  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_INGREDIENT_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
	  WHEN 
	  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_INGREDIENT_FLAT_R_STREAM')
	  AS 
	  CALL SP_GetMeal_Plan_Ingredient_TO_BIM_LOAD_Meal_Plan_Ingredient('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_INGREDIENT_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_INGREDIENT_TASK RESUME;

ALTER TASK GET_RETAIL_CUSTOMER_MEAL_PLAN_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_MEAL_PLAN_TASK
              WAREHOUSE = '<<WH>>'
              SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
			  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_MEAL_PLAN_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
              WHEN 
               SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_MEAL_PLAN_FLAT_R_STREAM')
              AS 
              CALL SP_GETRETAIL_CUSTOMER_MEAL_PLAN_TO_BIM_LOAD_RETAIL_CUSTOMER_MEAL_PLAN('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_MEAL_PLAN_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_MEAL_PLAN_TASK RESUME;

ALTER TASK GET_RETAIL_CUSTOMER_PENDING_MEAL_TASK SUSPEND; 
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_PENDING_MEAL_TASK
	  WAREHOUSE = '<<WH>>'
	  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
	  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_PENDING_MEAL_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
	  WHEN
	  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_PENDING_MEAL_FLAT_R_STREAM')
	  AS
	  CALL SP_GETRETAIL_CUSTOMER_PENDING_MEAL_TO_BIM_LOAD_RETAIL_CUSTOMER_PENDING_MEAL('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_PENDING_MEAL_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_PENDING_MEAL_TASK RESUME; 

ALTER TASK GET_RETAIL_CUSTOMER_MEALPLAN_PROFILE_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_MEALPLAN_PROFILE_TASK
  WAREHOUSE = '<<WH>>'
  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_MEALPLAN_PROFILE_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
  WHEN 
  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_MEALPLAN_PROFILE_FLAT_R_STREAM')
  AS 
  CALL SP_GETRETAIL_CUSTOMER_MEALPLAN_PROFILE_TO_BIM_LOAD_RETAIL_CUSTOMER_MEALPLAN_PROFILE('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_MEALPLAN_PROFILE_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_MEALPLAN_PROFILE_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_RESTRICTION_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_RESTRICTION_TASK
  WAREHOUSE = '<<WH>>'
  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_RESTRICTION_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
  WHEN 
  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_RESTRICTION_FLAT_R_STREAM')
  AS 
  CALL SP_GetMeal_Plan_Restriction_TO_BIM_LOAD_Meal_Plan_Restriction('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_RESTRICTION_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_RESTRICTION_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_VARIETY_TAG_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_VARIETY_TAG_TASK
  WAREHOUSE = '<<WH>>'
  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_VARIETY_TAG_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
  WHEN 
  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_VARIETY_TAG_FLAT_R_STREAM')
  AS 
  CALL SP_GetMeal_Plan_Variety_Tag_TO_BIM_LOAD_Meal_Plan_Variety_Tag('<<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_VARIETY_TAG_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_VARIETY_TAG_TASK RESUME;


ALTER TASK GET_RETAIL_CUSTOMER_PROFILE_TO_RESTRICTION_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_PROFILE_TO_RESTRICTION_TASK
  WAREHOUSE = '<<WH>>'
  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_PROFILE_TO_RESTRICTION_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
  WHEN 
  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_PROFILE_TO_RESTRICTION_FLAT_R_STREAM')
  AS 
  CALL SP_GetRetail_Customer_Profile_To_Restriction_TO_BIM_LOAD_Retail_Customer_Profile_To_Restriction('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_PROFILE_TO_RESTRICTION_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_PROFILE_TO_RESTRICTION_TASK RESUME;

ALTER TASK GET_MEAL_PLAN_APP_FEEDBACK_TASK SUSPEND;
CREATE OR REPLACE TASK GET_MEAL_PLAN_APP_FEEDBACK_TASK
	  WAREHOUSE = '<<WH>>'
	  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
	  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_MEAL_PLAN_APP_FEEDBACK_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
	  WHEN
	  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETMeal_Plan_App_Feedback_FLAT_R_STREAM')
	  AS
	  CALL SP_GETMEAL_PLAN_APP_FEEDBACK_TO_BIM_LOAD_MEAL_PLAN_APP_FEEDBACK('<<EDM_DB_NAME_R>>.DW_APPL.GETMeal_Plan_App_Feedback_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_MEAL_PLAN_APP_FEEDBACK_TASK RESUME;

ALTER TASK GET_RETAIL_CUSTOMER_DISLIKE_TO_PROFILE_TASK SUSPEND;
CREATE OR REPLACE TASK GET_RETAIL_CUSTOMER_DISLIKE_TO_PROFILE_TASK
  WAREHOUSE = '<<WH>>'
  SCHEDULE = 'USING CRON 0 20 * * * Asia/Kolkata'
  QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"GET_RETAIL_CUSTOMER_DISLIKE_TO_PROFILE_TASK", "APPCODE":"DIRM", "TECHNICAL_CONTACT":"LOYALTY"}'
  WHEN 
  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_DISLIKE_TO_PROFILE_FLAT_R_STREAM')
  AS 
  CALL SP_GetRetail_Customer_Dislike_To_Profile_TO_BIM_LOAD_Retail_Customer_Dislike_To_Profile('<<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_DISLIKE_TO_PROFILE_FLAT_R_STREAM','<<EDM_DB_NAME>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK GET_RETAIL_CUSTOMER_DISLIKE_TO_PROFILE_TASK RESUME;

