--liquibase formatted sql
--changeset SYSTEM:Create_RERUN_for_MealPlan runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA <<EDM_DB_NAME>>.DW_C_STAGE;

CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Recipe_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Recipe_Flat_R_STREAM where 1=2;  


CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Cuisine_Tag_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Cuisine_Tag_Flat_R_STREAM where 1=2;	


CREATE OR REPLACE TRANSIENT TABLE Retail_Customer_Dislike_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetRetail_Customer_Dislike_Flat_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Retail_Customer_Dislike_Ingredients_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetRetail_Customer_Dislike_Ingredients_Flat_R_STREAM where 1=2;	


CREATE OR REPLACE TRANSIENT TABLE RETAIL_CUSTOMER_FAVORITE_FLAT_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_FAVORITE_FLAT_R_STREAM where 1=2;  
 

CREATE OR REPLACE TRANSIENT TABLE MEAL_PLAN_CUSTOMER_FLAG_FLAT_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GETMEAL_PLAN_CUSTOMER_FLAG_FLAT_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Ingredient_Restriction_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Ingredient_Restriction_Flat_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Ingredient_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Ingredient_Flat_R_STREAM where 1=2;	


CREATE OR REPLACE TRANSIENT TABLE RETAIL_CUSTOMER_MEAL_PLAN_FLAT_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GETRETAIL_CUSTOMER_MEAL_PLAN_FLAT_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Retail_Customer_Pending_Meal_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM  <<EDM_DB_NAME_R>>.DW_APPL.GetRetail_Customer_Pending_Meal_Flat_R_STREAM where 1=2;	


CREATE OR REPLACE TRANSIENT TABLE Retail_Customer_MealPlan_Profile_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM  <<EDM_DB_NAME_R>>.DW_APPL.GetRetail_Customer_MealPlan_Profile_Flat_R_STREAM where 1=2;
 

CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Restriction_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Restriction_Flat_R_STREAM where 1=2;	


CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Variety_Tag_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Variety_Tag_Flat_R_STREAM where 1=2;	


CREATE OR REPLACE TRANSIENT TABLE Retail_Customer_Profile_To_Restriction_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetRetail_Customer_Profile_To_Restriction_Flat_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_App_Feedback_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM  <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_App_Feedback_Flat_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Retail_Customer_Dislike_To_Profile_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetRetail_Customer_Dislike_To_Profile_Flat_R_STREAM where 1=2;


CREATE OR REPLACE TRANSIENT TABLE Meal_Plan_Customer_Flat_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetMeal_Plan_Customer_Flat_R_STREAM where 1=2;
