--liquidbase formatted sql
--changeset SYSTEM:CUSTOMER_IDS runOnChange: true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<TAB_DEPLOY_SCHEMA>>;

create or replace TABLE <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.CATALINA_OUTBOUND_LOAD_STATUS (
	ID NUMBER(38,0) autoincrement,
	TABLE_NAME VARCHAR(16777216),
	LOAD_STATUS VARCHAR(16777216),
	RUN_DATE DATE,
	DW_CREATE_TS TIMESTAMP_NTZ(9)
);
