--liquidbase formatted sql
--changeset SYSTEM:CUSTOMER_IDS runOnChange: true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<TAB_DEPLOY_SCHEMA>>;

create or replace TABLE <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.ITEMS_IN_ORDER_Incremental (
	RETAILER_ID VARCHAR(50),
	RETAIL_STORE_ID VARCHAR(20),
	TRANSACTION_DATE DATE,
	TRANSACTION_TIME TIMESTAMP_TZ(9),
	LANE_ID NUMBER(38,0),
	REGISTER_NAME VARCHAR(30),
	TRANSACTION_ID NUMBER(38,0),
	TRADE_ITEM_ID NUMBER(14,0),
	TRADE_ITEM_ID_TYPE VARCHAR(50),
	MEASURE_QTY NUMBER(14,4),
	ITEM_QTY NUMBER(14,4),
	UNIT_OF_MEASURE VARCHAR(50),
	UNIT_QUANTITY NUMBER(14,4),
	UNIT_PRICE NUMBER(14,4),
	SCAN_UNIT_IND BOOLEAN,
	GROSS_AMT NUMBER(14,4),
	EQUIVALIZED_FACTOR_SOURCE_UPDATE_IND BOOLEAN,
	ITEM_DSC VARCHAR(1024),	
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
