--liquidbase formatted sql
--changeset SYSTEM:CUSTOMER_IDS runOnChange: true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<TAB_DEPLOY_SCHEMA>>;

create or replace TABLE <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.ORDER_INFO_Incremental (
	RETAILER_ID VARCHAR(50),
	RETAIL_STORE_ID VARCHAR(16777216),
	TRANSACTION_DATE DATE NOT NULL,
	TRANSACTION_TIME TIMESTAMP_TZ(9) NOT NULL,
	LANE_ID NUMBER(38,0),
	REGISTER_NAME VARCHAR(30),
	TRANSACTION_ID NUMBER(38,0) NOT NULL,
	OPERATOR_ID NUMBER(38,0),
	LANE_TYPE_CODE VARCHAR(50),
	ORDER_INITIATION_LOCATION VARCHAR(50),
	ORDER_DELIVERY_LOCATION VARCHAR(50),
	PAYMENT_TYPE_CODE NUMBER(38,0),
	PAYMENT_TYPE_DESC VARCHAR(40),
	TENDER_AMT NUMBER(14,4),
	ORDER_TOTAL_AMOUNT NUMBER(14,4),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
