--liquidbase formatted sql
--changeset SYSTEM:CUSTOMER_IDS runOnChange: true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<TAB_DEPLOY_SCHEMA>>;

create or replace TABLE <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.ITEM_PRICE_ADJUSTMENTS_Incremental (
	RETAILER_ID VARCHAR(50),
	RETAIL_STORE_ID VARCHAR(16777216),
	TRANSACTION_DATE DATE NOT NULL,
	TRANSACTION_TIME TIMESTAMP_TZ(9) NOT NULL,
	LANE_ID NUMBER(38,0),
	REGISTER_NAME VARCHAR(30),
	TRANSACTION_ID NUMBER(38,0) NOT NULL,
	TRADE_ITEM_ID NUMBER(14,0),
	ADJUSTMENT_ID NUMBER(38,0),
	ADJUSTMENT_TYPE_CODE VARCHAR(16777216),
	APPLICABLE_UNIT_QUANTITY NUMBER(38,0),
	ADJUSTMENT_UNIT_AMOUNT NUMBER(9,2),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
