--liquidbase formatted sql
--changeset SYSTEM:ORDER_INFO runOnChange: true splitStatements:false OBJECT_TYPE:VIEW

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<VW_DEPLOY_SCHEMA>>;

CREATE OR REPLACE SECURE VIEW <<TGT_EDM_DB_NAME>>.<<VW_DEPLOY_SCHEMA>>.ORDER_INFO COPY GRANTS as

WITH FULLFILLMENT AS (    
    SELECT DISTINCT ORDER_ID, FULLFILLMENT_TYPE_CD from <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.GROCERY_SUB_ORDER
    WHERE DW_CURRENT_VERSION_IND = TRUE and FULLFILLMENT_TYPE_CD IS NOT NULL
)

select 
    RS.BANNER_NM as RETAILER_ID
    ,TH.FACILITY_NBR as RETAIL_STORE_ID 
    ,TH.Transaction_DT as TRANSACTION_DATE
    ,TH.TRANSACTION_TS as TRANSACTION_TIME
    ,TH.REGISTER_NBR as LANE_ID
    ,RT.REGISTER_DEPARTMENT_NM as REGISTER_NAME
    ,TH.TRANSACTION_ID as TRANSACTION_ID
    ,TH.CHECKER_NBR as OPERATOR_ID
    ,CASE 
       WHEN GOH.ORDER_ID IS NOT NULL THEN 'ONLINE'
       ELSE 'INSTORE'
     END as LANE_TYPE_CODE
    ,CASE WHEN GOH.ORDER_ID IS NULL THEN 'INSTORE'
		ELSE GOH.DEVICE_CD 
	 END as ORDER_INITIATION_LOCATION
    ,CASE
        WHEN GOH.ORDER_ID IS NOT NULL THEN GSO.FULLFILLMENT_TYPE_CD
        ELSE 'INSTORE'
     END as ORDER_DELIVERY_LOCATION
    ,TT.TENDER_SUBTYPE_ID AS PAYMENT_TYPE_CODE
    ,TS.TENDER_SUBTYPE_DSC as PAYMENT_TYPE_DESC
    ,TT.TENDER_AMT AS TENDER_AMT
    ,TH.total_gross_amt + TH.total_tax_amt + TH.total_markdown_amt + TH.total_manufacturer_coupon_amt - TH.total_miscellaneous_amt as ORDER_TOTAL_AMOUNT
    

FROM <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.TRANSACTION_HDR TH
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.D1_RETAIL_STORE RS
ON TH.FACILITY_NBR = RS.RETAIL_STORE_FACILITY_NBR
AND RS.DW_LOGICAL_DELETE_IND = TRUE
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.GROCERY_ORDER_HEADER GOH
ON TH.ORDER_ID = GOH.ORDER_ID
AND GOH.DW_CURRENT_VERSION_IND = TRUE
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_EDW_SCHEMA_NAME>>.REGISTER_TYPE RT
ON TH.REGISTER_NBR = RT.REGISTER_NBR
LEFT JOIN FULLFILLMENT GSO 
ON GSO.ORDER_ID = TH.ORDER_ID
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.TRANSACTION_TENDER TT
ON TH.TRANSACTION_HDR_INTEGRATION_ID = TT.TRANSACTION_HDR_INTEGRATION_ID
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_EDW_SCHEMA_NAME>>.TENDER_SUBTYPE TS
ON TT.TENDER_SUBTYPE_ID = TS.TENDER_SUBTYPE_ID
where TH.TRANSACTION_DT BETWEEN TO_DATE('2022-11-01') AND TO_DATE('2022-11-30');

