--liquidbase formatted sql
--changeset SYSTEM:ITEM_PRICE_ADJUSTMENTS runOnChange: true splitStatements:false OBJECT_TYPE:VIEW

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<VW_DEPLOY_SCHEMA>>;

CREATE OR REPLACE SECURE VIEW <<TGT_EDM_DB_NAME>>.<<VW_DEPLOY_SCHEMA>>.ITEM_PRICE_ADJUSTMENTS_Incremental COPY GRANTS as

select 
	RETAILER_ID,
	RETAIL_STORE_ID,
	TRANSACTION_DATE,
	TRANSACTION_TIME,
	LANE_ID,
	REGISTER_NAME,
	TRANSACTION_ID,
	TRADE_ITEM_ID,
	ADJUSTMENT_ID,
	ADJUSTMENT_TYPE_CODE,
	APPLICABLE_UNIT_QUANTITY,
	ADJUSTMENT_UNIT_AMOUNT,
	DW_CREATE_TS as LOAD_TIME
from <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.ITEM_PRICE_ADJUSTMENTS_Incremental;
