--liquidbase formatted sql
--changeset SYSTEM:ITEMS_IN_ORDER runOnChange: true splitStatements:false OBJECT_TYPE:VIEW

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<VW_DEPLOY_SCHEMA>>;

CREATE OR REPLACE SECURE VIEW <<TGT_EDM_DB_NAME>>.<<VW_DEPLOY_SCHEMA>>.ITEMS_IN_ORDER_Incremental COPY GRANTS as
select 

	RETAILER_ID,
	RETAIL_STORE_ID,
	TRANSACTION_DATE,
	TRANSACTION_TIME,
	LANE_ID,
	REGISTER_NAME,
	TRANSACTION_ID,
	TRADE_ITEM_ID,
	TRADE_ITEM_ID_TYPE,
	MEASURE_QTY,
	ITEM_QTY,
	UNIT_OF_MEASURE,
	UNIT_QUANTITY,
	UNIT_PRICE,
	SCAN_UNIT_IND,
	GROSS_AMT,
	EQUIVALIZED_FACTOR_SOURCE_UPDATE_IND,
	ITEM_DSC,
	DW_CREATE_TS  as LOAD_TIME
FROM <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.ITEMS_IN_ORDER_Incremental;
