--liquidbase formatted sql
--changeset SYSTEM:ITEMS_IN_ORDER runOnChange: true splitStatements:false OBJECT_TYPE:VIEW

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<VW_DEPLOY_SCHEMA>>;

CREATE OR REPLACE SECURE VIEW <<TGT_EDM_DB_NAME>>.<<VW_DEPLOY_SCHEMA>>.ITEMS_IN_ORDER_FULLTABLE COPY GRANTS as
select 
    RS.BANNER_NM as RETAILER_ID
    ,TH.FACILITY_NBR as RETAIL_STORE_ID 
    ,TH.Transaction_DT as TRANSACTION_DATE
    ,TH.TRANSACTION_TS as TRANSACTION_TIME
    ,TH.REGISTER_NBR as LANE_ID
    ,RT.REGISTER_DEPARTMENT_NM as REGISTER_NAME
    ,TH.TRANSACTION_ID as TRANSACTION_ID
    ,TI.UPC_NBR as TRADE_ITEM_ID
    ,CASE
       WHEN length(TI.UPC_NBR) < 6 then 'PLU'
       ELSE 'UPC'
     END as TRADE_ITEM_ID_TYPE
    ,TI.MEASURE_QTY as MEASURE_QTY
    ,TI.ITEM_QTY as ITEM_QTY
    ,CASE
       WHEN GD.ORDER_ID IS NOT NULL THEN UPPER(GD.UOM_CD)
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY = 0 THEN 'Each'
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY <> 0 AND D1U.SCAN_UNIT_IND = TRUE THEN 'Each'
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY <> 0 AND D1U.SCAN_UNIT_IND = FALSE THEN 'Lb'
	   ELSE 'N/A'
     END as UNIT_OF_MEASURE
    ,CASE
       WHEN GD.ORDER_ID IS NOT NULL THEN GD.ORDER_QTY
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY = 0 THEN TI.ITEM_QTY
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY <> 0 AND D1U.SCAN_UNIT_IND = TRUE THEN TI.ITEM_QTY
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY <> 0 AND D1U.SCAN_UNIT_IND = FALSE THEN TI.MEASURE_QTY
     END as UNIT_QUANTITY
    ,CASE
       WHEN GD.ORDER_ID IS NOT NULL THEN GD.UNIT_PRICE_AMT
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY = 0 THEN TI.GROSS_AMT/TI.ITEM_QTY
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY <> 0 AND D1U.SCAN_UNIT_IND = TRUE THEN TI.GROSS_AMT/TI.ITEM_QTY
       WHEN GD.ORDER_ID IS NULL AND TI.MEASURE_QTY <> 0 AND D1U.SCAN_UNIT_IND = FALSE THEN TI.GROSS_AMT/TI.MEASURE_QTY
     END as UNIT_PRICE
    ,D1U.SCAN_UNIT_IND
    ,TI.GROSS_AMT
    ,D1U.EQUIVALIZED_FACTOR_SOURCE_UPDATE_IND
    ,D1U.ITEM_DSC
FROM <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.TRANSACTION_HDR TH
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.TRANSACTION_ITEM TI
ON TH.TRANSACTION_HDR_INTEGRATION_ID = TI.TRANSACTION_HDR_INTEGRATION_ID
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.D1_RETAIL_STORE RS
ON TH.FACILITY_NBR = RS.RETAIL_STORE_FACILITY_NBR
AND RS.DW_LOGICAL_DELETE_IND = TRUE
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.GROCERY_ORDER_DETAIL GD
ON TH.ORDER_ID = GD.ORDER_ID
AND TI.UPC_NBR = GD.UPC_NBR
AND GD.DW_CURRENT_VERSION_IND = TRUE
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_EDW_SCHEMA_NAME>>.REGISTER_TYPE RT
ON TH.REGISTER_NBR = RT.REGISTER_NBR
LEFT JOIN <<SRC_EDM_DB_NAME>>.<<SRC_EDM_SCHEMA_NAME>>.D1_UPC D1U
ON TI.UPC_NBR = D1U.UPC_NBR
where TH.TRANSACTION_DT BETWEEN TO_DATE('2022-07-01') AND TO_DATE('2023-02-28');
