--liquidbase formatted sql
--changeset SYSTEM:ORDER_INFO runOnChange: true splitStatements:false OBJECT_TYPE:VIEW

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<VW_DEPLOY_SCHEMA>>;

CREATE OR REPLACE SECURE VIEW <<TGT_EDM_DB_NAME>>.<<VW_DEPLOY_SCHEMA>>.ORDER_INFO_Incremental COPY GRANTS as
SELECT
	RETAILER_ID,
	RETAIL_STORE_ID,
	TRANSACTION_DATE,
	TRANSACTION_TIME,
	LANE_ID,
	REGISTER_NAME,
	TRANSACTION_ID,
	OPERATOR_ID,
	LANE_TYPE_CODE,
	ORDER_INITIATION_LOCATION,
	ORDER_DELIVERY_LOCATION,
	PAYMENT_TYPE_CODE,
	PAYMENT_TYPE_DESC,
	TENDER_AMT,
	ORDER_TOTAL_AMOUNT,
	DW_CREATE_TS as LOAD_TIME
FROM <<TGT_EDM_DB_NAME>>.<<TAB_DEPLOY_SCHEMA>>.ORDER_INFO_Incremental;
