--liquibase formatted sql
--changeset SYSTEM:SP_GETSHOPPINGLIST_TO_BIM_LOAD_J4U_COUPON_CLIP_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_PRD;
use schema DW_APPL;

CREATE OR REPLACE TASK SP_GETSHOPPINGLIST_TO_BIM_LOAD_J4U_COUPON_CLIP_TASK
WAREHOUSE='EDM_ADMIN_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.GETSHOPPINGLIST_FLAT_R_STREAM')
AS CALL SP_GetShoppingList_To_BIM_load();

ALTER TASK SP_GETSHOPPINGLIST_TO_BIM_LOAD_J4U_COUPON_CLIP_TASK RESUME;