create or replace task GENERIC_ARCHIVE_EDM_LOYALTY_TASK
	warehouse=PROD_INGESTION_SMALL_WH
	schedule='USING CRON  5 0 * * * America/Los_Angeles'
	USER_TASK_TIMEOUT_MS=14400000
	QUERY_TAG='{"OBJECT_TYPE":"TASK", 
"OBJECT_NAME":"GENERIC_ARCHIVE_EDM_LOYALTY_TASK", "APPCODE":"EDDW", "APPID":"DSU", "SUBJECTAREA":"LOYALTY", "BOD": "LOYALTY", 
"PROCESS": "GENERIC_ARCHIVE_PROCESS", "COMMENT": "Task Tag"}'
	as call SP_Generic_archive('EDM_LOYALTY');
