--liquibase formatted sql
--changeset SYSTEM:Create_WRK_Table runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database <<EDM_DB_NAME>>;
use schema DW_C_STAGE;


create or replace TRANSIENT TABLE F_PARTNER_CUSTOMER_INSIGHT_WORK (
	CUSTOMER_INSIGHT_F_SK NUMBER(38,0),
	DAY_ID NUMBER(10,0),
	RETAIL_CUSTOMER_HOUSEHOLD_D1_SK NUMBER(38,0),
	BUSINESS_PARTNER_D1_SK NUMBER(38,0),
	RETAIL_STORE_D1_SK NUMBER(38,0),
	BANNER_D1_SK NUMBER(38,0),
	DIVISION_D1_SK NUMBER(38,0),
	HOUSEHOLD_ID VARCHAR(16777216),
	TRANSACTION_DT DATE,
	PRODUCT_GROUP_NM VARCHAR(16777216),
	ORDER_ID VARCHAR(50),
	GMV_ORDER_VALUE_AMT NUMBER(12,2),
	LOYALTY_INDICATOR_CD VARCHAR(16777216),
	FRESHPASS_SUBSCRIBED_IND BOOLEAN,
	B4U_LINKED_IND BOOLEAN,
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
