--liquibase formatted sql
--changeset SYSTEM:Offer_red_wrk_tbl runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TRANSIENT TABLE OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_WRK (
	TRANSACTION_INTEGRATION_ID NUMBER(38,0),
	DW_FIRST_EFFECTIVE_DT DATE,
	DW_LAST_EFFECTIVE_DT DATE,
	TERMINAL_NBR VARCHAR(16777216),
	TRANSACTION_ID NUMBER(38,0),
	ORDER_ID VARCHAR(16777216),
	HOUSEHOLD_ID NUMBER(38,0),
	STATUS_CD VARCHAR(16777216),
	CREATE_DT DATE,
	SOURCE_SYSTEM_CD VARCHAR(16777216),
	TOTAL_CARD_SAVINGS_AMT NUMBER(38,5),
	TRANSACTION_TOTAL_AMT NUMBER(38,5),
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	STORE_NBR VARCHAR(16777216),
	REGISTER_TRANSACTION_SEQUENCE_NBR NUMBER(38,0),
	TRANSACTION_TS TIMESTAMP_TZ(9),
	FULFILLMENT_STORE_NBR VARCHAR(16777216),
	METADATA$ACTION VARCHAR(6),
	METADATA$ISUPDATE BOOLEAN,
	METADATA$ROW_ID VARCHAR(40)
);

create or replace TABLE OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_WRK (
	STORE VARCHAR(16777216),
	LANE VARCHAR(16777216),
	TRANSACTION_NUMBER NUMBER(38,0),
	HHID NUMBER(38,0),
	REDEMPTION_COUNT NUMBER(38,0),
	REDEMPTION_AMOUNT NUMBER(10,2),
	POINTS_AMOUNT NUMBER(10,2),
	POINTS_PROGRAMNAME VARCHAR(16777216),
	TRANSACTION_DATE TIMESTAMP_TZ(9),
	OFFER_ID VARCHAR(16777216),
	OFFER_START_DATE DATE,
	OFFER_END_DATE DATE,
	CLIPS_TOTALCOLUMN NUMBER(18,0),
	REDEMPTION_TOTALCOLUMN NUMBER(18,0),
	MARKDOWN_TOTALCOLUMN NUMBER(38,2),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
