--liquibase formatted sql
--changeset SYSTEM:Offer_red_task runOnChange:true splitStatements:false OBJECT_TYPE:SP

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA <<EDM_DB_NAME>>.DW_APPL;

CREATE OR REPLACE TASK OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Task
WAREHOUSE = '<<WH>>'
SCHEDULE = '1 minutes'
WHEN
SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream')
AS
call <<EDM_DB_NAME>>.DW_APPL.SP_LOAD_OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY();


ALTER TASK OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Task RESUME;
