--liquibase formatted sql
--changeset SYSTEM:Alter_Tables runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE Database <<EDM_DB_NAME>>;
Use Schema dw_c_stage;


Alter table <<EDM_DB_NAME>>.dw_c_stage.EPE_Transaction_Header_Savings_Exceptions
drop COLUMN if exists Program_Type_Cd ;

Alter table <<EDM_DB_NAME>>.dw_c_stage.EPE_Transaction_Item_Savings_Exceptions
drop COLUMN if exists Program_Type_Cd ;

Alter table <<EDM_DB_NAME>>.dw_c_stage.EPE_Transaction_Header_Savings_Exceptions
Add Column Program_Type_Cd String;

Alter table <<EDM_DB_NAME>>.dw_c_stage.EPE_Transaction_Item_Savings_Exceptions
Add Column Program_Type_Cd String;


 Create or replace TRANSIENT table  <<EDM_DB_NAME_R>>.DW_R_STAGE.GetEPETransaction_Flat_wrk
  as select * from  <<EDM_DB_NAME_R>>.DW_APPL.GetEPETransaction_Flat_R_STREAM where 1=2;
  
  Alter Table  <<EDM_DB_NAME_R>>.DW_R_STAGE.GetEPETransaction_Flat_wrk
  Modify column METADATA$ACTION VARCHAR(16777216),METADATA$ROW_ID VARCHAR(16777216);
  
 Create or replace TRANSIENT table  <<EDM_DB_NAME_R>>.DW_R_STAGE.GetEPETransaction_Flat_Rerun
  as select * from  <<EDM_DB_NAME_R>>.DW_APPL.GetEPETransaction_Flat_R_STREAM where 1=2;
    
  Alter Table  <<EDM_DB_NAME_R>>.DW_R_STAGE.GetEPETransaction_Flat_Rerun
  Modify column METADATA$ACTION VARCHAR(16777216),METADATA$ROW_ID VARCHAR(16777216);
  
  CREATE OR REPLACE STREAM <<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_HEADER_SAVINGS
ON TABLE <<EDM_DB_NAME>>.DW_C_RETAILSALE.EPE_TRANSACTION_HEADER_SAVINGS;
 
CREATE OR REPLACE STREAM <<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_ITEM_SAVINGS
ON TABLE <<EDM_DB_NAME>>.DW_C_RETAILSALE.EPE_TRANSACTION_ITEM_SAVINGS;
  
  CREATE OR REPLACE TRANSIENT TABLE <<EDM_DB_NAME>>.DW_C_STAGE.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_HEADER_SAVINGS_WRK
  as SELECT * FROM <<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_HEADER_SAVINGS where 1=2;
  
  Alter table <<EDM_DB_NAME>>.DW_C_STAGE.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_HEADER_SAVINGS_WRK
   Modify column METADATA$ACTION VARCHAR(16777216),METADATA$ROW_ID VARCHAR(16777216);

  CREATE OR REPLACE TRANSIENT TABLE <<EDM_DB_NAME>>.DW_C_STAGE.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_ITEM_SAVINGS_WRK
  as SELECT * FROM <<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_ITEM_SAVINGS where 1=2;
  
  Alter table <<EDM_DB_NAME>>.DW_C_STAGE.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_ITEM_SAVINGS_WRK
   Modify column METADATA$ACTION VARCHAR(16777216),METADATA$ROW_ID VARCHAR(16777216); 
