--liquibase formatted sql
--changeset SYSTEM:Air_Mile_Points_Detail runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_LOYALTY;

create or replace TABLE AIR_MILE_POINTS_DETAIL (
	BATCH_ID VARCHAR(100) NOT NULL COMMENT 'The timestamp the record was inserted.',
	HOUSEHOLD_ID NUMBER(38,0) NOT NULL COMMENT 'Unique identifier of the Household. The aggregateId in CHMS service is the HHID unlike the other services where the aggegatedid we map to the CustomerId',
	TRANSACTION_ID VARCHAR(100) NOT NULL COMMENT 'Transaction Id for AirMiles.',
	TRANSACTION_TS TIMESTAMP_LTZ(9) NOT NULL COMMENT 'This is the timestamp when the transaction was updated.',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	TRANSACTION_DATE_TXT VARCHAR(10) COMMENT 'This is the date when the transaction was updated.',
	TRANSACTION_TYPE_CD VARCHAR(50) COMMENT 'Transaction type code for the transaction.',
	TRANSACTION_TYPE_DSC VARCHAR(250) COMMENT 'Transaction type Description for the transaction.',
	TRANSACTION_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Transaction type Short Description for the transaction.',
	TRANSACTION_REASON_CD VARCHAR(50) COMMENT 'Transaction Reason code for the transaction.',
	TRANSACTION_REASON_DSC VARCHAR(250) COMMENT 'Transaction Reason Description for the transaction.',
	TRANSACTION_REASON_SHORT_DSC VARCHAR(50) COMMENT 'Transaction Reason Short Description for the transaction.',
	TRANSACTION_REFERENCE_NBR VARCHAR(100) COMMENT 'Can be used as a cross reference nbr from external systems for the internal transaction id.',
	ALTERNATE_TRANSACTION_ID VARCHAR(100) COMMENT 'Alternate transaction Ids linked to the partner transaction.',
	ALTERNATE_TRANSACTION_TYPE_CD VARCHAR(50) COMMENT 'Alternate transaction Code linked to the partner transaction.',
	ALTERNATE_TRANSACTION_TYPE_DSC VARCHAR(250) COMMENT 'Alternate transaction Description linked to the partner transaction.',
	ALTERNATE_TRANSACTION_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Alternate transaction Short Description linked to the partner transaction.',
	ALTERNATE_TRANSACTION_TS TIMESTAMP_LTZ(9) COMMENT 'This is the timestamp when the transaction was updated.',
	RECORD_TYPE_CD VARCHAR(50) COMMENT 'Code that Can be used to specify type of record.',
	RECORD_TYPE_DSC VARCHAR(250) COMMENT 'Description that Can be used to specify type of record.',
	RECORD_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Short Description that Can be used to specify type of record.',
	AIR_MILE_PROGRAM_ID VARCHAR(16777216) COMMENT 'AirMilePoints program Unique Identifier',
	AIR_MILE_PROGRAM_NM VARCHAR(200) COMMENT 'AirMilePoints program name',
	AIR_MILE_TIER_NM VARCHAR(200) COMMENT 'AirMilePoints Tier program name',
	AIR_MILE_POINT_QTY NUMBER(38,0) COMMENT 'Number of AirMiles in the Transaction file. Note that AirMiles are calculated from  customers rewards/points they have earned.',
	CUSTOMER_FORMATTED_NM VARCHAR(16777216) COMMENT 'Customer formatted name invloved with the transaction.',
	CUSTOMER_PREFERRED_SALUTION_CD VARCHAR(50) COMMENT 'Customer preferred Salution Code invloved with the transaction.',
	CUSTOMER_TITLE_CD VARCHAR(50) COMMENT 'Customer Title Code invloved with the transaction.',
	CUSTOMER_GIVEN_NM VARCHAR(16777216) COMMENT 'Customer Given name invloved with the transaction.',
	CUSTOMER_NICK_NM VARCHAR(16777216) COMMENT 'Customer Nick name invloved with the transaction.',
	CUSTOMER_MIDDLE_NM VARCHAR(16777216) COMMENT 'Middle Name of the Customer involved with the Transaction',
	CUSTOMER_FAMILY_NM VARCHAR(16777216) COMMENT 'Family Name of the Customer involved with the Transaction',
	CUSTOMER_MAIDEN_NM VARCHAR(16777216) COMMENT 'Maiden Name of the Customer involved with the Transaction',
	CUSTOMER_GENERATION_AFFIX_CD VARCHAR(50) COMMENT 'Customer Generation Affix code involved with the Transaction',
	CUSTOMER_QUALIFICATION_AFFIX_CD VARCHAR(50) COMMENT 'Customer Qualification Affix Code involved with the transaction',
	CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'Date and time when the record was created in the source system.',
	CREATE_USER_ID VARCHAR(50) COMMENT 'User Id of the record created in the source system record',
	UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'Last updated timestamp of the source sytem record.',
	UPDATE_USER_ID VARCHAR(50) COMMENT 'User Id of the last updated in the source system record',
	SOURCE_EXTRACT_TS TIMESTAMP_LTZ(9) COMMENT 'Source Extract Create Timestamp',
	SOURCE_TYPE_CD VARCHAR(50) COMMENT 'Indicates if the AirMilePoints are SUMMARY or DETAIL payload.',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d',
	primary key (BATCH_ID, HOUSEHOLD_ID, TRANSACTION_ID, TRANSACTION_TS, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
