--liquibase formatted sql
--changeset SYSTEM:OCGP_PROGRAM_STORE_FLAT runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<EDM_DB_NAME_R>>;
USE SCHEMA DW_R_LOYALTY;

create or replace TABLE OCGP_PROGRAM_STORE_FLAT (
	RETAIL_STORE_ID VARCHAR(16777216),
	PROGRAM_CD VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	DW_CREATETS TIMESTAMP_TZ(9)
);

ALTER TABLE OCGP_PROGRAM_STORE_FLAT  SET CHANGE_TRACKING = TRUE;
