--liquibase formatted sql
--changeset SYSTEM:OCGP_PROGRAM_STORE runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_C_LOYALTY;

create or replace TABLE OCGP_PROGRAM_STORE (
	PROGRAM_CD VARCHAR(16777216) NOT NULL,
	RETAIL_STORE_ID VARCHAR(16777216) NOT NULL,
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL,
	DW_LAST_EFFECTIVE_DT DATE NOT NULL,
	DW_CREATE_TS TIMESTAMP_TZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_TZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	primary key (PROGRAM_CD, RETAIL_STORE_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
