USE DATABASE EDM_REFINED_PRD;
USE SCHEMA DW_APPL;

CREATE OR REPLACE stage EDDW_PETPROFILE_ADF_STAGE_PRDBLOB_INC
	url = 'azure://absitdsprodwusseddw001.blob.core.windows.net/itds-prod-direct-feeds'
	STORAGE_INTEGRATION = STORAGE_ABSITDSPRODWUSSEDDW001;
