--liquibase formatted sql
--changeset SYSTEM:SP_OFFERREQUEST_TO_BIM_LOAD_GETOFFERREQUEST_FLAT runOnChange:true splitStatements:false OBJECT_TYPE:SP
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PRODUCT;

CREATE OR REPLACE PROCEDURE <<EDM_DB_NAME>>.DW_C_PRODUCT.SP_OFFERREQUEST_TO_BIM_LOAD_GETOFFERREQUEST_FLAT(FLAT_STREAM VARCHAR, CNF_DB VARCHAR, DW_PRD_SCHEMA VARCHAR, WRK_SCHEMA VARCHAR)
RETURNS STRING
LANGUAGE JAVASCRIPT
AS
$$



    // **************        Load for GetOfferRequest_Flat table BEGIN *****************

  
    var cnf_db = CNF_DB;
    var cnf_schema = DW_PRD_SCHEMA;
    var wrk_schema = WRK_SCHEMA;
    var src_flat_strm =  FLAT_STREAM;	
    var Ref_db = "EDM_REFINED_PRD";
    var Ref_schema = "DW_R_PRODUCT";
    
    var src_flat_table=Ref_db + "." +Ref_schema+".GetOfferRequest_Flat" ;
    

    // identify  if the columns have changed between Target table and changed dataset and create a work table specific to the BIM table. 
    var tgt_wrk_tbl = cnf_db + "." + wrk_schema + ".GetOfferRequest_Flat_wrk";
    var tgt_tbl = cnf_db +"."+ cnf_schema +".GetOfferRequest_Flat";

	
		var wrk_tbl = `CREATE OR REPLACE TABLE `+ tgt_wrk_tbl +` AS
             SELECT  FILENAME
					,BODNm
					,DocumentID
				,ExternalTargetInd
				,InterchangeTime
				,InterchangeDate
				,InternalFileTransferInd
				,RoutingSystemNm
				,ReceiverId
				,GatewayNm
				,SenderId
				,TargetApplicationCd
				,SourceApplicationCd
				,Document_Description
				,CreationDt
				,DocumentNm
				,InboundOutboundInd
				,AlternateDocumentID
				,Note
				,PHIdataInd
				,PIIdataInd
				,PCIdataInd
				,BusinessSensitivityLevel_ShortDescription
				,BusinessSensitivityLevel_Description
				,BusinessSensitivityLevel_Code
				,DataClassificationLevel_ShortDescription
				,DataClassificationLevel_Description
				,DataClassificationLevel_Code
				,ActionTypeCd
				,RecordTypeCd
				,TriggerId
				,SavingsValueTxt
				,OfferRequestData_DisclaimerTxt
				,OfferRequestData_ImageId
				,OfferEffectiveDay
				,OfferRequestReferenceId
				,BusinessJustificationTxt
				,OfferRequestTypeCd
				,OfferItemDsc
				,OfferRequestCommentTxt
				,VersionQty
				,TierQty
				,ProductQty
				,StoreGroupQty
				,CustomerSegmentInfoTxt
				,DeletedOfferTxt
				,BrandInfoTxt
				,a.OfferRequestId
				,SizeDsc
				,DepartmentId
				,DepartmentNm
				,OfferNm
				,OfferRequestDsc
				,AdvertisementType_ShortDescription
				,AdvertisementType_Description
				,AdvertisementType_Code
				,AttachedOfferType_StoreGroupVersionId
				,AttachedOfferType_DisplayOrderNbr
				,AttachedOfferTypeId
				,AttachedOffer_DiscountId
				,AttachedOffer_DiscountVersionId
				,AttachedOffer_ProductGroupVersionId
				,AttachedOffer_StoreGroupVersionId
				,DistinctId
				,OfferId
				,a.ReferenceOfferId
				,AppliedInd
				,ProgramNm
				,Status_StatusTypeCd
				,case when Status_Description is null and upper(ActionTypeCd) = 'DELETE' then 'Deleted' else Status_Description end as Status_Description
				,Status_EffectiveDtTm
				,FrequencyDsc
				,InstantWinProgramId
				,PrizeItemQty
				,InstantWinVersionId
				,PODDetailType_DisclaimerTxt
				,PODDetailType_DisplayEndDt
				,PODDetailType_DisplayStartDt
				,HeadlineTxt
				,PriceInfoTxt
				,OfferDsc
				,CustomerFriendlyCategory_Description
				,CustomerFriendlyCategory_ShortDescription
				,CustomerFriendlyCategory_Code
				,DisplayImage_ImageId
				,ImageTypeCd
				,EventId
				,EventNm
				,DiscountVersion_DiscountVersionId
				,AirMileProgramNm
				,AirMileProgramId
				,AirMilePointQty
				,AirMileTierNm
				,Discount_DiscountId
				,ChargebackDepartmentNm
				,ChargebackDepartmentId
				,ExcludedProductGroupNm
				,ExcludedProductGroupId
				,IncludedProductgroupNm
				,IncludedProductGroupId
				,BenefitValueQty
				,BenefitValueType_Code
				,BenefitValueType_Description
				,BenefitValueType_ShortDescription
				,DiscountUptoQty
				,ReceiptTxt
				,RewardQty
				,DiscountAmt
				,TierLevelnbr
				,LimitType_LimitQty
				,LimitType_LimitWt
				,LimitType_LimitVol
				,LimitType_LimitAmt
				,LimitType_UOMCd
				,LimitType_UOMNm
				,DiscountType_ShortDescription
				,DiscountType_Description
				,DiscountType_Code
				,ProductGroup_DisplayOrderNbr
				,ItemQty
				,GiftCardInd
				,AnyProductInd
				,InheritedInd
				,ConjunctionDsc
				,MinimumPurchaseAmt
				,MaximumPurchaseAmt
				,UniqueItemInd
				,ProductGroup_ProductGroupNm
				,ProductGroupDsc
				,ProductGroup_ProductGroupId
				,ProductGroup_ProductGroupVersionId
				,ExcludedProductGroup_ProductGroupNm
				,ExcludedProductGroup_ProductGroupId
				,TierLevelAmt
				,TierLevelId
				,ProductGroup_UOMCd
				,ProductGroup_UOMNm
				,UOMDsc
				,ProtoType_Description
				,ProtoType_Code
				,ProtoType_ShortDescription
				,StoreGroupId
				,StoreGroupNm
				,StoreGroupDsc
				,StoreGroupType_Code
				,StoreGroupType_Description
				,StoreGroupType_ShortDescription
				,TagDsc
				,LoyaltyPgmTagInd
				,TagAmt
				,TagNbr
				,LinkURL
				,FileNm
				,IdNbr
				,ManufacturerType_Description
				,IdTxt
				,ManufacturerType_ShortDescription
				,DeliveryChannelTypeDsc
				,DeliveryChannelTypeCd
				,OfferEffectiveTm_TimeZoneCd
				,EndTm
				,StartTm
				,GroupCd
				,GroupNm
				,GroupId
				,SubGroupNm
				,SubGroupId
				,SubGroupCd
				,OfferPeriodType_DisplayStartDt
				,OfferPeriodType_DisplayEndDt
				,OfferStartDt
				,OfferEndDt
				,TestStartDt
				,TestEndDt
				,SourceSystemId
				,ApplicationId
				,UpdatedApplicationId
				,FirstNm
				,LastNm
				,UserTypeCd
				,a.UpdateTs
				,UserUpdate_TimeZoneCd
				,CreateTs
				,UserId
				,OfferRequestStatus_TimeZoneCd
				,OfferRequestStatus_EffectiveDtTm
				,OfferRequestStatus_Description
				,OfferRequestStatus_StatusTypeCd
				,OfferRequestStatusTypeCd
				,OfferRestrictionType_LimitWt
				,UsageLimitTypeTxt
				,OfferRestrictionType_LimitQty
				,OfferRestrictionType_LimitAmt
				,OfferRestrictionType_LimitVol
				,RestrictionType_Description
				,RestrictionType_Code
				,RestrictionType_ShortDescription
				,OfferRestrictionType_UOMNm
				,OfferRestrictionType_UOMCd
				,Name
				,PromotionProgramType_Code
				,NOPAEndDt
				,BilledInd
				,NOPAStartDt
				,VendorPromotionId
				,AllowanceType_ShortDescription
				,AllowanceType_Code
				,AllowanceType_Description
				,BillingOptionType_Description
				,BillingOptionType_ShortDescription
				,BillingOptionType_Code
				,NOPAAssignStatus_StatusTypeCd
				,NOPAAssignStatus_EffectiveDtTm
				,NOPAAssignStatus_Description
				,Document_ReleaseId
				,Document_VersionId
				,Document_SystemEnvironmentCd
				,OfferEffectiveDay_Qualifier
				,OfferRequestReferenceId_QualifierCd
				,Status_StatusTypeCd_Type
				,LinkURL_Qualifier
				,FileNm_Qualifier
				,OfferRequestStatus_StatusTypeCd_Type
				,NOPAAssignStatus_StatusTypeCd_Type
				,CURRENT_TIMESTAMP AS DW_CreateTs
				,USAGELIMITNBR
				,USAGELIMITPERIODNBR
   FROM (
              SELECT   ftab.FILENAME
						,ftab.BODNm
						,ftab.DocumentID
					,ftab.ExternalTargetInd
					,ftab.InterchangeTime
					,ftab.InterchangeDate
					,ftab.InternalFileTransferInd
					,ftab.RoutingSystemNm
					,ftab.ReceiverId
					,ftab.GatewayNm
					,ftab.SenderId
					,ftab.TargetApplicationCd
					,ftab.SourceApplicationCd
					,ftab.Document_Description
					,ftab.CreationDt
					,ftab.DocumentNm
					,ftab.InboundOutboundInd
					,ftab.AlternateDocumentID
					,ftab.Note
					,ftab.PHIdataInd
					,ftab.PIIdataInd
					,ftab.PCIdataInd
					,ftab.BusinessSensitivityLevel_ShortDescription
					,ftab.BusinessSensitivityLevel_Description
					,ftab.BusinessSensitivityLevel_Code
					,ftab.DataClassificationLevel_ShortDescription
					,ftab.DataClassificationLevel_Description
					,ftab.DataClassificationLevel_Code
					,ftab.ActionTypeCd
					,ftab.RecordTypeCd
					,ftab.TriggerId
					,ftab.SavingsValueTxt
					,ftab.OfferRequestData_DisclaimerTxt
					,ftab.OfferRequestData_ImageId
					,ftab.OfferEffectiveDay
					,ftab.OfferRequestReferenceId
					,ftab.BusinessJustificationTxt
					,ftab.OfferRequestTypeCd
					,ftab.OfferItemDsc
					,ftab.OfferRequestCommentTxt
					,ftab.VersionQty
					,ftab.TierQty
					,ftab.ProductQty
					,ftab.StoreGroupQty
					,ftab.CustomerSegmentInfoTxt
					,ftab.DeletedOfferTxt
					,ftab.BrandInfoTxt
					,ftab.OfferRequestId
					,ftab.SizeDsc
					,ftab.DepartmentId
					,ftab.DepartmentNm
					,ftab.OfferNm
					,ftab.OfferRequestDsc
					,ftab.AdvertisementType_ShortDescription
					,ftab.AdvertisementType_Description
					,ftab.AdvertisementType_Code
					,ftab.AttachedOfferType_StoreGroupVersionId
					,ftab.AttachedOfferType_DisplayOrderNbr
					,ftab.AttachedOfferTypeId
					,ftab.AttachedOffer_DiscountId
					,ftab.AttachedOffer_DiscountVersionId
					,ftab.AttachedOffer_ProductGroupVersionId
					,ftab.AttachedOffer_StoreGroupVersionId
					,ftab.DistinctId
					,ftab.OfferId
					,ftab.ReferenceOfferId
					,ftab.AppliedInd
					,ftab.ProgramNm
					,ftab.Status_StatusTypeCd
					,ftab.Status_Description
					,ftab.Status_EffectiveDtTm
					,ftab.FrequencyDsc
					,ftab.InstantWinProgramId
					,ftab.PrizeItemQty
					,ftab.InstantWinVersionId
					,ftab.PODDetailType_DisclaimerTxt
					,ftab.PODDetailType_DisplayEndDt
					,ftab.PODDetailType_DisplayStartDt
					,ftab.HeadlineTxt
					,ftab.PriceInfoTxt
					,ftab.OfferDsc
					,ftab.CustomerFriendlyCategory_Description
					,ftab.CustomerFriendlyCategory_ShortDescription
					,ftab.CustomerFriendlyCategory_Code
					,ftab.DisplayImage_ImageId
					,ftab.ImageTypeCd
					,ftab.EventId
					,ftab.EventNm
					,ftab.DiscountVersion_DiscountVersionId
					,ftab.AirMileProgramNm
					,ftab.AirMileProgramId
					,ftab.AirMilePointQty
					,ftab.AirMileTierNm
					,ftab.Discount_DiscountId
					,ftab.ChargebackDepartmentNm
					,ftab.ChargebackDepartmentId
					,ftab.ExcludedProductGroupNm
					,ftab.ExcludedProductGroupId
					,ftab.IncludedProductgroupNm
					,ftab.IncludedProductGroupId
					,ftab.BenefitValueQty
					,ftab.BenefitValueType_Code
					,ftab.BenefitValueType_Description
					,ftab.BenefitValueType_ShortDescription
					,ftab.DiscountUptoQty
					,ftab.ReceiptTxt
					,ftab.RewardQty
					,ftab.DiscountAmt
					,ftab.TierLevelnbr
					,ftab.LimitType_LimitQty
					,ftab.LimitType_LimitWt
					,ftab.LimitType_LimitVol
					,ftab.LimitType_LimitAmt
					,ftab.LimitType_UOMCd
					,ftab.LimitType_UOMNm
					,ftab.DiscountType_ShortDescription
					,ftab.DiscountType_Description
					,ftab.DiscountType_Code
					,ftab.ProductGroup_DisplayOrderNbr
					,ftab.ItemQty
					,ftab.GiftCardInd
					,ftab.AnyProductInd
					,ftab.InheritedInd
					,ftab.ConjunctionDsc
					,ftab.MinimumPurchaseAmt
					,ftab.MaximumPurchaseAmt
					,ftab.UniqueItemInd
					,ftab.ProductGroup_ProductGroupNm
					,ftab.ProductGroupDsc
					,ftab.ProductGroup_ProductGroupId
					,ftab.ProductGroup_ProductGroupVersionId
					,ftab.ExcludedProductGroup_ProductGroupNm
					,ftab.ExcludedProductGroup_ProductGroupId
					,ftab.TierLevelAmt
					,ftab.TierLevelId
					,ftab.ProductGroup_UOMCd
					,ftab.ProductGroup_UOMNm
					,ftab.UOMDsc
					,ftab.ProtoType_Description
					,ftab.ProtoType_Code
					,ftab.ProtoType_ShortDescription
					,ftab.StoreGroupId
					,ftab.StoreGroupNm
					,ftab.StoreGroupDsc
					,ftab.StoreGroupType_Code
					,ftab.StoreGroupType_Description
					,ftab.StoreGroupType_ShortDescription
					,ftab.TagDsc
					,ftab.LoyaltyPgmTagInd
					,ftab.TagAmt
					,ftab.TagNbr
					,ftab.LinkURL
					,ftab.FileNm
					,ftab.IdNbr
					,ftab.ManufacturerType_Description
					,ftab.IdTxt
					,ftab.ManufacturerType_ShortDescription
					,ftab.DeliveryChannelTypeDsc
					,ftab.DeliveryChannelTypeCd
					,ftab.OfferEffectiveTm_TimeZoneCd
					,ftab.EndTm
					,ftab.StartTm
					,ftab.GroupCd
					,ftab.GroupNm
					,ftab.GroupId
					,ftab.SubGroupNm
					,ftab.SubGroupId
					,ftab.SubGroupCd
					,ftab.OfferPeriodType_DisplayStartDt
					,ftab.OfferPeriodType_DisplayEndDt
					,ftab.OfferStartDt
					,ftab.OfferEndDt
					,ftab.TestStartDt
					,ftab.TestEndDt
					,ftab.SourceSystemId
					,ftab.ApplicationId
					,ftab.UpdatedApplicationId
					,ftab.FirstNm
					,ftab.LastNm
					,ftab.UserTypeCd
					,ftab.UpdateTs
					,nvl(ftab.UpdateTs,ftab.dw_createts) as Updatets_creationdt
					,ftab.UserUpdate_TimeZoneCd
					,ftab.CreateTs
					,ftab.UserId
					,ftab.OfferRequestStatus_TimeZoneCd
					,ftab.OfferRequestStatus_EffectiveDtTm
					,ftab.OfferRequestStatus_Description
					,ftab.OfferRequestStatus_StatusTypeCd
					,ftab.OfferRequestStatusTypeCd
					,ftab.OfferRestrictionType_LimitWt
					,ftab.UsageLimitTypeTxt
					,ftab.OfferRestrictionType_LimitQty
					,ftab.OfferRestrictionType_LimitAmt
					,ftab.OfferRestrictionType_LimitVol
					,ftab.RestrictionType_Description
					,ftab.RestrictionType_Code
					,ftab.RestrictionType_ShortDescription
					,ftab.OfferRestrictionType_UOMNm
					,ftab.OfferRestrictionType_UOMCd
					,ftab.Name
					,ftab.PromotionProgramType_Code
					,ftab.NOPAEndDt
					,ftab.BilledInd
					,ftab.NOPAStartDt
					,ftab.VendorPromotionId
					,ftab.AllowanceType_ShortDescription
					,ftab.AllowanceType_Code
					,ftab.AllowanceType_Description
					,ftab.BillingOptionType_Description
					,ftab.BillingOptionType_ShortDescription
					,ftab.BillingOptionType_Code
					,ftab.NOPAAssignStatus_StatusTypeCd
					,ftab.NOPAAssignStatus_EffectiveDtTm
					,ftab.NOPAAssignStatus_Description
					,ftab.Document_ReleaseId
					,ftab.Document_VersionId
					,ftab.Document_SystemEnvironmentCd
					,ftab.OfferEffectiveDay_Qualifier
					,ftab.OfferRequestReferenceId_QualifierCd
					,ftab.Status_StatusTypeCd_Type
					,ftab.LinkURL_Qualifier
					,ftab.FileNm_Qualifier
					,ftab.OfferRequestStatus_StatusTypeCd_Type
					,ftab.NOPAAssignStatus_StatusTypeCd_Type
					,CURRENT_TIMESTAMP AS DW_CreateTs
					,ftab.USAGELIMITNBR
					,ftab.USAGELIMITPERIODNBR
                            ,row_number() over(PARTITION BY ftab.FILENAME
						,ftab.BODNm
						,ftab.DocumentID
					,ftab.ExternalTargetInd
					,ftab.InterchangeTime
					,ftab.InterchangeDate
					,ftab.InternalFileTransferInd
					,ftab.RoutingSystemNm
					,ftab.ReceiverId
					,ftab.GatewayNm
					,ftab.SenderId
					,ftab.TargetApplicationCd
					,ftab.SourceApplicationCd
					,ftab.Document_Description
					,ftab.CreationDt
					,ftab.DocumentNm
					,ftab.InboundOutboundInd
					,ftab.AlternateDocumentID
					,ftab.Note
					,ftab.PHIdataInd
					,ftab.PIIdataInd
					,ftab.PCIdataInd
					,ftab.BusinessSensitivityLevel_ShortDescription
					,ftab.BusinessSensitivityLevel_Description
					,ftab.BusinessSensitivityLevel_Code
					,ftab.DataClassificationLevel_ShortDescription
					,ftab.DataClassificationLevel_Description
					,ftab.DataClassificationLevel_Code
					,ftab.ActionTypeCd
					,ftab.RecordTypeCd
					,ftab.TriggerId
					,ftab.SavingsValueTxt
					,ftab.OfferRequestData_DisclaimerTxt
					,ftab.OfferRequestData_ImageId
					,ftab.OfferEffectiveDay
					,ftab.OfferRequestReferenceId
					,ftab.BusinessJustificationTxt
					,ftab.OfferRequestTypeCd
					,ftab.OfferItemDsc
					,ftab.OfferRequestCommentTxt
					,ftab.VersionQty
					,ftab.TierQty
					,ftab.ProductQty
					,ftab.StoreGroupQty
					,ftab.CustomerSegmentInfoTxt
					,ftab.DeletedOfferTxt
					,ftab.BrandInfoTxt
					,ftab.OfferRequestId
					,ftab.SizeDsc
					,ftab.DepartmentId
					,ftab.DepartmentNm
					,ftab.OfferNm
					,ftab.OfferRequestDsc
					,ftab.AdvertisementType_ShortDescription
					,ftab.AdvertisementType_Description
					,ftab.AdvertisementType_Code
					,ftab.AttachedOfferType_StoreGroupVersionId
					,ftab.AttachedOfferType_DisplayOrderNbr
					,ftab.AttachedOfferTypeId
					,ftab.AttachedOffer_DiscountId
					,ftab.AttachedOffer_DiscountVersionId
					,ftab.AttachedOffer_ProductGroupVersionId
					,ftab.AttachedOffer_StoreGroupVersionId
					,ftab.DistinctId
					,ftab.OfferId
					,ftab.ReferenceOfferId
					,ftab.AppliedInd
					,ftab.ProgramNm
					,ftab.Status_StatusTypeCd
					,ftab.Status_Description
					,ftab.Status_EffectiveDtTm
					,ftab.FrequencyDsc
					,ftab.InstantWinProgramId
					,ftab.PrizeItemQty
					,ftab.InstantWinVersionId
					,ftab.PODDetailType_DisclaimerTxt
					,ftab.PODDetailType_DisplayEndDt
					,ftab.PODDetailType_DisplayStartDt
					,ftab.HeadlineTxt
					,ftab.PriceInfoTxt
					,ftab.OfferDsc
					,ftab.CustomerFriendlyCategory_Description
					,ftab.CustomerFriendlyCategory_ShortDescription
					,ftab.CustomerFriendlyCategory_Code
					,ftab.DisplayImage_ImageId
					,ftab.ImageTypeCd
					,ftab.EventId
					,ftab.EventNm
					,ftab.DiscountVersion_DiscountVersionId
					,ftab.AirMileProgramNm
					,ftab.AirMileProgramId
					,ftab.AirMilePointQty
					,ftab.AirMileTierNm
					,ftab.Discount_DiscountId
					,ftab.ChargebackDepartmentNm
					,ftab.ChargebackDepartmentId
					,ftab.ExcludedProductGroupNm
					,ftab.ExcludedProductGroupId
					,ftab.IncludedProductgroupNm
					,ftab.IncludedProductGroupId
					,ftab.BenefitValueQty
					,ftab.BenefitValueType_Code
					,ftab.BenefitValueType_Description
					,ftab.BenefitValueType_ShortDescription
					,ftab.DiscountUptoQty
					,ftab.ReceiptTxt
					,ftab.RewardQty
					,ftab.DiscountAmt
					,ftab.TierLevelnbr
					,ftab.LimitType_LimitQty
					,ftab.LimitType_LimitWt
					,ftab.LimitType_LimitVol
					,ftab.LimitType_LimitAmt
					,ftab.LimitType_UOMCd
					,ftab.LimitType_UOMNm
					,ftab.DiscountType_ShortDescription
					,ftab.DiscountType_Description
					,ftab.DiscountType_Code
					,ftab.ProductGroup_DisplayOrderNbr
					,ftab.ItemQty
					,ftab.GiftCardInd
					,ftab.AnyProductInd
					,ftab.InheritedInd
					,ftab.ConjunctionDsc
					,ftab.MinimumPurchaseAmt
					,ftab.MaximumPurchaseAmt
					,ftab.UniqueItemInd
					,ftab.ProductGroup_ProductGroupNm
					,ftab.ProductGroupDsc
					,ftab.ProductGroup_ProductGroupId
					,ftab.ProductGroup_ProductGroupVersionId
					,ftab.ExcludedProductGroup_ProductGroupNm
					,ftab.ExcludedProductGroup_ProductGroupId
					,ftab.TierLevelAmt
					,ftab.TierLevelId
					,ftab.ProductGroup_UOMCd
					,ftab.ProductGroup_UOMNm
					,ftab.UOMDsc
					,ftab.ProtoType_Description
					,ftab.ProtoType_Code
					,ftab.ProtoType_ShortDescription
					,ftab.StoreGroupId
					,ftab.StoreGroupNm
					,ftab.StoreGroupDsc
					,ftab.StoreGroupType_Code
					,ftab.StoreGroupType_Description
					,ftab.StoreGroupType_ShortDescription
					,ftab.TagDsc
					,ftab.LoyaltyPgmTagInd
					,ftab.TagAmt
					,ftab.TagNbr
					,ftab.LinkURL
					,ftab.FileNm
					,ftab.IdNbr
					,ftab.ManufacturerType_Description
					,ftab.IdTxt
					,ftab.ManufacturerType_ShortDescription
					,ftab.DeliveryChannelTypeDsc
					,ftab.DeliveryChannelTypeCd
					,ftab.OfferEffectiveTm_TimeZoneCd
					,ftab.EndTm
					,ftab.StartTm
					,ftab.GroupCd
					,ftab.GroupNm
					,ftab.GroupId
					,ftab.SubGroupNm
					,ftab.SubGroupId
					,ftab.SubGroupCd
					,ftab.OfferPeriodType_DisplayStartDt
					,ftab.OfferPeriodType_DisplayEndDt
					,ftab.OfferStartDt
					,ftab.OfferEndDt
					,ftab.TestStartDt
					,ftab.TestEndDt
					,ftab.SourceSystemId
					,ftab.ApplicationId
					,ftab.UpdatedApplicationId
					,ftab.FirstNm
					,ftab.LastNm
					,ftab.UserTypeCd
					,ftab.UserUpdate_TimeZoneCd
					,ftab.CreateTs
					,ftab.UserId
					,ftab.OfferRequestStatus_TimeZoneCd
					,ftab.OfferRequestStatus_EffectiveDtTm
					,ftab.OfferRequestStatus_Description
					,ftab.OfferRequestStatus_StatusTypeCd
					,ftab.OfferRequestStatusTypeCd
					,ftab.OfferRestrictionType_LimitWt
					,ftab.UsageLimitTypeTxt
					,ftab.OfferRestrictionType_LimitQty
					,ftab.OfferRestrictionType_LimitAmt
					,ftab.OfferRestrictionType_LimitVol
					,ftab.RestrictionType_Description
					,ftab.RestrictionType_Code
					,ftab.RestrictionType_ShortDescription
					,ftab.OfferRestrictionType_UOMNm
					,ftab.OfferRestrictionType_UOMCd
					,ftab.Name
					,ftab.PromotionProgramType_Code
					,ftab.NOPAEndDt
					,ftab.BilledInd
					,ftab.NOPAStartDt
					,ftab.VendorPromotionId
					,ftab.AllowanceType_ShortDescription
					,ftab.AllowanceType_Code
					,ftab.AllowanceType_Description
					,ftab.BillingOptionType_Description
					,ftab.BillingOptionType_ShortDescription
					,ftab.BillingOptionType_Code
					,ftab.NOPAAssignStatus_StatusTypeCd
					,ftab.NOPAAssignStatus_EffectiveDtTm
					,ftab.NOPAAssignStatus_Description
					,ftab.Document_ReleaseId
					,ftab.Document_VersionId
					,ftab.Document_SystemEnvironmentCd
					,ftab.OfferEffectiveDay_Qualifier
					,ftab.OfferRequestReferenceId_QualifierCd
					,ftab.Status_StatusTypeCd_Type
					,ftab.LinkURL_Qualifier
					,ftab.FileNm_Qualifier
					,ftab.OfferRequestStatus_StatusTypeCd_Type
					,ftab.NOPAAssignStatus_StatusTypeCd_Type  
					,ftab.USAGELIMITNBR
					,ftab.USAGELIMITPERIODNBR		ORDER BY to_timestamp_ntz(nvl(ftab.UpdateTs,ftab.dw_createts)) desc
					) as rn
			  
			              FROM ` + src_flat_table  +` ftab where OfferRequestId in (
                          select OfferRequestId from ` + src_flat_strm +` str )
                                       and   ftab.OfferRequestId is not null) a                                                                                                                                                
                   JOIN                                                                                                                                                                                      
                    (select                                                                                                                                                                                   
						ftab.OfferRequestId                                                                                                                                                                                                                                                                                                                                                                                                                              
						,max(nvl(ftab.updatets,ftab.dw_createts)) as updatets                                                                                                                                                                                                                                                                                                                                                                                                                              
						from  ` + src_flat_table  +` ftab 
                        where OfferRequestId in (
                          select OfferRequestId from ` + src_flat_strm +` str )
                                       and   ftab.OfferRequestId is not null
						group by ftab.OfferRequestId                                                                                                                                                                                                                                                                                                                                                                                                                              
						                                                                                                                                                                                                                                                                                                                                                                                                                              
		    		) b                    
                      
					ON a.OfferRequestId = b.OfferRequestId
					// AND a.ReferenceOfferId = b.ReferenceOfferId
					AND a.Updatets_creationdt = b.updatets 
					where rn = 1 
					order by OfferRequestId,AttachedOfferType_DisplayOrderNbr,BenefitValueType_Description`;
                       

		    try {
        snowflake.execute ( 
            {sqlText: wrk_tbl  }
        );
    }
    catch (err)  { 
    return "Creation of OfferRequest_Flat tgt_wrk_tbl table  Failed with error: " + err;   // Return a error message.
    }
    
   
	var delete_duplicate = `DELETE FROM ` + tgt_tbl + ` WHERE OfferRequestId IN (SELECT OfferRequestId FROM `+ tgt_wrk_tbl +`)`;
                      
							
	var sql_begin = "BEGIN"
    // Processing Inserts
    var sql_inserts = `insert INTO ` + tgt_tbl + `
	                     (FILENAME
						,BODNm
						,DocumentID
						,ExternalTargetInd
						,InterchangeTime
						,InterchangeDate
						,InternalFileTransferInd
						,RoutingSystemNm
						,ReceiverId
						,GatewayNm
						,SenderId
						,TargetApplicationCd
						,SourceApplicationCd
						,Document_Description
						,CreationDt
						,DocumentNm
						,InboundOutboundInd
						,AlternateDocumentID
						,Note
						,PHIdataInd
						,PIIdataInd
						,PCIdataInd
						,BusinessSensitivityLevel_ShortDescription
						,BusinessSensitivityLevel_Description
						,BusinessSensitivityLevel_Code
						,DataClassificationLevel_ShortDescription
						,DataClassificationLevel_Description
						,DataClassificationLevel_Code
						,ActionTypeCd
						,RecordTypeCd
						,TriggerId
						,SavingsValueTxt
						,OfferRequestData_DisclaimerTxt
						,OfferRequestData_ImageId
						,OfferEffectiveDay
						,OfferRequestReferenceId
						,BusinessJustificationTxt
						,OfferRequestTypeCd
						,OfferItemDsc
						,OfferRequestCommentTxt
						,VersionQty
						,TierQty
						,ProductQty
						,StoreGroupQty
						,CustomerSegmentInfoTxt
						,DeletedOfferTxt
						,BrandInfoTxt
						,OfferRequestId
						,SizeDsc
						,DepartmentId
						,DepartmentNm
						,OfferNm
						,OfferRequestDsc
						,AdvertisementType_ShortDescription
						,AdvertisementType_Description
						,AdvertisementType_Code
						,AttachedOfferType_StoreGroupVersionId
						,AttachedOfferType_DisplayOrderNbr
						,AttachedOfferTypeId
						,AttachedOffer_DiscountId
						,AttachedOffer_DiscountVersionId
						,AttachedOffer_ProductGroupVersionId
						,AttachedOffer_StoreGroupVersionId
						,DistinctId
						,OfferId
						,ReferenceOfferId
						,AppliedInd
						,ProgramNm
						,Status_StatusTypeCd
						,Status_Description
						,Status_EffectiveDtTm
						,FrequencyDsc
						,InstantWinProgramId
						,PrizeItemQty
						,InstantWinVersionId
						,PODDetailType_DisclaimerTxt
						,PODDetailType_DisplayEndDt
						,PODDetailType_DisplayStartDt
						,HeadlineTxt
						,PriceInfoTxt
						,OfferDsc
						,CustomerFriendlyCategory_Description
						,CustomerFriendlyCategory_ShortDescription
						,CustomerFriendlyCategory_Code
						,DisplayImage_ImageId
						,ImageTypeCd
						,EventId
						,EventNm
						,DiscountVersion_DiscountVersionId
						,AirMileProgramNm
						,AirMileProgramId
						,AirMilePointQty
						,AirMileTierNm
						,Discount_DiscountId
						,ChargebackDepartmentNm
						,ChargebackDepartmentId
						,ExcludedProductGroupNm
						,ExcludedProductGroupId
						,IncludedProductgroupNm
						,IncludedProductGroupId
						,BenefitValueQty
						,BenefitValueType_Code
						,BenefitValueType_Description
						,BenefitValueType_ShortDescription
						,DiscountUptoQty
						,ReceiptTxt
						,RewardQty
						,DiscountAmt
						,TierLevelnbr
						,LimitType_LimitQty
						,LimitType_LimitWt
						,LimitType_LimitVol
						,LimitType_LimitAmt
						,LimitType_UOMCd
						,LimitType_UOMNm
						,DiscountType_ShortDescription
						,DiscountType_Description
						,DiscountType_Code
						,ProductGroup_DisplayOrderNbr
						,ItemQty
						,GiftCardInd
						,AnyProductInd
						,InheritedInd
						,ConjunctionDsc
						,MinimumPurchaseAmt
						,MaximumPurchaseAmt
						,UniqueItemInd
						,ProductGroup_ProductGroupNm
						,ProductGroupDsc
						,ProductGroup_ProductGroupId
						,ProductGroup_ProductGroupVersionId
						,ExcludedProductGroup_ProductGroupNm
						,ExcludedProductGroup_ProductGroupId
						,TierLevelAmt
						,TierLevelId
						,ProductGroup_UOMCd
						,ProductGroup_UOMNm
						,UOMDsc
						,ProtoType_Description
						,ProtoType_Code
						,ProtoType_ShortDescription
						,StoreGroupId
						,StoreGroupNm
						,StoreGroupDsc
						,StoreGroupType_Code
						,StoreGroupType_Description
						,StoreGroupType_ShortDescription
						,TagDsc
						,LoyaltyPgmTagInd
						,TagAmt
						,TagNbr
						,LinkURL
						,FileNm
						,IdNbr
						,ManufacturerType_Description
						,IdTxt
						,ManufacturerType_ShortDescription
						,DeliveryChannelTypeDsc
						,DeliveryChannelTypeCd
						,OfferEffectiveTm_TimeZoneCd
						,EndTm
						,StartTm
						,GroupCd
						,GroupNm
						,GroupId
						,SubGroupNm
						,SubGroupId
						,SubGroupCd
						,OfferPeriodType_DisplayStartDt
						,OfferPeriodType_DisplayEndDt
						,OfferStartDt
						,OfferEndDt
						,TestStartDt
						,TestEndDt
						,SourceSystemId
						,ApplicationId
						,UpdatedApplicationId
						,FirstNm
						,LastNm
						,UserTypeCd
						,UpdateTs
						,UserUpdate_TimeZoneCd
						,CreateTs
						,UserId
						,OfferRequestStatus_TimeZoneCd
						,OfferRequestStatus_EffectiveDtTm
						,OfferRequestStatus_Description
						,OfferRequestStatus_StatusTypeCd
						,OfferRequestStatusTypeCd
						,OfferRestrictionType_LimitWt
						,UsageLimitTypeTxt
						,OfferRestrictionType_LimitQty
						,OfferRestrictionType_LimitAmt
						,OfferRestrictionType_LimitVol
						,RestrictionType_Description
						,RestrictionType_Code
						,RestrictionType_ShortDescription
						,OfferRestrictionType_UOMNm
						,OfferRestrictionType_UOMCd
						,Name
						,PromotionProgramType_Code
						,NOPAEndDt
						,BilledInd
						,NOPAStartDt
						,VendorPromotionId
						,AllowanceType_ShortDescription
						,AllowanceType_Code
						,AllowanceType_Description
						,BillingOptionType_Description
						,BillingOptionType_ShortDescription
						,BillingOptionType_Code
						,NOPAAssignStatus_StatusTypeCd
						,NOPAAssignStatus_EffectiveDtTm
						,NOPAAssignStatus_Description
						,Document_ReleaseId
						,Document_VersionId
						,Document_SystemEnvironmentCd
						,OfferEffectiveDay_Qualifier
						,OfferRequestReferenceId_QualifierCd
						,Status_StatusTypeCd_Type
						,LinkURL_Qualifier
						,FileNm_Qualifier
						,OfferRequestStatus_StatusTypeCd_Type
						,NOPAAssignStatus_StatusTypeCd_Type
						,DW_CreateTs
						,USAGELIMITNBR
						,USAGELIMITPERIODNBR)
				Select 
                            FILENAME
						,BODNm
						,DocumentID
						,ExternalTargetInd
						,InterchangeTime
						,InterchangeDate
						,InternalFileTransferInd
						,RoutingSystemNm
						,ReceiverId
						,GatewayNm
						,SenderId
						,TargetApplicationCd
						,SourceApplicationCd
						,Document_Description
						,CreationDt
						,DocumentNm
						,InboundOutboundInd
						,AlternateDocumentID
						,Note
						,PHIdataInd
						,PIIdataInd
						,PCIdataInd
						,BusinessSensitivityLevel_ShortDescription
						,BusinessSensitivityLevel_Description
						,BusinessSensitivityLevel_Code
						,DataClassificationLevel_ShortDescription
						,DataClassificationLevel_Description
						,DataClassificationLevel_Code
						,ActionTypeCd
						,RecordTypeCd
						,TriggerId
						,SavingsValueTxt
						,OfferRequestData_DisclaimerTxt
						,OfferRequestData_ImageId
						,OfferEffectiveDay
						,OfferRequestReferenceId
						,BusinessJustificationTxt
						,OfferRequestTypeCd
						,OfferItemDsc
						,OfferRequestCommentTxt
						,VersionQty
						,TierQty
						,ProductQty
						,StoreGroupQty
						,CustomerSegmentInfoTxt
						,DeletedOfferTxt
						,BrandInfoTxt
						,OfferRequestId
						,SizeDsc
						,DepartmentId
						,DepartmentNm
						,OfferNm
						,OfferRequestDsc
						,AdvertisementType_ShortDescription
						,AdvertisementType_Description
						,AdvertisementType_Code
						,AttachedOfferType_StoreGroupVersionId
						,AttachedOfferType_DisplayOrderNbr
						,AttachedOfferTypeId
						,AttachedOffer_DiscountId
						,AttachedOffer_DiscountVersionId
						,AttachedOffer_ProductGroupVersionId
						,AttachedOffer_StoreGroupVersionId
						,DistinctId
						,OfferId
						,ReferenceOfferId
						,AppliedInd
						,ProgramNm
						,Status_StatusTypeCd
						,Status_Description
						,Status_EffectiveDtTm
						,FrequencyDsc
						,InstantWinProgramId
						,PrizeItemQty
						,InstantWinVersionId
						,PODDetailType_DisclaimerTxt
						,PODDetailType_DisplayEndDt
						,PODDetailType_DisplayStartDt
						,HeadlineTxt
						,PriceInfoTxt
						,OfferDsc
						,CustomerFriendlyCategory_Description
						,CustomerFriendlyCategory_ShortDescription
						,CustomerFriendlyCategory_Code
						,DisplayImage_ImageId
						,ImageTypeCd
						,EventId
						,EventNm
						,DiscountVersion_DiscountVersionId
						,AirMileProgramNm
						,AirMileProgramId
						,AirMilePointQty
						,AirMileTierNm
						,Discount_DiscountId
						,ChargebackDepartmentNm
						,ChargebackDepartmentId
						,ExcludedProductGroupNm
						,ExcludedProductGroupId
						,IncludedProductgroupNm
						,IncludedProductGroupId
						,BenefitValueQty
						,BenefitValueType_Code
						,BenefitValueType_Description
						,BenefitValueType_ShortDescription
						,DiscountUptoQty
						,ReceiptTxt
						,RewardQty
						,DiscountAmt
						,TierLevelnbr
						,LimitType_LimitQty
						,LimitType_LimitWt
						,LimitType_LimitVol
						,LimitType_LimitAmt
						,LimitType_UOMCd
						,LimitType_UOMNm
						,DiscountType_ShortDescription
						,DiscountType_Description
						,DiscountType_Code
						,ProductGroup_DisplayOrderNbr
						,ItemQty
						,GiftCardInd
						,AnyProductInd
						,InheritedInd
						,ConjunctionDsc
						,MinimumPurchaseAmt
						,MaximumPurchaseAmt
						,UniqueItemInd
						,ProductGroup_ProductGroupNm
						,ProductGroupDsc
						,ProductGroup_ProductGroupId
						,ProductGroup_ProductGroupVersionId
						,ExcludedProductGroup_ProductGroupNm
						,ExcludedProductGroup_ProductGroupId
						,TierLevelAmt
						,TierLevelId
						,ProductGroup_UOMCd
						,ProductGroup_UOMNm
						,UOMDsc
						,ProtoType_Description
						,ProtoType_Code
						,ProtoType_ShortDescription
						,StoreGroupId
						,StoreGroupNm
						,StoreGroupDsc
						,StoreGroupType_Code
						,StoreGroupType_Description
						,StoreGroupType_ShortDescription
						,TagDsc
						,LoyaltyPgmTagInd
						,TagAmt
						,TagNbr
						,LinkURL
						,FileNm
						,IdNbr
						,ManufacturerType_Description
						,IdTxt
						,ManufacturerType_ShortDescription
						,DeliveryChannelTypeDsc
						,DeliveryChannelTypeCd
						,OfferEffectiveTm_TimeZoneCd
						,EndTm
						,StartTm
						,GroupCd
						,GroupNm
						,GroupId
						,SubGroupNm
						,SubGroupId
						,SubGroupCd
						,OfferPeriodType_DisplayStartDt
						,OfferPeriodType_DisplayEndDt
						,OfferStartDt
						,OfferEndDt
						,TestStartDt
						,TestEndDt
						,SourceSystemId
						,ApplicationId
						,UpdatedApplicationId
						,FirstNm
						,LastNm
						,UserTypeCd
						,UpdateTs
						,UserUpdate_TimeZoneCd
						,CreateTs
						,UserId
						,OfferRequestStatus_TimeZoneCd
						,OfferRequestStatus_EffectiveDtTm
						,OfferRequestStatus_Description
						,OfferRequestStatus_StatusTypeCd
						,OfferRequestStatusTypeCd
						,OfferRestrictionType_LimitWt
						,UsageLimitTypeTxt
						,OfferRestrictionType_LimitQty
						,OfferRestrictionType_LimitAmt
						,OfferRestrictionType_LimitVol
						,RestrictionType_Description
						,RestrictionType_Code
						,RestrictionType_ShortDescription
						,OfferRestrictionType_UOMNm
						,OfferRestrictionType_UOMCd
						,Name
						,PromotionProgramType_Code
						,NOPAEndDt
						,BilledInd
						,NOPAStartDt
						,VendorPromotionId
						,AllowanceType_ShortDescription
						,AllowanceType_Code
						,AllowanceType_Description
						,BillingOptionType_Description
						,BillingOptionType_ShortDescription
						,BillingOptionType_Code
						,NOPAAssignStatus_StatusTypeCd
						,NOPAAssignStatus_EffectiveDtTm
						,NOPAAssignStatus_Description
						,Document_ReleaseId
						,Document_VersionId
						,Document_SystemEnvironmentCd
						,OfferEffectiveDay_Qualifier
						,OfferRequestReferenceId_QualifierCd
						,Status_StatusTypeCd_Type
						,LinkURL_Qualifier
						,FileNm_Qualifier
						,OfferRequestStatus_StatusTypeCd_Type
						,NOPAAssignStatus_StatusTypeCd_Type
						,DW_CreateTs
						,USAGELIMITNBR
						,USAGELIMITPERIODNBR
							from `+ tgt_wrk_tbl +` 
						order by OfferRequestId,AttachedOfferType_DisplayOrderNbr,BenefitValueType_Description`;
                      
	var sql_commit = "COMMIT"
    var sql_rollback = "ROLLBACK"
    try {
       snowflake.execute (
            {sqlText: sql_begin}
        );
        snowflake.execute(
			{sqlText: delete_duplicate}
			);              
        snowflake.execute (
            {sqlText: sql_inserts}
        );
        snowflake.execute (
            {sqlText: sql_commit}
        );    
    }
    catch (err) {
        snowflake.execute (
            {sqlText: sql_rollback}
        );
         return "Loading of "  + tgt_tbl + " Failed with error: " + err;   // Return a error message.
    }
            // **************        Load for OfferRequest_Flat  ENDs *****************
 return "Done"


$$;
