--liquibase formatted sql
--changeset SYSTEM:ONETAG_CLICK_STREAM_OPERATING_SYSTEM_DETAIL_WRK runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_STAGE;

DELETE FROM EDM_REFINED_<<ENV>>.DW_R_STAGE.ONETAG_OTHER_FLAT_WRK;
DELETE FROM EDM_REFINED_<<ENV>>.DW_R_STAGE.ONETAG_OTHER_FLAT_RERUN;
