--liquibase formatted sql
--changeset SYSTEM:ONE_TAG_CLICK_STREAM_VISIT runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_STAGE;

CREATE OR REPLACE TRANSIENT TABLE ONE_TAG_CLICK_STREAM_VISIT_WRK (
	EVENT_ID VARCHAR(16777216),
	SESSION_ID VARCHAR(16777216),
	VISIT_ID VARCHAR(16777216),
	VISIT_PAGE_NBR VARCHAR(16777216),
	EVENT_TS TIMESTAMP_LTZ(9),
	ADOBE_CREATE_TS TIMESTAMP_LTZ(9)
	);