--liquibase formatted sql
--changeset SYSTEM:CUSTOMER_SESSION_PAGE_WRK runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_STAGE;

create or replace TRANSIENT TABLE CUSTOMER_SESSION_PAGE_WRK (
	PAGE_NM VARCHAR NULL,
	PAGE_TYPE_CD VARCHAR NULL,
	PAGE_SUBSECTION1_DSC VARCHAR NULL,
	PAGE_SUBSECTION2_DSC VARCHAR NULL,
	PAGE_SUBSECTION3_DSC VARCHAR NULL,
	PAGE_SUBSECTION4_DSC VARCHAR NULL,
	DW_CREATE_TS TIMESTAMP NULL,
	DW_LAST_UPDATE_TS TIMESTAMP NULL,
	DW_LOGICAL_DELETE_IND BOOLEAN NULL,
	DW_SOURCE_CREATE_NM VARCHAR(255) NULL,
	DW_SOURCE_UPDATE_NM VARCHAR(255) NULL,
	DW_CURRENT_VERSION_IND BOOLEAN NULL 
);
