--liquibase formatted sql
--changeset SYSTEM:SP_ONETAG_ADOBE_VISIT_LOAD_MAIN_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_ANALYTICS_<<ENV>>;
use schema DW_APPL;

CREATE OR REPLACE TASK SP_ONETAG_ADOBE_VISIT_LOAD_MAIN_TASK
WAREHOUSE = <<parm_EDM_WH_NAME>>
QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_ONETAG_ADOBE_VISIT_LOAD_MAIN_TASK", "APPCODE":"OCAT", "APPID":"OCAT", "SUBJECTAREA":"OneTag", "BOD":"OneTag", "PROCESS":"C_PIPELINE_INC_LOAD", "COMMENT":"Task Tag"}'
--AFTER EDM_ANALYTICS_<<ENV>>.DW_APPL.SP_ONETAG_PRODUCT_IMPRESSION_TASK
SCHEDULE='USING CRON 0 1 * * * MST'
--SCHEDULE = '1 minute'
AS
CALL EDM_CONFIRMED_<<ENV>>.DW_APPL.SP_ONETAG_ADOBE_VISIT_LOAD_MAIN();
ALTER TASK SP_ONETAG_ADOBE_VISIT_LOAD_MAIN_TASK SET USER_TASK_TIMEOUT_MS = 7200000;

ALTER TASK SP_ONETAG_ADOBE_VISIT_LOAD_MAIN_TASK RESUME;