--liquibase formatted sql
--changeset SYSTEM:SP_ONETAG_OTHER_TO_BIM_LOAD_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_APPL;

ALTER task SP_ONETAG_OTHER_TO_BIM_LOAD_TASK
SET QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_ONETAG_OTHER_TO_BIM_LOAD_TASK", "APPCODE":"OCAT", "APPID":"OCAT", "SUBJECTAREA":"OneTag", "BOD":"OneTag", "PROCESS":"C_PIPELINE_INC_LOAD", "COMMENT":"Task Tag"}';
ALTER task SP_ONETAG_OTHER_TO_BIM_LOAD_TASK RESUME;