--liquibase formatted sql
--changeset SYSTEM:SP_ONETAG_TO_BIM_LOAD_CLICK_STREAM_IMPRESSIONS_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_APPL;

CREATE OR REPLACE TASK SP_ONETAG_TO_BIM_LOAD_CLICK_STREAM_IMPRESSIONS_TASK
WAREHOUSE = <<parm_EDM_WH_NAME>>
SCHEDULE = 'USING CRON 30 * * * * UTC'
QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_ONETAG_TO_BIM_LOAD_CLICK_STREAM_IMPRESSIONS_TASK", "APPCODE":"OCAT", "APPID":"OCAT", "SUBJECTAREA":"OneTag", "BOD":"OneTag", "PROCESS":"C_PIPELINE_INC_LOAD", "COMMENT":"Task Tag"}'
WHEN
SYSTEM$STREAM_HAS_DATA('EDM_REFINED_<<ENV>>.DW_APPL.ONETAG_CAROUSEL_FLAT_R_STREAM')
AS
CALL SP_ONE_TAG_CAROUSEL_TO_BIM_LOAD();

ALTER TASK SP_ONETAG_TO_BIM_LOAD_CLICK_STREAM_IMPRESSIONS_TASK RESUME;
