--liquibase formatted sql
--changeset SYSTEM:SP_GETPARTNERREWARDTRANSACTION_TO_BIM_LOAD_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_APPL;

CREATE OR REPLACE TASK SP_GETPARTNERREWARDTRANSACTION_TO_BIM_LOAD_TASK
WAREHOUSE='EDM_ADMIN_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.GetPartnerRewardTransaction_Flat_R_STREAM')
AS CALL SP_GetPartnerRewardTransaction_To_BIM_load();

ALTER TASK SP_GETPARTNERREWARDTRANSACTION_TO_BIM_LOAD_TASK RESUME;
