create or replace task SP_GETDOORDASH_TO_BIM_LOAD_TASK
	warehouse=PROD_INGESTION_SMALL_WH
	schedule='USING CRON 0 21 * * * America/Denver'
	QUERY_TAG='{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_GETDOORDASH_TO_BIM_LOAD_TASK", "APPCODE":"EDM"}'
	when SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.DOORDASH_ORDER_INFO_FLAT_R_STREAM') OR
  SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.DOORDASH_Transaction_INFO_FLAT_R_STREAM')
	as CALL EDM_CONFIRMED_PRD.DW_APPL.SP_GetDoordash_To_BIM_load();
