--liquibase formatted sql
--changeset SYSTEM:NET_PROMOTER_SCORE_SURVEY runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_PRD;
use schema DW_C_LOYALTY;

create or replace TABLE NET_PROMOTER_SCORE_SURVEY (
	SURVEY_ID VARCHAR(16777216) NOT NULL COMMENT 'Medallia unique identifier',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	FACILITY_INTEGRATION_ID NUMBER(38,0) COMMENT 'Unique Integration Id generated for each Store # in the Facility Table',
	TRANSACTION_ID NUMBER(38,0) COMMENT 'It is unique number for each transction',
	SURVEY_LANGUAGE_NM VARCHAR(16777216) COMMENT 'Survey language — The language in which the survey was taken (English, Spanish, etc.).',
	SURVEY_START_TS TIMESTAMP_LTZ(9) COMMENT 'Survey start date — Timestamp when the first page of the survey was sent to the survey taker.',
	SURVEY_URL_TXT VARCHAR(16777216) COMMENT 'URL the survey taker uses to access the survey.',
	SURVEY_TYPE_NM VARCHAR(16777216) COMMENT 'Survey type, e.g. Pharmacy, DUG, Delivery, Retail',
	SURVEY_METHOD_DSC VARCHAR(16777216) COMMENT 'Method in which the survey was taken.',
	SURVEY_STATUS_CD VARCHAR(16777216) COMMENT 'Survey status field tracks the state of the survey record',
	STORE_DEVELOPMENT_CYCLE_DSC VARCHAR(16777216) COMMENT 'Used for testing purposes, Identifies development phase',
	TRANSACTION_TS TIMESTAMP_LTZ(9) COMMENT 'Transaction Date/Time value from parameters',
	ROLLING_TRANSACTION_COUNT_TXT VARCHAR(16777216) COMMENT 'Rolling Transaction Number from parameters',
	LANE_NBR NUMBER(38,0) COMMENT 'Lane number value from parameters',
	MASTER_PARAMETER_ID VARCHAR(16777216) COMMENT 'String of Albertsons : separated parameters (non Pharmacy)',
	NET_PROMOTER_SCORE_SEGMENT_DSC VARCHAR(16777216) COMMENT 'Promoter, Passive, or Detractor',
	SURVEY_ELAPSE_SECS_CNT NUMBER(38,0) COMMENT 'Survey time spent — Time (seconds) the survey taker spent on the survey.',
	CUSTOMER_IP_ADDRESS_TXT VARCHAR(16777216) COMMENT 'Customer IP address — The IP address from which the survey was taken.',
	LAST_SEEN_PAGE_NM VARCHAR(16777216) COMMENT 'Last page seen — The name of the last survey page seen by (sent to) the survey taker for this survey record.',
	LAST_SUBMITTED_PAGE_NM VARCHAR(16777216) COMMENT 'Last page submitted — Name of the last survey page submitted by the survey taker.',
	SURVEY_PAGE_PATH_NBR VARCHAR(16777216) COMMENT 'Survey path in page numbers — List of the survey page numbers (multi-value field) sent to the survey taker.',
	SURVEY_PAGE_PATH_TS VARCHAR(16777216) COMMENT 'Survey path in timestamps — List of timestamps (multi-value field) when the survey pages were sent to the survey taker.',
	SURVEY_RESPONSE_TS TIMESTAMP_LTZ(9) COMMENT 'Timestamp when the survey taker completed the survey.',
	SURVEY_MOBILE_DEVICE_IND VARCHAR(16777216) COMMENT 'Survey was viewed on mobile — At least one page of the survey was viewed on mobile device.',
	SURVEY_MOBILE_DEVICE_FINISHED_IND VARCHAR(16777216) COMMENT 'Survey was submitted on mobile — The survey taker completed the survey (clicked Submit) on a mobile device.',
	MOBILE_FIRST_IND VARCHAR(16777216) COMMENT 'Survey was started on mobile device — Whether or not the survey taker started the survey on a mobile device. This is true when the Survey Engine sends the first page of the survey to a mobile device (after the survey taker clicked a link to access the survey). Once this field is true, it remains true. This field is similar to a_survey_is_started, which will also be true when this field is true.',
	PARTIAL_SURVEY_IND VARCHAR(16777216) COMMENT 'Survey was viewed (feed-based) or started (feedless), but is not finished',
	SURVEY_STARTED_IND VARCHAR(16777216) COMMENT 'Survey has started — Whether or not the survey taker started the survey.',
	SURVEY_PAGES_SUBMIT_CNT NUMBER(38,0) COMMENT 'Survey count of pages submitted — The count of the survey pages the survey taker completed and submitted.',
	SURVEY_PAGES_VALIDATION_FAILED_CNT NUMBER(38,0) COMMENT 'Count of survey pages submitted that failed validation — The count of page submissions that failed to pass validation, such as when a required question not answered.',
	SURVEY_LAST_SUBMIT_TS TIMESTAMP_LTZ(9) COMMENT 'Timestamp when the last page was submitted by the survey taker.',
	DEVICE_BRAND_NM VARCHAR(16777216) COMMENT 'Mobile Device Brand — Brand of the mobile device the survey taker used to complete the survey.',
	DEVICE_BROSWER_TXT VARCHAR(16777216) COMMENT 'Browser — Browser the survey taker used to complete the survey.',
	DEVICE_BROWSER_VERSION_DSC VARCHAR(16777216) COMMENT 'Browser with Version — Same as a_user_agent_browser, but also includes the browser version I',
	DEVICE_OPERATING_SYSTEM_NM VARCHAR(16777216) COMMENT 'Operating System — Operating system the survey taker used to complete the survey.',
	DEVICE_OPERATING_SYSTEM_VERSION_DSC VARCHAR(16777216) COMMENT 'Operating System with Version — Same as a_user_agent_os, but also includes the operating system version ID.',
	FEEDBACK_IND VARCHAR(16777216) COMMENT 'DUG flex question',
	SURVEY_BANNER_NM VARCHAR(16777216) COMMENT 'Survey Brand (Banner)',
	SURVEY_AUTO_COMPLETED_IND VARCHAR(16777216) COMMENT 'Was this record auto-completed (user abandonded the survey after page 1).',
	SURVEY_AUTO_COMPLETED_TS TIMESTAMP_LTZ(9) COMMENT 'Timestamp of auto-completion',
	SURVEY_HAS_COMMENT_IND VARCHAR(16777216) COMMENT 'Yes/No Flag (Yes = 1, No = 2) for if the survey has a written comment',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d',
	constraint XPKNET_PROMOTER_SCORE_SURVEY primary key (SURVEY_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);