--liquibase formatted sql
--changeset SYSTEM:NET_PROMOTER_SCORE_UMA_SURVEY runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_LOYALTY;

create or replace TABLE NET_PROMOTER_SCORE_UMA_SURVEY (
	SURVEY_ID VARCHAR(16777216) NOT NULL COMMENT 'Unique Identifier of the Survey from Medallia',
	RESPONSE_TS TIMESTAMP_LTZ(9) COMMENT 'TIMESTAMP of the Survey response received',
	DIGITAL_SURVEY_NM VARCHAR(16777216) COMMENT 'Name of the survey being taken. Example Dug/Delivery',
	DIGITAL_UNIT_NM VARCHAR(16777216) COMMENT 'Digital Unit for which the Survey is being taken',
	REGION_NM VARCHAR(16777216) COMMENT 'Region where the survey is being taken',
	CITY_NM VARCHAR(16777216) COMMENT 'City where the survey is being taken',
	DEVICE_VENDOR_NM VARCHAR(16777216) COMMENT 'Vendor name of the Device',
	DEVICE_MODEL_NM VARCHAR(16777216) COMMENT 'Model Name of the Device',
	DEVICE_SCREEN_RESOLUTION_TXT VARCHAR(16777216) COMMENT 'Screen resolution of the Device used for survey',
	DEVICE_OS_NM VARCHAR(16777216) COMMENT 'Operating System name of the Device used for survey',
	DEVICE_OS_VERSION_TXT VARCHAR(16777216) COMMENT 'Operating System version of the Device used for Survey',
	RETAIL_CUSTOMER_UUID VARCHAR(16777216) COMMENT 'Unique Identifier of the Customer',
	TRIGGER_ENTITY_TYPE_TXT VARCHAR(16777216) COMMENT 'Survey Trigger type',
	MOBILE_APP_VERSION_TXT VARCHAR(16777216) COMMENT 'Version of the Application',
	MOBILE_APP_ID VARCHAR(16777216) COMMENT 'Identifier of the Mobile Application',
	MOBILE_DEVICE_ID VARCHAR(16777216) COMMENT 'Identifier of the Mobile Device',
	DUG_SCORE_NBR NUMBER(38,0) COMMENT 'Net Promoter Score for DUG given by the customer',
	DUG_REASON_FOR_SCORE_COMMENT_TXT VARCHAR(16777216) COMMENT 'Reason provided by customer for the score given',
	DUG_ITEM_AVAILABILITY_SCORE_NBR NUMBER(38,0) COMMENT 'Score for Item Availability',
	DUG_SAFETY_PRECAUTIONS_TAKEN_SCORE_NBR NUMBER(38,0) COMMENT 'Score for Safety Precautions',
	DUG_ORDER_TIMELINESS_SCORE_NBR NUMBER(38,0) COMMENT 'Order TImeliness Score',
	DUG_ORDER_PROCESS_EASE_SCORE_NBR NUMBER(38,0) COMMENT 'Order Process Ease Score',
	DUG_QUALITY_SCORE_NBR NUMBER(38,0) COMMENT 'Item Quality Score',
	DUG_FRESHNESS_SCORE_NBR NUMBER(38,0) COMMENT 'Item Freshness Score',
	DUG_ORDER_ACCURACY_SCORE_NBR NUMBER(38,0) COMMENT 'Order Accuracy Score',
	DUG_ASSOCIATE_FRIENDLINESS_SCORE_NBR NUMBER(38,0) COMMENT 'Assosciate Friendliness Score',
	DUG_GIVE_MORE_FEEDBACK_IND BOOLEAN COMMENT 'Indicator if the customer is willing to provide more feedback',
	DUG_SUBSTITUTION_SATISFACTION_SCORE_NBR NUMBER(38,0) COMMENT 'Rating of satisfication with a subsitution if their order had one\n',
	DUG_SUBSTITUTION_DISSATISFACTION_REASON_TXT VARCHAR(16777216) COMMENT 'Reason for dissatisfaction with subsitution\n',
	DUG_SUBSTITUTION_DISSATISFACTION_REASON_OTHER_TXT VARCHAR(16777216) COMMENT 'Reason for dissatisfaction with subsitution (other open end)\n',
	DELIVERY_SCORE_NBR NUMBER(38,0) COMMENT 'Net Promoter Score for Delivery',
	DELIVERY_REASON_FOR_SCORE_COMMENT_TXT VARCHAR(16777216) COMMENT 'Reason provided by customer for the score given',
	DELIVERY_ITEM_AVAILABILITY_SCORE_NBR NUMBER(38,0) COMMENT 'Score for Item Availability',
	DELIVERY_SAFETY_PRECAUTIONS_TAKEN_SCORE_NBR NUMBER(38,0) COMMENT 'Score for Safety Precautions',
	DELIVERY_ORDER_TIMELINESS_SCORE_NBR NUMBER(38,0) COMMENT 'Order Timeliness Score',
	DELIVERY_ORDER_PROCESS_EASE_SCORE_NBR NUMBER(38,0) COMMENT 'Order Process Ease Score',
	DELIVERY_QUALITY_SCORE_NBR NUMBER(38,0) COMMENT 'Item Quality Score',
	DELIVERY_FRESHNESS_SCORE_NBR NUMBER(38,0) COMMENT 'Freshness Score',
	DELIVERY_ORDER_ACCURACY_SCORE_NBR NUMBER(38,0) COMMENT 'Order Accuracy Score',
	DELIVERY_ASSOCIATE_FRIENDLINESS_SCORE_NBR NUMBER(38,0) COMMENT 'Assosciate Friendliness Score',
	DELIVERY_GIVE_MORE_FEEDBACK_IND BOOLEAN COMMENT 'Indicator if the customer is willing to provide more feedback',
	DELIVERY_SUBSTITUTION_SATISFACTION_SCORE_NBR NUMBER(38,0) COMMENT 'Rating of satisfication with a subsitution if their order had one',
	DELIVERY_SUBSTITUTION_DISSATISFACTION_REASON_TXT VARCHAR(16777216) COMMENT 'Reason for dissatisfaction with subsitution',
	DELIVERY_SUBSTITUTION_DISSATISFACTION_REASON_OTHER_TXT VARCHAR(16777216) COMMENT 'Reason for dissatisfaction with subsitution (other open end)',
	BANNER_NM VARCHAR(16777216) COMMENT 'Customer parameter to include banner with survey data\n',
	ORDER_NBR VARCHAR(16777216) COMMENT 'Customer parameter to include Fulfillment Order Number with survey data\n',
	RETAIL_STORE_ID VARCHAR(16777216) COMMENT 'Customer parameter to include store # with survey data\n',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	primary key (SURVEY_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
