--liquibase formatted sql
--changeset SYSTEM:Net_Promoter_Score_Survey runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema DW_VIEWS;

CREATE OR REPLACE VIEW  Net_Promoter_Score_Survey
(
    	Survey_Id 				comment 'Medallia unique identifier',
    	Facility_Integration_ID 		comment	'Unique Integration Id generated for each Store # in the Facility Table',
	DW_FIRST_EFFECTIVE_DT 			comment 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT 			comment 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	Transaction_Id				comment 'It is unique number for each transction',
	Survey_Type_Nm 				comment 'Survey type, e.g. Pharmacy, DUG, Delivery, Retail',
	Survey_Method_Dsc 			comment 'Method in which the survey was taken.',
	Survey_Status_Cd 			comment 'Survey status field tracks the state of the survey record',
	Store_Development_Cycle_Dsc 		comment 'Used for testing purposes, Identifies development phase',
	Survey_Language_Nm 			comment 'Survey language — The language in which the survey was taken (English, Spanish, etc.).',
	Survey_Start_Ts 			comment 'Survey start date — Timestamp when the first page of the survey was sent to the survey taker',
	Survey_Response_Ts 			comment 'Timestamp when the survey taker completed the survey.',
	Survey_Url_Txt 				comment 'URL the survey taker uses to access the survey.',
	Net_Promoter_Score_Segment_Dsc 		comment 'Promoter, Passive, or Detractor',
	Transaction_Ts		 		comment	'Transaction Date/Time value from parameters',
	Rolling_Transaction_Count_Txt 		comment 'Rolling Transaction Number from parameters',
	Lane_Nbr 				comment 'Lane number value from parameters',
	Master_Parameter_Id 			comment 'String of Albertsons : separated parameters (non Pharmacy)',
	Survey_Elapse_Secs_Cnt 			comment 'Survey time spent — Time (seconds) the survey taker spent on the survey.',
	Customer_IP_Address_Txt 		comment 'Customer IP address — The IP address from which the survey was taken.',
	Last_Seen_Page_Nm 			comment 'Last page seen — The name of the last survey page seen by (sent to) the survey taker for this survey record.',
	Last_Submitted_Page_Nm 			comment 'Last page submitted — Name of the last survey page submitted by the survey taker.',
	Survey_Page_Path_Nbr 			comment 'Survey path in page numbers — List of the survey page numbers (multi-value field) sent to the survey taker.',
	Survey_Page_Path_Ts 			comment 'Survey path in timestamps — List of timestamps (multi-value field) when the survey pages were sent to the survey taker.',
	Survey_Mobile_Device_Ind 		comment 'Survey was viewed on mobile — At least one page of the survey was viewed on mobile device.',
	Survey_Mobile_Device_Finished_Ind 	comment 'Survey was submitted on mobile — The survey taker completed the survey (clicked Submit) on a mobile device.',
	Mobile_First_Ind 			comment 'Survey was started on mobile device — Whether or not the survey taker started the survey on a mobile device. This is true when the Survey Engine sends the first page of the survey to a mobile device (after the survey taker clicked a link to access the survey). Once this field is true, it remains true. This field is similar to a_survey_is_started, which will also be true when this field is true.',
	Partial_Survey_Ind 			comment 'Survey was viewed (feed-based) or started (feedless), but is not finished',
	Survey_Started_Ind 			comment 'Survey has started — Whether or not the survey taker started the survey.',
	Survey_Pages_Submit_Cnt 		comment 'Survey count of pages submitted — The count of the survey pages the survey taker completed and submitted.',
	Survey_Pages_Validation_Failed_Cnt 	comment 'Count of survey pages submitted that failed validation — The count of page submissions that failed to pass validation, such as when a required question not answered.',
	Survey_Last_Submit_Ts 			comment 'Timestamp when the last page was submitted by the survey taker.',
    	Device_Brand_Nm 			comment 'Mobile Device Brand — Brand of the mobile device the survey taker used to complete the survey.',
	Device_Broswer_Txt 			comment 'Browser — Browser the survey taker used to complete the survey.',
	Device_Browser_Version_Dsc 		comment 'Browser with Version — Same as a_user_agent_browser, but also includes the browser version I',
	Device_Operating_System_Nm 		comment 'Operating System — Operating system the survey taker used to complete the survey.',
	Device_Operating_System_Version_Dsc 	comment 'Operating System with Version — Same as a_user_agent_os, but also includes the operating system version ID.',
	FeedBack_Ind 				comment 'DUG flex question',
	Survey_Banner_Nm 			comment 'Survey Brand (Banner)',
	Survey_Auto_Completed_Ts		comment 'Timestamp of auto-completion',
	Survey_Auto_Completed_Ind 		comment 'Was this record auto-completed (user abandonded the survey after page 1)',
    	Survey_Has_Comment_Ind 			comment 'Yes/No Flag (Yes = 1, No = 2) for if the survey has a written comment',
	Dw_Create_Ts          			comment	'The timestamp the record was inserted.',
	Dw_Last_Update_Ts     			comment	'When a record is updated  this would be the current timestamp',
	Dw_Logical_Delete_Ind  			comment	'Set to True when we receive a delete record for the primary key, else False',
	Dw_Source_Create_Nm   			comment 'The Bod (data source) name of this insert.',
	Dw_Source_Update_Nm   			comment	'The Bod (data source) name of this update or delete.',
	Dw_Current_Version_Ind  		comment	'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d'
 )
COPY GRANTS
comment = 'VIEW for Net_Promoter_Score_Survey' 
As
select
    Survey_Id  							,
    Facility_Integration_ID				,
	DW_FIRST_EFFECTIVE_DT				,
	DW_LAST_EFFECTIVE_DT				,
	Transaction_Id						,
	Survey_Type_Nm						,
	Survey_Method_Dsc					,
	Survey_Status_Cd					,
	Store_Development_Cycle_Dsc			,
	Survey_Language_Nm					,
	Survey_Start_Ts						,
	Survey_Response_Ts					,
	Survey_Url_Txt						,
	Net_Promoter_Score_Segment_Dsc		,
	Transaction_Ts						,
	Rolling_Transaction_Count_Txt		,
	Lane_Nbr							,
	Master_Parameter_Id					,
	Survey_Elapse_Secs_Cnt				,
	Customer_IP_Address_Txt				,
	Last_Seen_Page_Nm					,
	Last_Submitted_Page_Nm				,
	Survey_Page_Path_Nbr				,
	Survey_Page_Path_Ts					,
	Survey_Mobile_Device_Ind			,
	Survey_Mobile_Device_Finished_Ind	,
	Mobile_First_Ind					,
	Partial_Survey_Ind					,
	Survey_Started_Ind					,
	Survey_Pages_Submit_Cnt				,
	Survey_Pages_Validation_Failed_Cnt	,
	Survey_Last_Submit_Ts				,
	Device_Brand_Nm						,
	Device_Broswer_Txt					,
	Device_Browser_Version_Dsc			,
	Device_Operating_System_Nm			,
	Device_Operating_System_Version_Dsc	,
	FeedBack_Ind						,
	Survey_Banner_Nm					,
	Survey_Auto_Completed_Ts			,
	Survey_Auto_Completed_Ind			,
    Survey_Has_Comment_Ind				,
	Dw_Create_Ts						,
	Dw_Last_Update_Ts					,
	Dw_Logical_Delete_Ind				,
	Dw_Source_Create_Nm					,
	Dw_Source_Update_Nm					,
	Dw_Current_Version_Ind
	FROM  EDM_CONFIRMED_PRD.DW_C_Loyalty.Net_Promoter_Score_Survey;