--liquibase formatted sql
--changeset SYSTEM:Fact_Offer_Reports runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_PRD;
use schema DW_C_PRODUCT;

create or replace TABLE FACT_OFFER_REPORTS (
	AGG VARCHAR(16777216) COMMENT 'Aggregator Offer ID in OMS Offer',
	AMOUNT VARCHAR(16777216) COMMENT 'DISCOUNT TIER AMT in OMS_OFFER_BENEFIT_DISCOUNT_TIER',
	ATTRIBUTE VARCHAR(16777216) COMMENT 'QUALIFICATION_ATTRIBUTE_TYPE_TXT from OMS_OFFER_QUALIFICATION_ATTRIBUTE',
	BEEP NUMBER(38,0) COMMENT 'Cashier message Beep duration number',
	CASHIER_MESSAGE VARCHAR(16777216) COMMENT 'Cashier Message Beep type text',
	CATEGORY VARCHAR(16777216) COMMENT 'Category description of the offer',
	CHANNEL VARCHAR(16777216) COMMENT 'Deliver Channel Description in OMS offer',
	CHARGEBACK_VENDOR_NAME VARCHAR(16777216) COMMENT 'Vendor name of the offers',
	CHARGEBACK_DEPARTMENT VARCHAR(16777216) COMMENT 'Description of Chargeback for benefit discounts',
	CREATED_BY VARCHAR(16777216) COMMENT 'User ID in OMS offer',
	CUSTOMER_GROUP VARCHAR(16777216) COMMENT 'Group ID from Qualification customers',
	DAY VARCHAR(3) COMMENT 'Day of the Effective start date',
	DEFER_EVALUATION_UNTIL_EOS VARCHAR(3) COMMENT 'Evaluation indication in OMS offer',
	DIGITAL_STORE_GROUP VARCHAR(16777216) COMMENT 'External offer Id with D as suffix',
	DISCOUNT VARCHAR(16777216) COMMENT 'Benefit value type description',
	DISPLAY_END_DATE DATE COMMENT 'Effective end date in OMS Offer',
	DISPLAY_START_DATE DATE COMMENT 'Effective start date in OMS Offer',
	DOLLAR_LIMIT NUMBER(38,3) COMMENT 'Amount in Benefit discount tier',
	ECOMMERCE_TEXT VARCHAR(16777216) COMMENT 'Ecom description in OMS Offer',
	END_DATE DATE COMMENT 'Effective end date in OMS Offer',
	ENTERPRISE_INSTANT_WIN NUMBER(38,0) COMMENT 'Number of prizes from OMS Offer',
	EVENT VARCHAR(16777216) COMMENT 'Event Description text from OMS offer event',
	EXCLUDED_CUSTOMER VARCHAR(16777216) COMMENT 'User Indicator from Customer group',
	EXCLUDED_TERMINALS VARCHAR(16777216) COMMENT 'Number Text from excluded terminals',
	EXTERNAL_OFFER_ID VARCHAR(16777216) COMMENT 'External Offer ID from OMS Offer',
	FIRST_DEPLOYED TIMESTAMP_LTZ(9) COMMENT 'Redemption Engine Timestamp from OMS Offer',
	FIRST_PUBLISHED TIMESTAMP_LTZ(9) COMMENT 'J4U Timestamp from OMS Offer',
	HEADLINE VARCHAR(16777216) COMMENT 'Headline Text from OMS offer',
	IN_AD VARCHAR(16777216) COMMENT 'Type code from OMS Offer',
	IN_EMAIL VARCHAR(5) COMMENT 'Email indicator in OMS Offer',
	ITEM_LIMIT NUMBER(38,0) COMMENT 'Quantity in discount tier',
	IVIE_IMAGE_ID VARCHAR(16777216) COMMENT 'Image ID in OMS Offer',
	J4U_REGIONS VARCHAR(16777216) COMMENT 'Region code from OMS offer regions',
	JUST_FOR_U_STORE_GROUP VARCHAR(16777216) COMMENT 'External offer ID with D as suffix',
	LAST_DEPLOYED TIMESTAMP_LTZ(9) COMMENT 'Redemption Engine Timestamp from OMS offer',
	LAST_PUBLISHED TIMESTAMP_LTZ(9) COMMENT 'First J4U timestamp in OMS offer',
	LAST_UPDATED_BY VARCHAR(16777216) COMMENT 'User last name from OMS offer',
	LEFT_NAV_CATEGORY VARCHAR(16777216) COMMENT 'Primart category text from OMS offer',
	LEVEL VARCHAR(16777216) COMMENT 'Discount description',
	MIN_PURCHASE NUMBER(38,0) COMMENT 'Purchase amount from product group',
	NON_DIGITAL_STORE_GROUP VARCHAR(16777216) COMMENT 'External offer ID with ND as suffix',
	OFFER_DESCRIPTION VARCHAR(16777216) COMMENT 'Protype description from OMS offer',
	OFFER_ID VARCHAR(16777216) COMMENT 'Offer ID from OMS offer',
	OFFER_NAME VARCHAR(16777216) COMMENT 'Offer Name from OMS offer',
	OFFER_TYPE VARCHAR(16777216) COMMENT 'Prototype code from OMS offer',
	POD_OFFER_DESCRIPTION VARCHAR(16777216) COMMENT 'Limit type per user description',
	POD_OFFER_DETAILS_DISCLAIMER VARCHAR(16777216) COMMENT 'Disclaimer Text',
	POINTS_GROUP NUMBER(38,0) COMMENT 'Points Group ID',
	POINTS_GROUP_1 VARCHAR(16777216) COMMENT 'Point group Name',
	PRICE_TEXT VARCHAR(16777216) COMMENT 'Title text in OMS offer',
	PRINTED_MESSAGE VARCHAR(16777216) COMMENT 'Message code in printed message',
	PRIORITY VARCHAR(16777216) COMMENT 'Priority code in OMS offer',
	PRODUCT_DISQUALIFER VARCHAR(16777216) COMMENT 'Disqualifer Text of the product',
	PRODUCT_GROUP_ID NUMBER(38,0) COMMENT 'Points program Id from benefit points',
	PRODUCT_GROUP_1 VARCHAR(16777216) COMMENT 'Points program name from benefit points',
	PROGRAM_CODE VARCHAR(16777216) COMMENT 'Program_Code from OMS offer',
	TIER_LEVEL_QUANTITY NUMBER(38,0) COMMENT 'Quantity of the points Tier',
	TIER_QUANTITY NUMBER(38,0) COMMENT 'Quantity of the Tier',
	RECEIPT_TEXT VARCHAR(16777216) COMMENT 'Receipt Text from Discount tier',
	REMOVED_FOR_ALL BOOLEAN COMMENT 'Indicator for all removed',
	REMOVED_FOR_UNCLIPPED TIMESTAMP_LTZ(9) COMMENT 'Indicator for removed unclipped',
	REMOVED_ON TIMESTAMP_LTZ(9) COMMENT 'Timestamp of the removed',
	OFFER_REQUEST_ID NUMBER(38,0) COMMENT 'OMS Offer Request ID',
	REQUESTED_BY VARCHAR(16777216) COMMENT 'Created User ID from OMS Offer',
	REWARD_FREQ VARCHAR(16777216) COMMENT 'Eligibility frequency text',
	ROG VARCHAR(16777216) COMMENT 'ROG ID from Retail store',
	SCENE_7_IMAGE_ID VARCHAR(16777216) COMMENT 'Product Image ID',
	SCORECARD_TEXT VARCHAR(16777216) COMMENT 'Text for the scorecard',
	SCORECARD VARCHAR(16777216) COMMENT 'Number of the scorecard',
	SHOPPING_LIST_CATEGORY VARCHAR(16777216) COMMENT 'primary category text',
	CASHIER_SHOW_ALWAYS BOOLEAN COMMENT 'Notification indicator for cashier message',
	PRINTED_SHOW_ALWAYS BOOLEAN COMMENT 'Notification indicator for printed message',
	START_DATE DATE COMMENT 'Offer start date from OMS Offer',
	STORE_GROUP VARCHAR(16777216) COMMENT 'Name of the store group',
	SUBMITTED TIMESTAMP_LTZ(9) COMMENT 'Unclipped Timestamp from OMS offer',
	TERMINALS VARCHAR(16777216) COMMENT 'Number text of the terminal',
	TIERS VARCHAR(16777216) COMMENT 'Tier code from OMS offer',
	ACCUMULATION_MESSAGE VARCHAR(4000) COMMENT 'Accumulation Printed Message text',
	TIME VARCHAR(16777216) COMMENT 'Time from effective start date',
	TRIGGER_CODE VARCHAR(16777216) COMMENT 'Trigger_Code from qualification',
	UNIT_OF_MEASURE VARCHAR(16777216) COMMENT 'unit type description from product group',
	USAGE VARCHAR(16777216) COMMENT 'User level description from OMS offer',
	PRICE_VALUE VARCHAR(16777216) COMMENT 'Value text from OMS offer',
	SAVINGS_VALUE_TEXT VARCHAR(16777216) COMMENT 'savings Value Text from OMS offer',
	BENEFIT_VALUE_TYPE VARCHAR(16777216) COMMENT 'benefit Value Type from OMS offer',
	ADVANCED VARCHAR(14) COMMENT 'Allow negative/ Flex negative',
	OFFER_STATUS VARCHAR(16777216) COMMENT 'Status description from OMS offer',
	EXCLUDED_PRODUCTS NUMBER(38,0) COMMENT 'Product group name from product group',
	OFFER_REQUEST_ID_TXT VARCHAR(16777216) COMMENT 'Text of Offer Request ID from OMS Offer',
	RN NUMBER(18,0) COMMENT 'Row number for latest records',
	CREATED_TS TIMESTAMP_LTZ(9) COMMENT 'Record inserted date in Fact table',
	CUSTOM_LIMIT NUMBER(38,0) COMMENT 'Usage Limit Per User from OMS Offer',
	CUSTOM_PERIOD NUMBER(38,0) COMMENT 'Period Number from OMS Offer',
	CUSTOM_TYPE VARCHAR(100) COMMENT 'Period Type from OMS Offer',
	DIVISION VARCHAR(50) COMMENT 'Region code in OMS offer',
	GROUP_NAME VARCHAR(100) COMMENT 'Group Name of Offer Request',
	PER_LB_LIMIT NUMBER(38,0) COMMENT 'Weight limit quantity in discount benefit tier'
);