--liquibase formatted sql
--changeset SYSTEM:OFFEROMS_FLAT runOnChange:true splitStatements:false OBJECT_TYPE:TABLE


USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_C_PRODUCT;
 
execute immediate $$
BEGIN
IF (NOT EXISTS(SELECT * FROM <<EDM_DB_NAME>>.INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'OFFEROMS_FLAT' AND COLUMN_NAME in ('PAYLOAD_INITIALSUBSCRIPTIONOFFER',
'PAYLOAD_ISDYNAMICOFFER','PAYLOAD_DAYSTOREDEEM')))
THEN 
    alter table OFFEROMS_FLAT ADD PAYLOAD_INITIALSUBSCRIPTIONOFFER VARCHAR(16777216),PAYLOAD_ISDYNAMICOFFER VARCHAR(16777216), PAYLOAD_DAYSTOREDEEM VARCHAR;
END IF; 
END;
$$;
