--liquibase formatted sql
--changeset SYSTEM:OMS_Offer_Qualification_Product_Group runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PRODUCT;

create or replace TABLE OMS_OFFER_QUALIFICATION_PRODUCT_GROUP (
	OMS_OFFER_ID NUMBER(38,0) NOT NULL COMMENT 'OMS Offer ID',
	PRODUCT_GROUP_ID NUMBER(38,0) NOT NULL COMMENT 'Product Group ID',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW First Effective Date',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW Last Effective Date',
	EXCLUDED_OMS_PRODUCT_GROUP_ID NUMBER(38,0) COMMENT 'Excluded OMS Product Group ID',
	QUANTITY_UNIT_TYPE_DSC VARCHAR(16777216) COMMENT 'Quantity Unit Type Description',
	QUANTITY_UNIT_DSC VARCHAR(16777216) COMMENT 'Quantity Unit Description',
	CONJUNCTION_TXT VARCHAR(16777216) COMMENT 'Conjuction Text',
	MINIMUM_PURCHASE_AMT NUMBER(38,3) COMMENT 'Minimum Purchase Amount',
	UNIQUE_PRODUCT_IND BOOLEAN COMMENT 'Unique Product Indicator',
	INHERITED_FROM_OFFER_REQUEST_IND BOOLEAN COMMENT 'Inherited From Offer Request Indicator',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW CREATE TS',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW LAST UPDATE TS',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'DW SOURCE CREATE NM',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW LOGICAL DELETE INDICATOR',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'DW CURRENT VERSION INDICATOR',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'DW SOURCE UPDATE NM',
	primary key (OMS_OFFER_ID, PRODUCT_GROUP_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
