--liquibase formatted sql
--changeset SYSTEM:OMS_Offer_Benefit_Points runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PRODUCT;

create or replace TABLE OMS_OFFER_BENEFIT_POINTS (
	OMS_OFFER_ID NUMBER(38,0) NOT NULL COMMENT 'OMS Offer Id',
	POINTS_PROGRAM_ID NUMBER(38,0) NOT NULL COMMENT 'Points Program Id',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW First Effective Dt',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW Last Effective Dt',
	POINTS_PROGRAM_NM VARCHAR(16777216) COMMENT 'Points Program Nm',
	SCORECARD_NM VARCHAR(16777216) COMMENT 'Scorecard Nm',
	SCORECARD_TXT VARCHAR(16777216) COMMENT 'Scorecard Txt',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW CREATE TS',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW LAST UPDATE TS',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'DW SOURCE CREATE NM',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW LOGICAL DELETE IND',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'DW CURRENT VERSION IND',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'DW SOURCE UPDATE NM',
	primary key (OMS_OFFER_ID, POINTS_PROGRAM_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
