--liquibase formatted sql
--changeset SYSTEM:OMS_Offer_Region runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PRODUCT;

create or replace TABLE OMS_OFFER_REGION (
	OMS_OFFER_ID NUMBER(38,0) NOT NULL COMMENT 'OMS Offer ID',
	OMS_OFFER_REGION_CD VARCHAR(16777216) NOT NULL COMMENT 'OMS Offer Region Code',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW First Effective Date',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW Last Effective Date',
	OMS_OFFER_REGION_NM VARCHAR(16777216) COMMENT 'OMS Offer Region Number',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW CREATE TS',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW LAST UPDATE TS',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'DW SOURCE CREATE NM',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW LOGICAL DELETE INDICATOR',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'DW CURRENT VERSION INDICATOR',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'DW SOURCE UPDATE NM',
	primary key (OMS_OFFER_ID, OMS_OFFER_REGION_CD, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
