--liquibase formatted sql
--changeset SYSTEM:Alter_Script_Flat_Table_ddl runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
USE DATABASE <<EDM_DB_NAME_R>>;
USE SCHEMA <<EDM_DB_NAME_R>>.DW_R_LOYALTY;

ALTER TABLE GetMeal_Plan_Recipe_flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;   
ALTER TABLE GetMeal_Plan_Cuisine_Tag_flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetRetail_Customer_Dislike_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetRetail_Customer_Dislike_Ingredients_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetMeal_Plan_Customer_Flag_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetMeal_Plan_Ingredient_Restriction_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetMeal_Plan_Ingredient_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetRetail_Customer_MealPlan_Profile_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetMeal_Plan_Restriction_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetMeal_Plan_Variety_Tag_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetRetail_Customer_Profile_To_Restriction_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
ALTER TABLE GetRetail_Customer_Dislike_To_Profile_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;

ALTER TABLE GetMeal_Plan_App_Feedback_Flat RENAME COLUMN CREATEDAT to CREATEDDATE;
ALTER TABLE GetMeal_Plan_App_Feedback_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;

ALTER TABLE GetRetail_Customer_Pending_Meal_Flat RENAME COLUMN CREATEDAT to CREATEDDATE;
ALTER TABLE GetRetail_Customer_Pending_Meal_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;

ALTER TABLE GetRetail_Customer_Meal_Plan_Flat RENAME COLUMN CREATEDAT to CREATEDDATE;
ALTER TABLE GetRetail_Customer_Meal_Plan_Flat RENAME COLUMN COOKEDAT to COOKEDDATE;
ALTER TABLE GetRetail_Customer_Meal_Plan_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;

ALTER TABLE GetRetail_Customer_Favorite_Flat RENAME COLUMN CREATEDAT to CREATEDDATE;
ALTER TABLE GetRetail_Customer_Favorite_Flat RENAME COLUMN UPDATEDAT to UPDATEDDATE;
ALTER TABLE GetRetail_Customer_Favorite_Flat RENAME COLUMN DW_CREATE_TS to DW_CREATETS;

ALTER TABLE GETMEAL_PLAN_CUSTOMER_FLAT RENAME COLUMN CREATEDAT to CREATEDDATE;
ALTER TABLE GETMEAL_PLAN_CUSTOMER_FLAT RENAME COLUMN UPDATEDAT to UPDATEDDATE;
ALTER TABLE GETMEAL_PLAN_CUSTOMER_FLAT RENAME COLUMN DW_CREATE_TS to DW_CREATETS;
