--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_LOYALTY runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_PRD;
use schema DW_C_USER_ACTIVITY;

create or replace TABLE CLICK_STREAM_LOYALTY (
	CLICK_STREAM_INTEGRATION_ID NUMBER(38,0) NOT NULL COMMENT 'Unique Key generated for each record in the Adobe transaction data',
	HIT_ID_HIGH VARCHAR(16777216) COMMENT 'Used in combination with hitid_low to uniquely identify a hit.',
	HIT_ID_LOW VARCHAR(16777216) COMMENT 'Used in combination with hitid_high to uniquely identify a hit.',
	VISIT_PAGE_NBR VARCHAR(16777216) COMMENT 'Variable used in the Hit depth dimension. Increases by 1 for each hit the user generates. Resets each visit.',
	VISIT_NBR NUMBER(38,0) COMMENT 'Variable used in the Visit number dimension. Starts at 1 and increments each time a new visit starts per visitor.',
	CLIP_ACTIONS_PER_VISIT_NBR NUMBER(38,0) COMMENT 'Coupon Clips',
	COUPON_CAROUSEL_SECTION_NM VARCHAR(16777216) COMMENT 'Coupon Carousel section details',
	COUPON_CLIP_METHOD_CD VARCHAR(16777216) COMMENT 'The method how a coupon was clipped i.e. singleclip barcodescan multiclip autoclip etc... - Expires After Hit',
	COUPON_CLIPPED_TXT VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	COUPON_ID VARCHAR(16777216) COMMENT 'The internal ID of the coupon being clipped. i.e. 860808600 - Expires After Visit',
	COUPON_NM VARCHAR(16777216) COMMENT 'The name of the coupon being clipped. i.e. On any purchase in the Produce Department - Expires After Visit',
	COUPON_PRODUCT_SKU VARCHAR(16777216) COMMENT 'The product sku where the coupon was clipped - Expires After Visit',
	COUPON_SAVINGS_AMT VARCHAR(16777216) COMMENT 'Shows the savings amount from the a clipped coupon - Expires After Visit',
	COUPON_STATUS_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	COUPON_TYPE_CD VARCHAR(16777216) COMMENT 'The type of coupon that was clipped. i.e. cc  sc pd PersonalizedDeals - Expires After Visit',
	EMAIL_CLIPALL_COUPON_TXT VARCHAR(16777216) COMMENT 'Web Only: Email ClipAll Coupon displays a list of totalCoupons couponsClipped autoclipError clipFailCode clipFailMessage when user interact on website - Expires After Visit',
	EMAIL_OFFER_ID_URL_PARAMETER_TXT VARCHAR(16777216) COMMENT 'Web Only: Email OfferID URL Parameter displays a list of offerID through which visitors landed on website - Expires After Visit',
	EXCLUDE_ROW_IND NUMBER(38,0) COMMENT 'Indicator that the record should be excluded from all analytics.  This is out-of-the-box adobe logic  that we consolidated into a simple flag. CASE WHEN(exclude_hit= 0 and hit_source not in (5 7 8 9)) THEN 0 ELSE 1 END as Exclude_Row_ind   (0=Include(FALSE) 1=Exclude(TRUE))',
	FACILITY_INTEGRATION_ID NUMBER(38,0) COMMENT 'Unique Integration Id generated for each Store # in the Facility Table',
	J4U_COUPON_SOURCE_CD VARCHAR(16777216) COMMENT 'Web Only: We do not know - Expires After Hit',
	J4U_COUPONS_AVAILABLE_NBR NUMBER(38,0) COMMENT 'Web Only: We do not know - Expires After Hit',
	J4U_FILTER_TYPE_DSC VARCHAR(16777216) COMMENT 'App Only: The Filter Type a user has set in JFU iFrame. i.e. Filter:Only Personalized Deals - Expires After Visit',
	LOYALTY_APPLICATION_COLUMN_VW VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	LOYALTY_STORE_ID VARCHAR(16777216) COMMENT 'Historic Data Only - Web Only: We do not know - Data not present from Jul20 - Expires After Visit',
	LOYALTY_ZIP_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Web Only: We do not know - Data not present from Jul20 - Expires After Visit',
	OFFER_ID VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	OFFER_TYPE_CD VARCHAR(16777216) COMMENT 'Web: Displays a list of offer that visitors interact on the website App: Only Loyalty App when users are clipping coupons on J4U. If clipped via Weekly Ad value is Weekly Ad from Personalized Deals the value is Personalized Deal - Expires After Visit',
	ORDER_ID VARCHAR(16777216) COMMENT 'ID# of the Order',
	PRODUCT_COUPON_CLIPPED_TXT NUMBER(38,0) COMMENT 'Web Only: Product - Coupon Clipped displays a list of product info where coupons are clipped by visitors - Expires After Visit',
	PRODUCT_COUPON_ID VARCHAR(16777216) COMMENT 'Web Only: Product - CouponID displays a list of coupon id which was visited by visitors - Expires After Visit',
	PRODUCT_COUPONS_AVAILABLE_NBR NUMBER(38,0) COMMENT 'Web Only: Product - Coupons Available displays a list of product info which was visited by visitors where coupons are available - Expires After Visit',
	PROMOTION_CD VARCHAR(16777216) COMMENT 'The promo code entered on checkout  i.e. SAVE20 TAKE20 etc.. - Expires After Purchase',
	REDEEMED_REWARDS_NBR NUMBER(38,0) COMMENT 'Web Only: # of Rewards Redeemed displays a total number of rewards redeemed by visitor on the website  (until its implemented on App) - Expires After Hit',
	RETAIL_CUSTOMER_UUID VARCHAR(16777216) COMMENT 'UUID# of the Retail_Customer',
	REWARD_ID VARCHAR(16777216) COMMENT 'Shows the ID of the reward clipped. i.e. 1533393857 - Expires After Hit',
	TOTAL_COUPON_CLIPPED_NBR VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	VERSION_NBR NUMBER(38,0) COMMENT 'Version Number of the Grocery Order placed by the Customer',
	RETAIL_CUSTOMER_GUID VARCHAR(16777216) COMMENT 'GUID# of the Retail_Customer',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is created this would be the current timestamp',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The data source name of this insert',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The data source name of this update or delete',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 day',
	primary key (CLICK_STREAM_INTEGRATION_ID)
);