--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_SHOP runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_PRD;
use schema DW_C_USER_ACTIVITY;

create or replace TABLE CLICK_STREAM_SHOP (
	CLICK_STREAM_INTEGRATION_ID NUMBER(38,0) NOT NULL COMMENT 'Unique Key generated for each record in the Adobe transaction data',
	HIT_ID_HIGH VARCHAR(16777216) COMMENT 'Used in combination with hitid_low to uniquely identify a hit.',
	HIT_ID_LOW VARCHAR(16777216) COMMENT 'Used in combination with hitid_high to uniquely identify a hit.',
	VISIT_PAGE_NBR VARCHAR(16777216) COMMENT 'Variable used in the Hit depth dimension. Increases by 1 for each hit the user generates. Resets each visit.',
	VISIT_NBR NUMBER(38,0) COMMENT 'Variable used in the Visit number dimension. Starts at 1 and increments each time a new visit starts per visitor.',
	CART_ADDITION_IND BOOLEAN COMMENT 'The Cart Additions’ metric shows the number of times a visitor added an item to cart. (There are numerous nuances to this metric not the least of which is that incrementing the number of units for a given product in the cart is tracked as a separate event)',
	CART_ID VARCHAR(16777216) COMMENT 'The Id associated with a users cart - Expires After Visit',
	CART_PRODUCT1_NBR VARCHAR(16777216) COMMENT 'Expires After Hit',
	CART_PRODUCT2_NBR VARCHAR(16777216) COMMENT 'Expires After Hit',
	CART_PRODUCT3_NBR VARCHAR(16777216) COMMENT 'Expires After Hit',
	CART_PRODUCT4_NBR VARCHAR(16777216) COMMENT 'Expires After Hit',
	CART_PRODUCT5_NBR VARCHAR(16777216) COMMENT 'Expires After Hit',
	CART_PRODUCT6_NBR VARCHAR(16777216) COMMENT 'Expires After Hit',
	CART_TYPE_CD VARCHAR(16777216) COMMENT 'The type of cart that is being viewed. The same cart is viewed but there are different way to open it from the main cart view checkout cart view mini cart view etc... i.e. app_cart (main app cart) app_checkout_cart (cart from checkout screen) mini_cart full_cart - Expires After Visit',
	CHECKOUT_IND BOOLEAN COMMENT 'The Checkout’ metric shows the number of times a visitor went to checkout.',
	CLUB_CARD_NBR VARCHAR(16777216) COMMENT 'The users JFU Card number fires whenever its available  - Expires After Year',
	CUSTOMER_HHID VARCHAR(16777216) COMMENT 'Fires when a user is logged in with a value like 845029223012 - Expires After Year',
	DELIVERY_TM VARCHAR(16777216) COMMENT 'Delivery time for dug and delivery i.e. 8 AM 5 PM etc.. - Expires After Purchase',
	DELIVERY_WINDOW_TXT VARCHAR(16777216) COMMENT 'Web Only: Delivery Window displays delivery slot selected by visitors on checkout page - Expires After Purchase',
	ECOM_CUSTOMER_ID VARCHAR(16777216) COMMENT 'The internal customer id of the user i.e. 555-051-1578647650762 - Expires After Visit',
	EXCLUDE_ROW_IND NUMBER(38,0) COMMENT 'Indicator that the record should be excluded from all analytics.  This is out-of-the-box adobe logic  that we consolidated into a simple flag. CASE WHEN(exclude_hit= 0 and hit_source not in (5 7 8 9)) THEN 0 ELSE 1 END as Exclude_Row_ind   (0=Include(FALSE) 1=Exclude(TRUE))',
	FACILITY_INTEGRATION_ID NUMBER(38,0) COMMENT 'Unique Integration Id generated for each Store # in the Facility Table',
	FULFILLMENT_BANNER_CD VARCHAR(16777216) COMMENT 'Shows what Safeway company analytics is firing on. i.e. albertsons  safeway vons etc.. (duplicate of v4) - Expires After Visit',
	FULFILLMENT_TYPE_CD VARCHAR(16777216) COMMENT 'Delivery Preference that is set on every analytics call including order confirmations. Main values are instore delivery and dug (pickup) - Expires After Never',
	GROSS_ORDER_IND BOOLEAN COMMENT 'The Gross Orders’ metric shows the number of times a visitor submitted an order. (There are numerous nuances to this metric not the least of which is that order cancellations are tracked as a separate event)',
	ITEM_REFUND_CD VARCHAR(16777216) COMMENT 'Expires After Hit',
	MFC_FLG VARCHAR(16777216) COMMENT 'Web Only: Micro Fulfillment Center set to true for MFC Carts - Expires After Visit',
	MTO_FLG VARCHAR(16777216) COMMENT 'Set for the prodcut on Cart Add and  PDP True Or False  - Expires After Hit',
	ORDER_CNT NUMBER(38,0) COMMENT 'The amount of orders a user has previously made. This fires on every analytics call (not on loyalty app) - Expires After Visit',
	ORDER_ID VARCHAR(16777216) COMMENT 'ID# of the Order',
	ORDER_2_ID VARCHAR(16777216) COMMENT 'Order ID once transcation is successfully completed - Expires After Visit',
	ORDER_3_ID VARCHAR(16777216) COMMENT 'Web Only: Order Ahead: Order ID displays a list of storeids along with category codes where visitors viewed it on Order Ahead section of the website - Expires After Hit',
	ORDER_ISSUE_REPORTED_TXT VARCHAR(16777216) COMMENT 'Web Only: Set to teh order issue reported when requesting refund - Expires After Hit',
	ORDER_SUBSTITUTION_OPTIONS_TXT VARCHAR(16777216) COMMENT 'Expires After Purchase',
	PAYMENT_METHOD_CD VARCHAR(16777216) COMMENT 'Payment Methods such as i.e. cc ebt cc-coa cc & coa coa and ebt-coa - Expires After Purchase',
	PICKUP_LOCATION_CD VARCHAR(16777216) COMMENT 'Location where a user is picking up their purchase. i.e. locker counter kiosk dug delivery - Expires After Visit',
	PRICE_INFORMATION_TXT VARCHAR(16777216) COMMENT 'Price of the item added to cart',
	PRODUCT_FINDING_METHOD_CD VARCHAR(16777216) COMMENT 'Displays a list of page type search recommendation through which visitors found the products on the website.  - Expires After Purchase',
	PRODUCT_LST VARCHAR(16777216) COMMENT 'Product list as passed in through the products variable. Products are delimited by commas while individual product properties are delimited by semicolons.',
	PRODUCT2_LST VARCHAR(16777216) COMMENT 'Web Only: Product List displays list unit product id unit price when added to cart by visitor on website - Expires After Hit',
	PRODUCT_NM VARCHAR(16777216) COMMENT 'The name of the product being added removed viewed in cart and searched - Expires After Visit',
	PRODUCT_PRICING_TYPE_CD VARCHAR(16777216) COMMENT 'Web: Shows the pricing type i.e. club card price App: values do not make sense in APP - Use web description - Expires After Visit',
	PRODUCT_PURCHASE_OPTIONS_TXT VARCHAR(16777216) COMMENT 'Instore Online Only  - Expires After Hit',
	PRODUCT_VIEW_IND BOOLEAN COMMENT 'The Product views’ metric shows the number of times any product was viewed.',
	GROSS_REVENUE_AMT NUMBER(16,4) COMMENT 'Gross Revenue associated with the individual cart addition',
	STORE_ID VARCHAR(16777216) COMMENT 'The ID of the Store i.e. 3132 - Shop Store ID displays a list of store id which is selected by Visitors.  - Expires After Visit',
	STORE_ZIP_CD VARCHAR(16777216) COMMENT 'Displays a list of zip code that visitors preferred while navigating on the website - Expires After Visit',
	TOTAL_CART_AMT NUMBER(38,17) COMMENT 'When a user adds an item to cart the current cart total amount is reported - Expires After Visit',
	UNIQUE_SKU_IN_CART_NBR VARCHAR(16777216) COMMENT '# of unqiue items in cart. If you have 50 items in cart but 10 quantities of 5 unqiue items then value would be 5 - Expires After Visit',
	GROSS_UNITS_NBR NUMBER(16,4) COMMENT '# of units associated with the individual cart addition',
	RETAIL_CUSTOMER_UUID VARCHAR(16777216) COMMENT 'UUID# of the Retail_Customer',
	CUSTOMER_UUID VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	VERSION_NBR NUMBER(38,0) COMMENT 'Version Number of the Grocery Order placed by the Customer',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is created this would be the current timestamp',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The data source name of this insert',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The data source name of this update or delete',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 day',
	primary key (CLICK_STREAM_INTEGRATION_ID)
);