--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_OTHER runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_PRD;
use schema DW_C_USER_ACTIVITY;

create or replace TABLE CLICK_STREAM_OTHER (
	CLICK_STREAM_INTEGRATION_ID NUMBER(38,0) NOT NULL COMMENT 'Unique Key generated for each record in the Adobe transaction data',
	HIT_ID_HIGH VARCHAR(16777216) COMMENT 'Used in combination with hitid_low to uniquely identify a hit.',
	HIT_ID_LOW VARCHAR(16777216) COMMENT 'Used in combination with hitid_high to uniquely identify a hit.',
	VISIT_PAGE_NBR VARCHAR(16777216) COMMENT 'Variable used in the Hit depth dimension. Increases by 1 for each hit the user generates. Resets each visit.',
	VISIT_NBR NUMBER(38,0) COMMENT 'Variable used in the Visit number dimension. Starts at 1 and increments each time a new visit starts per visitor.',
	ACCEPTED_LANGUAGE_CD VARCHAR(16777216) COMMENT 'Lists all accepted languages as indicated in the Accept-Language HTTP header in an image request.',
	ACCORDION_EDIT_NBR NUMBER(38,0) COMMENT 'Identifies how many Accordions that need to be editied in Checkout i.e. 0 1 2 3 etc.. - Expires After Visit',
	ACCORDION_EDIT_TXT VARCHAR(16777216) COMMENT 'Aggeration of Accordions that user MUST edit were editied i.e. Payment Order InfoPayment ContactOrder InfoPayment etc... - Expires After Visit',
	ADOBE_TNT_ID VARCHAR(16777216) COMMENT 'Used in Adobe Target integrations.',
	ACTIVITY_ID VARCHAR(16777216) COMMENT 'Web Only: Target: Activity ID displays a list of activity id for the list of campaigns displayed to visitors through Adobe Target - Expires After Visit',
	ACTIVITY_NM VARCHAR(16777216) COMMENT 'Web Only: Target: Activity Name displays a list of activity name for the list of campaigns displayed to visitors through Adobe Target - Expires After Visit',
	ADA_FLG VARCHAR(16777216) COMMENT 'Americans with Disabilities - Flag that shows if the user has enabled the ADA Experinces - Expires After Visit',
	APP_BANNER_CD VARCHAR(16777216) COMMENT 'App Only: Banner associated with the Mobile Application (separate from the Brand associated with the Store ID; you can access an Albertsons store from a Safeway app if only to be transferred into an Albertsons App)',
	APP_BUILD_NBR VARCHAR(16777216) COMMENT 'App Only: Build number of the Mobile Application: each release is assigned a unique Version Number with each build of the Version identifying more precisely which code build was installed on the users device.',
	APPLICATION_OS_TXT VARCHAR(16777216) COMMENT 'App Only:Operating System the mobile application',
	APPLICATION_SIGN_IN_IND VARCHAR(16777216) COMMENT 'The Sign in’ metric shows the number of times a visitor had successful sign in. (recorded Once Per Visit)',
	APPLICATION_TYPE_CD VARCHAR(16777216) COMMENT 'App Only:Description of the Mobile Application Type: UMA Shop App Legacy Loyalty App etc.',
	APPLICATION_VERSION_CD VARCHAR(16777216) COMMENT 'App Only:Version of the Mobile Application: each release is assigned a unique Version Number with each build of the Version tracked in a separate field',
	APPLICATION_OS_TYPE_CD VARCHAR(16777216) COMMENT 'App Only:Operating System and App Type of the mobile application',
	APPLICATION_AVAILABILITY_DT VARCHAR(16777216) COMMENT 'Flag for whether the product is available or not.',
	APPLICATION_DETAIL_TXT VARCHAR(16777216) COMMENT 'Application Level Detail ',
	APPLICATION_ORDER_STATUS_MSG VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	APPLICATION_USER_START_BY_NM VARCHAR(16777216) COMMENT 'App Only: J4U only variable. Shows how the App was launched. - Expires After Visit',
	APPLICATION_SEPARATE_LST VARCHAR(16777216) COMMENT 'We do not know - Values are shopping_list_enable and shopping_list_disable - Expires After Never',
	APPLICATION_TYPE2_CD VARCHAR(16777216) COMMENT 'Web: Reports Content type i.e. safeway albertsons J4U etc... App: Reports App Type iOS or Android - Expires After Visit',
	APPLICATION_VERSION_BUILD_NBR VARCHAR(16777216) COMMENT 'App Only: Version and Build number of the Mobile Application: each release is assigned a unique Version Number with each build of the Version identifying more precisely which code build was installed on the users device.',
	AVAILABILE_CD VARCHAR(16777216) COMMENT 'Tied to the product string on cart views. Reports if a product is available or not-available - Expires After Visit',
	BOT_TRACKING_TXT VARCHAR(16777216) COMMENT 'Historcal Only - Captures bot info from Imperva',
	BROWSER_HEIGHT_TXT VARCHAR(16777216) COMMENT 'Height in pixels of the browser window.',
	BROWSER_WIDTH_TXT VARCHAR(16777216) COMMENT 'Width in pixels of the browser window.',
	BROWSER_NM VARCHAR(250) COMMENT 'Name/Version of the browser',
	BANNER_CD VARCHAR(16777216) COMMENT 'Shows what Safeway company analytics is firing on. i.e. albertsons  safeway vons etc.. - Expires After Visit',
	BOX_TOPS_AUTH_STATE_CD VARCHAR(16777216) COMMENT 'Web Only: We do not know - Data not present from Jul20 - Expires After Visit',
	BROWSER_GEO_CD VARCHAR(16777216) COMMENT 'Web Only: Browser GEO displays visitors location through which accessing the website - Expires After Never',
	CAMPAIGN_TXT VARCHAR(16777216) COMMENT 'Variable used in the Tracking Code dimension.',
	CAMERA_ALLOWED_CD VARCHAR(16777216) COMMENT 'App Only: Shows what level of camera permissions a user has permitted on their App - Expires After Hit',
	CAMPAIGN_AFFILIATE_TXT VARCHAR(16777216) COMMENT 'Web Only: Campaign - Affiliate displays a list of campaign id related to Affiliate through visitors landed on website - Expires After Day',
	CAMPAIGN_STACKING_TXT VARCHAR(16777216) COMMENT 'Web Only: Displays a list of program along with visitor id through which visitor came to website - Expires After Month',
	CARD_LESS_REGISTRATION_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Displays YES when visitors does short registrations - Expires After Year',
	CAROUSEL_SIZE_TXT VARCHAR(16777216) COMMENT 'Web Only: Carousel Size displays list of size when visitor add/remove product/quantity from cart - Expires After Hit',
	CDA_MARKETING_CHANNEL_CD VARCHAR(16777216) COMMENT 'Expires After Visit',
	CHANNEL_MANAGER_CHANNEL_CD VARCHAR(16777216) COMMENT 'Web Only: Displays a list of program through which visitor came to the website - Channel Manager Channel displays a list of program through which visitor came to the website - Expires After Visit',
	CHANNEL_STACKING_TXT VARCHAR(16777216) COMMENT 'Web Only: Displays a list of consecutive program through which visitor came to the website - Channel Stacking displays a list of consecutive program through which visitor came to the website - Expires After Visit',
	COLOR_CD VARCHAR(16777216) COMMENT 'Color depth ID based on the value of the c_color column. References the color_depth.tsv lookup table.',
	CONNECTION_TYPE_NM VARCHAR(250) COMMENT 'Connection type The Connection type’ dimension shows how the visitor connected to the internet. This dimension is useful to determine how visitors connect to the internet to browse your site. You can use it to optimize site content based on the connection speed of visitors. Populate this dimension with data This dimension uses a combination of the ct query string and Adobe server-side logic. Adobe uses the following rules in order to determine its value: If the ct query string equals modem set the dimension item to Modem. AppMeasurement only collects this data on unsupported Internet Explorer browsers making this dimension item uncommon. Check the IP address of the hit and reference it to a lookup table internal to Adobe. If the IP address is from a mobile carrier set the dimension item to Mobile Carrier.If the ct query string equals lan set the dimension item to LAN/Wifi. If the hit originates from a Data source or is otherwise considered a special type of hit set the dimension item to Not specified.If none of the above rules are met default to the value of LAN/Wifi. Dimension items Dimension items include LAN/Wifi Mobile Carrier Modem and Not Specified. LAN/Wifi: The visitor connected to the internet through a landline or wifi hotspot.Mobile Carrier: The visitor connected to the internet through a mobile carrier. Modem: The visitor connected to the internet through a modem on an unsupported Internet Explorer browser. Not Specified: The hit did not have a connection type.',
	COUNTRY_NM VARCHAR(250) COMMENT 'Countries: The Countries’ dimension reports the country where the hit originated from. This dimension is useful to help determine what the most popular countries visitors originate from when visiting your site. You could use this data to focus on marketing efforts in these countries or make sure your site experience is optimal in countries that have different primary languages. Populate this dimension with data This dimension references lookup rules internal to Adobe. The lookup value is based on the IP address sent with the hit. Adobe partners with Digital Element to maintain lookups between IP address and country. This dimension works out of the box for all implementations. Dimension items Dimension items include countries all over the world. Example values include United States United Kingdom or India. Differences between reported and actual locationSince this dimension is based on IP address some scenarios can show a difference between reported location and actual location: IP addresses that represent corporate proxies: These visitors can appear as traffic coming through the user’s corporate network which can be a different location if the user is working remotely.Mobile IP addresses: Mobile IP targeting works at varying levels depending on the location and the network. A number of carriers backhaul IP traffic through centralized or regional points of presence.Satellite ISP users: Identifying the specific location of these users is difficult as they typically appear to originate from the uplink location.Military and government IPs: Represents personnel traveling around the globe and entering through their home location rather than the base or office where they are currently stationed.',
	CARRIER_NM VARCHAR(16777216) COMMENT 'Adobe Advertising Cloud integration variable. Specifies the mobile carrier. References the carrier lookup table.',
	CAMPAIGN_2_TXT VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	CREATE_DT DATE COMMENT 'transform DATE_TIME to date (just date)',
	CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'transform DATE_TIME to date (just date)',
	CUSTOM_NAV_LINK_TRACKING_TXT VARCHAR(16777216) COMMENT 'App: Only on J4U iFrame when delivery app is clicked Web: Custom Nav/Link Tracking displays just for you app through which visitor selected the deliver apps - Expires After Visit',
	CUSTOMER_STATUS_CD VARCHAR(16777216) COMMENT 'If a user is a first or returning user. A user is considered returning only after they have had 1 or more orders. If a user has never made an order they will always be shown as first - Expires After Visit',
	DELIVERY_ATTENDED_UNATTENDED_FLG VARCHAR(16777216) COMMENT 'Whether a delivery is attended or unattended - Expires After Purchase',
	DETAIL_VIEW_TXT VARCHAR(16777216) COMMENT 'App Only?: Displays a list of popup options on App - Very little hits. Possibly broken. - Expires After Visit',
	ECOM_LOGIN_ID VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	ECOM_NAV_LINK_TRACKING_CD VARCHAR(16777216) COMMENT 'Web Only: We do not know - Expires After Visit',
	ELEVAATE_FLG VARCHAR(16777216) COMMENT 'Historic Data Only - Web Only: We do not know - Expires After Visit',
	ELEVAATE_POISTION_NBR VARCHAR(16777216) COMMENT 'Historic Data Only - Web Only: We do not know - Expires After Visit',
	EMAIL_HHID_URL_PARAMETER_TXT VARCHAR(16777216) COMMENT 'Values appended from email parameters - Expires After Visit',
	EMAIL_THEME_URL_PARAMETER_TXT VARCHAR(16777216) COMMENT 'Values appended from email parameters - Expires After Visit',
	ENVIRONMENT_CD VARCHAR(16777216) COMMENT 'Web Only: Environment displays a list of website environment that visitors are interacting - Expires After Visit',
	ERROR_FEATURE_CD VARCHAR(16777216) COMMENT 'The component / feature that had an error - Expires After Hit',
	ERROR_ID VARCHAR(16777216) COMMENT 'The Error ID generated from the system - Expires After Hit',
	ERROR_MESSAGE_DSC VARCHAR(16777216) COMMENT 'The message from an error - Expires After Hit',
	ERROR_PAGE_DSC VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	EVENT_ID_URL_PARAMETER_TXT VARCHAR(16777216) COMMENT 'Web Only: EventID URL Parameter displays a list of event id of J4U that visitors clicked on the website - Expires After Hit',
	EVENT_NM VARCHAR(250) COMMENT 'Name of the event triggered on the hit. Includes both default events and custom events 1-1000. Uses event.tsv lookup.',
	EXPERIENCE_NM VARCHAR(16777216) COMMENT 'Web Only: Target: Experience Name displays a list of experience name for the list of campaigns displayed to visitors through Adobe Target - Expires After Visit',
	EXCLUDE_ROW_IND NUMBER(38,0) COMMENT 'Indicator that the record should be excluded from all analytics.  This is out-of-the-box adobe logic  that we consolidated into a simple flag. CASE WHEN(exclude_hit= 0 and hit_source not in (5 7 8 9)) THEN 0 ELSE 1 END as Exclude_Row_ind   (0=Include(FALSE) 1=Exclude(TRUE))',
	EXCLUDE_HIT_FLG NUMBER(38,0) COMMENT 'Flag indicating that the hit is excluded from reporting. The visit_num column is not incremented for excluded hits.|1: Not used. Part of a scrapped feature.|2: Not used. Part of a scrapped feature.|3: No longer used. User agent exclusion|4: Exclusion based on IP address|5: Vital hit info missing such as page_url pagename page_event or event_list|6: JavaScript did not correctly process hit|7: Account-specific exclusion such as in a VISTA rules|8: Not used. Alternate account-specific exclusion.|9: Not used. Part of a scrapped feature.|10: Invalid currency code|11: Hit missing a timestamp on a timestamp-only report suite or a hit contained a timestamp on a non-timestamp report suite|12: Not used. Part of a scrapped feature.|13: Not used. Part of a scrapped feature.|14: Target hit that did not match up with an Analytics hit|15: Not currently used.|16: Advertising Cloud hit that did not match up to an Analytics hit',
	FACILITY_INTEGRATION_ID NUMBER(38,0) COMMENT 'Unique Integration Id generated for each Store # in the Facility Table',
	FACE_BOOK_ACCOUNT_NM VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	FACE_BOOK_BANNER_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	FACE_BOOK_CAMPAIGN_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	FILTER_SECTION_TXT VARCHAR(16777216) COMMENT 'Shows the filter brand selected for the category as [FILTER TYPE] : [FILTER SELECTION. i.e. brand : signature select - Expires After Visit',
	FILTER_TYPE_CD VARCHAR(16777216) COMMENT 'Shows the filter category selected. i.e. deals aisles. If multiple filter categories are selected they are seperated by commas i.e.  dealsaisles - Expires After Visit',
	FIRST_HIT_REFERRER_TYPE_CD VARCHAR(16777216) COMMENT 'Numeric ID representing the referrer type of the very first referrer of the visitor. Uses referrer_type.tsv lookup.',
	GA_UTM_CAMPAIGN_NM VARCHAR(16777216) COMMENT 'Web Only: GA utm_ campaign displays a list of campaign name through which visitors landed on the website. - Expires After Custom(180 Days)',
	GA_UTM_CAMPAIGN_MEDIUM_TXT VARCHAR(16777216) COMMENT 'Web Only: GA utm_ medium displays a list of advertising or marketing through which visitors landed on the website. - Expires After Custom(180 Days)',
	GA_UTM_SOURCE_CD VARCHAR(16777216) COMMENT 'Web Only: GA utm_source displays a list of advertisers site publication through which visitors landed on the website. - Expires After Custom(180 Days)',
	GLOBAL_NO_SUBSTITUTION_CD VARCHAR(16777216) COMMENT 'Web: Displays while placing order whether visitor Checked or Unchecked Global Substitution....and more App: Displays while placing order whether visitor Checked or Unchecked Global Substitution - Expires After Purchase',
	HIDDEN_CATEGORIES_TXT VARCHAR(16777216) COMMENT 'App Only: Displays a list of hidden categories options at the time of launching the App - Expires After Visit',
	HIT_SOURCE_CD NUMBER(38,0) COMMENT 'Indicates what source the hit came from. Hit sources 1 2 and 6 are billed.|1: Standard image request without timestamp|2: Standard image request with timestamp|3: Live data source upload with timestamps|4: Not used|5: Generic data source upload|6: Full processing data source upload|7: TransactionID data source upload|8: No longer used; Previous versions of Adobe Advertising Cloud data sources|9: No longer used; Adobe Social summary metrics|10: Audience Manager server-side forwarding used',
	HOME_PAGE_CAROUSEL_TXT VARCHAR(16777216) COMMENT 'Web Only: displays a list of categories where visitors selected the products/coupons on shop page. - Expires After Hit',
	IP_ADDRESS_NBR VARCHAR(16777216) COMMENT 'The users IP Address i.e. 65.208.210.98 - Expires After Visit',
	IMPRESSIONS_COMPONENT_TXT VARCHAR(16777216) COMMENT 'App: Show if users have ZTP enabled or not Web: Impressions Component displays list of components viewed by the visitor on website - Expires After Hit',
	INTERNAL_CAMPAIGN_TRACKING_ID VARCHAR(16777216) COMMENT 'Displays a list of campaigns that visitors have clicked internally on the website - Expires After Purchase',
	INTERNAL_SEARCH_TERMS_TXT VARCHAR(16777216) COMMENT 'Displays a list of search terms that were used to return a search results page. If a search term was a typeahead value that value will be shown here the actual user input is in v91 - Expires After Visit',
	INTERNAL_SEARCH_TYPE_CD VARCHAR(16777216) COMMENT 'Records the type of search once search results screen is loaded. i.e. internalsearch:typeahead:suggestion internalsearch:typeahead:recent internalsearch:standard internalsearch:standard = you typed in all the search term internalsearch:typeahead:suggestion = you clicked a prefilled option internalsearch:typeahead:popular = you clicked a trending item internalsearch:typeahead:recent = you clicked a Recently Search Item - Expires After Visit',
	INTERNAL_SEARCH_RESULTS_NBR NUMBER(38,0) COMMENT '# of search results on a search results page. If no search results then the value is 0 - Expires After Visit',
	INTERNAL_SEARCH_TXT VARCHAR(16777216) COMMENT 'The Internal Searches’ metric shows the number of times a visitor searched on the site.',
	JAVA_SCRIPT_VERSION_NBR VARCHAR(16777216) COMMENT 'Lookup ID of JavaScript version based on j_jscript. Uses lookup table.',
	KMSI_TXT VARCHAR(16777216) COMMENT 'Web Only: ..... - Expires After Visit',
	LAST_ACTIVITY_FLG VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	LAUNCH_RULE_TXT VARCHAR(16777216) COMMENT 'Web Only: Launch Rule displays list of rules executed when visitor interacted on website - Expires After Hit',
	LANGUAGE_NM VARCHAR(250) COMMENT 'Languaged used',
	LINK_DETAIL_TXT VARCHAR(16777216) COMMENT 'Expires After Visit',
	LIST_INTERACTION_TYPE_CD VARCHAR(16777216) COMMENT 'App Only: Displays if visitors clicked on check uncheck add on loyalty app. - Expires After Visit',
	LOCATION_SHARING_ENABLED_FLG VARCHAR(16777216) COMMENT 'App Only: Shows what level of location sharing a user has permitted on their App - Expires After Hit',
	LOGIN_KMSI_TXT VARCHAR(16777216) COMMENT 'Web Only: Login Keep Me Signed In displays the login status of visitors - Expires After Visit',
	MAP_CLICKS_TXT VARCHAR(16777216) COMMENT 'Web Only: Activity Map Clicks displays a list links clicked by visitors on website - Expires After Visit',
	MAP_LINK_DSC VARCHAR(16777216) COMMENT 'Activity Map link',
	MAP_LINK_BY_REGION_NM VARCHAR(16777216) COMMENT 'Activity Map link by region',
	MAP_PAGE_CD VARCHAR(16777216) COMMENT 'Activity Map page',
	MAP_REGION_CD VARCHAR(16777216) COMMENT 'Activity Map region',
	MARKETING_CHANNEL_CD VARCHAR(16777216) COMMENT 'Numeric ID that identifies the Last touch channel dimension. Lookup for this ID can be found in the Marketing Channel Manager.',
	MARKETING_CHANNEL_DTL VARCHAR(16777216) COMMENT 'Variable used in the Last touch detail dimension.',
	MEDIA_PLACEMENT_CD VARCHAR(16777216) COMMENT 'Web Only: displays a product grid or banner through which products where selected by visitors. - Expires After Hit',
	MEDIA_TYPE_CD VARCHAR(16777216) COMMENT 'Historic Data Only - We do not know - The media type as to how a product was added to cart? i.e. carousels product-grid product-carousel - Expires After Visit',
	MESSAGE_TXT VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	MOBILE_APPLICATION_FIRST_LAUNCH_DT DATE COMMENT 'App Only: First launch date of a mobile app - Expires After Visit',
	MOBILE_DEVICE_ID VARCHAR(16777216) COMMENT 'App Only: The AAID / IDFA of a mobile app user - Expires After Visit',
	MOBILE_DEVICE_OS_VERSION_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	MOBILE_J4U_APPLICATION_VERSION_CD VARCHAR(16777216) COMMENT 'App Only: The version of JFU App (iFrame) - Expires After Visit',
	MOBILE_LATITUDE_LONGITUDE_DGR VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	MOBILE_DEVICE_MODEL_NM VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	MOBILE_VS_NON_MOBILE_FLG VARCHAR(16777216) COMMENT 'Identifies if a user is on Mobile or Non-mobile device - Expires After Visit',
	MODAL_NAME_LINK_NM VARCHAR(16777216) COMMENT 'Shows the modals views / clicks inside those modals. On App - Drawers are also considered Modals - Expires After Hit',
	NETWORK_TXT VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	NAVIGATION_SOURCE_TXT VARCHAR(16777216) COMMENT 'App Only: How users a navigating on J4U iFrame Content (old data) - Expires After Visit',
	NEW_REPEAT_VISITORS_TXT VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	NOTIFICATION_ALLOWED_TXT VARCHAR(16777216) COMMENT 'App Only: Shows what level of notification permissions a user has permitted on their App - Expires After Hit',
	OPERATING_SYSTEM_CD VARCHAR(16777216) COMMENT 'Numeric ID representing the operating system of the visitor. Based on the user_agent column. Uses os lookup.',
	OPERATING_SYSTEM_NM VARCHAR(250) COMMENT 'Operating System Name and Version',
	ORDER_ID VARCHAR(16777216) COMMENT 'ID# of the Order',
	PFM_SOURCE_CD VARCHAR(16777216) COMMENT 'Web Only: Tied to the product string. When an item is added to cart that is out of stock then you have the ability to add similar items to cart. Similar items can be added from PDP or Full Cart page - Expires After Purchase',
	PFM_SUBSECTION_1_CD VARCHAR(16777216) COMMENT 'PFM SubSection1 displays a list of page type which was the starting point of product selected by visitors on the website - Expires After Purchase',
	PLATFORM_CD VARCHAR(16777216) COMMENT 'Breakdown(s) of Web/App app_type_os/web desktop/web mobile etc.',
	PROVIDER_TXT VARCHAR(16777216) COMMENT 'Does not work - will look into it - Expires After Visit',
	PURCHASE_ID VARCHAR(16777216) COMMENT 'Unique identifier for a purchase as set using the purchaseID variable. Used by the duplicate_purchase column.',
	PAGE_1_NM VARCHAR(16777216) COMMENT 'Used to populate the Page dimension. If the pagename variable is empty Analytics uses page_url instead.',
	PAGE_2_NM VARCHAR(16777216) COMMENT 'Shows the pagename - hierarchy of page levels a user is on. Concatenation of v4:[CHANNEL]:v151:v152:v153:v154 - Expires After Visit',
	PAGE_URL_TXT VARCHAR(16777216) COMMENT 'Web Only: Displays a list of current page url that visitor visited on the website - Expires After Visit',
	PAST_PURCHASE_ITEMS_TXT VARCHAR(16777216) COMMENT 'Web Only: Past Purchase Items displays list of past purchased when visitors done the search and landed on search results page - Expires After Visit',
	PFM_DETAIL_TXT VARCHAR(16777216) COMMENT 'Displays a list of page type search recommendation through which visitors found the products on the website.  - Expires After Purchase',
	PLACEMENT_TYPE_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	PLATFORM_DSC VARCHAR(16777216) COMMENT 'Breakdown(s) of Web/App app_type_os/web desktop/web mobile etc.',
	PLUGIN_NM VARCHAR(250) COMMENT 'No longer used. List of numeric ID’s that correspond to plugins available within the browser. Uses plugins.tsv lookup.',
	PREMIUM_SLOTS_TXT VARCHAR(16777216) COMMENT 'Web Only: Premium Slots displays premius slots set to visitors on the checkout or not - Expires After Visit',
	PREVIOUS_PAGE_NM VARCHAR(16777216) COMMENT 'Displays a list of page prior to the current page that visitor visited on the website - Expires After Visit',
	PUSH_NOTIFICATIONS_MESSAGE_ID VARCHAR(16777216) COMMENT 'App Only: The Push ID clicked by a user. The Push ID is generated from the Push Notification Service - Expires After Visit',
	RECIPE_NM VARCHAR(16777216) COMMENT 'Web Only: Shows Recipe name - Expires After Visit',
	RECIPE_SOURCE_CD VARCHAR(16777216) COMMENT 'Web Only: The category under which the recipes is listed is called the recipe source. This is a numeric value grabbed from the recipe url path. - Expires After Visit',
	REFERRING_APPLICATION_CD VARCHAR(16777216) COMMENT 'The utm_source utm_medium and timestamp of referring source - Expires After Visit',
	REFERRER_TYPE_ID VARCHAR(250) COMMENT 'Single-string identifier of the type of referral for the hit. Used in the Referrer type dimension. 1: Inside your site,2: Other web sites,3: Search engines,4: Hard drive,5: USENET,6: Typed/Bookmarked (no referrer),7: Email,8: No JavaScript,9: Social Networks',
	RESOLUTION_NM VARCHAR(250) COMMENT 'Numeric ID representing the resolution of the monitor. Used in the Monitor resolution dimension. Uses resolution.tsv lookup table.',
	RETAIL_CUSTOMER_UUID VARCHAR(16777216) COMMENT 'UUID# of the Retail_Customer',
	SDK_VERISON_NBR VARCHAR(16777216) COMMENT 'App only: The Adobe Experince Platform SDK Version that is install in the App - Expires After Visit',
	SEARCH_ENGINE_NM VARCHAR(250) COMMENT 'The Search Engine that referred the visitor to your site. Uses search_engines.tsv lookup.',
	SOCIAL_AUTHORS_TXT VARCHAR(16777216) COMMENT 'Web Only: We do not know - Expires After Visit',
	SOCIAL_MEDIA_CHANNEL_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	SOCIAL_MEDIA_CONTENT_TITLE_TXT VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	SOCIAL_PLATFORMS_TXT VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	SORT_SELECTION_TXT VARCHAR(16777216) COMMENT 'Shows the sorting method of the filer. i.e. price low to high - Expires After Visit',
	SOURCE_SITE_TYPE_CD VARCHAR(16777216) COMMENT 'Web: Source / Site Type displays a list of banner visited by visitors through App or website. App: Shows source of analytics call. i.e. values report as Mobile Application|[BANNER] or Mobile Application|J4U - Expires After Visit',
	SUBSCRIPTION_DT VARCHAR(16777216) COMMENT 'Web Only: Subscription Date displays a visitor subscribed date to savings club - Expires After Never',
	SUBSCRIPTION_FUNNEL_CD VARCHAR(16777216) COMMENT 'Web Only: Subscription Funnel displays enrollment to monthly/annually from checkout to confirmation page  (for now until its released for App) - Expires After Hit',
	SUBSCRIPTION_STATUS_CD VARCHAR(16777216) COMMENT 'App: Whether a user is a subscriber or non-subscriber to savings club Web: Subscription Status displays a visitor is a subscriber or non-subscriber to savings club - Expires After Never',
	SUB_SECTION1_TXT VARCHAR(16777216) COMMENT 'Level 1 of pagename - Expires After Visit',
	SUB_SECTION2_TXT VARCHAR(16777216) COMMENT 'Level 2 of pagename - Expires After Visit',
	SUB_SECTION3_TXT VARCHAR(16777216) COMMENT 'Level 3 of pagename - Expires After Visit',
	SUB_SECTION4_TXT VARCHAR(16777216) COMMENT 'Level 4 of pagename - Expires After Visit',
	SYNDIGO_CONTENT_TXT VARCHAR(16777216) COMMENT 'Expires After Hit',
	TIME_PARTING_TXT VARCHAR(16777216) COMMENT 'Takes the timestamp of collected hits and breaks it into more meaningful dimensions such as “Hour of Day” or “Day of Week”. This eVar is a classification.  - Expires After Visit',
	TIMESTAMP_MARKETPLACE_TXT VARCHAR(16777216) COMMENT 'Web Only: Scenarios needed to update the description - Data not present from May20 - Expires After Hit',
	TOP_NAV_USAGE_CD VARCHAR(16777216) COMMENT 'Web Only: Top Nav usage displays menu navigation selected from top by visitor on website - Expires After Visit',
	TYPED_SEARCH_CNT VARCHAR(16777216) COMMENT 'The amount of characters a user has typed into the input field. Fires on the search results page. - Expires After Visit',
	TYPED_SEARCH_TERM_CD VARCHAR(16777216) COMMENT 'Shows the search term a user typed. If typeahead was prepopulated this value will still show what was typed by the user. - Expires After Visit',
	UMA_APPLICATION_NM VARCHAR(16777216) COMMENT 'App Only: If value is true then data is only from UMA App - Expires After Hit',
	USER_ACTION_CD VARCHAR(16777216) COMMENT 'Interaction events - User initiated actions that happen on pages or values used to define success events - Expires After Visit',
	USER_ACTION_TYPE_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	USER_AGENT_NM VARCHAR(16777216) COMMENT 'The device / browser a user is using - Expires After Visit',
	USER_MESSAGES_TXT VARCHAR(16777216) COMMENT 'Web Only: User Messages displays a list of user interaction error or modal displayed title on the website - Expires After Hit',
	USER_MESSAGE_STATUS_CD VARCHAR(16777216) COMMENT 'Historic Data Only - Expires After Visit',
	USER_TYPE_CD VARCHAR(16777216) COMMENT 'Web Only: User Type displays a list of user type when visitor does the login - Expires After Visit',
	VERSION_NBR NUMBER(38,0) COMMENT 'Version Number of the Grocery Order placed by the Customer',
	VIDEO_AD_LOAD_TXT VARCHAR(16777216) COMMENT 'Video Ad Load ',
	VISITOR2_ID VARCHAR(16777216) COMMENT 'Always fires. Unique value that represents a customer in both the online and offline systems. - Expires After Never',
	VISIT_ID VARCHAR(16777216) COMMENT 'Unique identifier for a visit as identified by Adobe',
	VISITOR_ID VARCHAR(16777216) COMMENT 'Unique identifier for a visitor as identified by Adobe',
	VISITOR_INTERACTED_HH_MM_TM VARCHAR(16777216) COMMENT 'Displays Hours and Minutes where visitors interacted on website. - Expires After Visit',
	WEARABLE_DEVICE_CD VARCHAR(16777216) COMMENT 'The wearable device a user is using i.e. AppleWatch - Expires After Visit',
	ZTP_DEFAULT_METHOD_CD VARCHAR(16777216) COMMENT 'The default ZTP (Zero Touch Payment) Method i.e. Apple Pay Empty Wallet ACH Store Value Card PREPAID - Expires After Visit',
	ZTP_METHOD_CD VARCHAR(16777216) COMMENT 'How users are paying with ZTP (Zero Touch Payment) i.e. ACH Store Value Card - Expires After Visit',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is created this would be the current timestamp',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The data source name of this insert',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The data source name of this update or delete',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 day',
	TOP_NAV_CLICKS_TXT VARCHAR(16777216) COMMENT 'Number of Clip Actions Per Visit',
	primary key (CLICK_STREAM_INTEGRATION_ID)
);