--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_UNASSIGNED runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema DW_VIEWS;

CREATE OR REPLACE VIEW CLICK_STREAM_UNASSIGNED
(
  CLICK_STREAM_INTEGRATION_ID   COMMENT 'UNIQUE KEY GENERATED FOR EACH RECORD IN THE ADOBE TRANSACTION DATA'
 ,EXCLUDE_ROW_IND  			    COMMENT 'INDICATOR THAT THE RECORD SHOULD BE EXCLUDED FROM ALL ANALYTICS.  THIS IS OUT-OF-THE-BOX ADOBE LOGIC  THAT WE CONSOLIDATED INTO A SIMPLE FLAG. CASE WHEN(EXCLUDE_HIT= 0 AND HIT_SOURCE NOT IN (5 7 8 9)) THEN 0 ELSE 1 END AS EXCLUDE_ROW_IND   (0=INCLUDE(FALSE) 1=EXCLUDE(TRUE))'
 ,HIT_ID_HIGH     			    COMMENT 'USED IN COMBINATION WITH HITID_LOW TO UNIQUELY IDENTIFY A HIT.'
 ,HIT_ID_LOW      			    COMMENT 'USED IN COMBINATION WITH HITID_HIGH TO UNIQUELY IDENTIFY A HIT.'
 ,VISIT_PAGE_NBR				COMMENT	'Variable used in the Hit depth dimension. Increases by 1 for each hit the user generates. Resets each visit.'
 ,VISIT_NBR						COMMENT	'Variable used in the Visit number dimension. Starts at 1 and increments each time a new visit starts per visitor.'
 ,TEXT_V110       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V208       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V209  	 			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V210	 	                COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V211                     COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V213                     COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V214                     COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V215                     COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V216 	 			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V217       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V218       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V219       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V220	 				    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V221  	 			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V222       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V223    	 			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V224    	 			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V225     	 		    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V226       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V227       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V228       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V229       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V230       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V231       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V232       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V233       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V234       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V235       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V236       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V237       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V238    	 			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V239       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V240       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V241	 				    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V242       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V243	 				    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V244       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V245       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V246       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V247       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V248       			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V249	 				    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V250      			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V27      			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V28      			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V29      			    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V30					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V31					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V34					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V39					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V41					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V42					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V43					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V44					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V45					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V48					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V50					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V69					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V72					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V79					    COMMENT 'UNASSIGNED VARIABLE'
 ,TEXT_V82					    COMMENT 'UNASSIGNED VARIABLE'
 ,Post_Event_List_Txt        	COMMENT 'This is a Raw column with direct mapping which has multiple Post Events of a Visit'
 ,DW_CREATE_TS  comment'When a record is created this would be the current timestamp'
 ,DW_LAST_UPDATE_TS  comment'When a record is updated this would be the current timestamp'
 ,DW_LOGICAL_DELETE_IND  comment'Set to True when we receive a delete record for the primary key, else False'
 ,DW_SOURCE_CREATE_NM  comment'The data source name of this insert'
 ,DW_SOURCE_UPDATE_NM  comment'The data source name of this update or delete'
 ,DW_CURRENT_VERSION_IND  comment'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 day'		
)
COPY GRANTS
comment = 'VIEW FOR CLICK_STREAM_UNASSIGNED' 
AS
SELECT
 CLICK_STREAM_INTEGRATION_ID            							
,EXCLUDE_ROW_IND
,HIT_ID_HIGH    			
,HIT_ID_LOW   
,VISIT_PAGE_NBR
,VISIT_NBR     			
,TEXT_V110     				
,TEXT_V208        			
,TEXT_V209 					
,TEXT_V210    			
,TEXT_V211      			
,TEXT_V213      			
,TEXT_V214      			
,TEXT_V215     				
,TEXT_V216					
,TEXT_V217      			
,TEXT_V218         			
,TEXT_V219      			
,TEXT_V220				
,TEXT_V221 					
,TEXT_V222      			
,TEXT_V223    				
,TEXT_V224    				
,TEXT_V225     				
,TEXT_V226       			
,TEXT_V227      				
,TEXT_V228      				
,TEXT_V229       			
,TEXT_V230          			
,TEXT_V231          			
,TEXT_V232          			
,TEXT_V233         			
,TEXT_V234          			
,TEXT_V235          			
,TEXT_V236          			
,TEXT_V237         			
,TEXT_V238    				
,TEXT_V239      				
,TEXT_V240        			
,TEXT_V241					
,TEXT_V242         			
,TEXT_V243					
,TEXT_V244          			
,TEXT_V245      				
,TEXT_V246        			
,TEXT_V247      				
,TEXT_V248      				
,TEXT_V249					
,TEXT_V250      				
,TEXT_V27      				
,TEXT_V28      				
,TEXT_V29      				
,TEXT_V30					
,TEXT_V31					
,TEXT_V34					
,TEXT_V39					
,TEXT_V41					
,TEXT_V42					
,TEXT_V43					
,TEXT_V44					
,TEXT_V45					
,TEXT_V48					
,TEXT_V50					
,TEXT_V69					
,TEXT_V72					
,TEXT_V79					
,TEXT_V82
,Post_Event_List_Txt					
,DW_CREATE_TS				
,DW_LAST_UPDATE_TS			
,DW_LOGICAL_DELETE_IND		
,DW_SOURCE_CREATE_NM			
,DW_SOURCE_UPDATE_NM			
,DW_CURRENT_VERSION_IND
FROM  EDM_CONFIRMED_PRD.DW_C_USER_ACTIVITY.CLICK_STREAM_UNASSIGNED;