--liquibase formatted sql
--changeset SYSTEM:GET_FRESHPASS_SUBSCRIPTION_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME_R>>;
use schema <<EDM_DB_NAME_R>>.DW_APPL;

CREATE OR REPLACE TASK GET_FRESHPASS_SUBSCRIPTION_TASK
WAREHOUSE='EDM_ADMIN_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.GetFreshpass_Flat_R_STREAM')
AS CALL SP_GetFreshpass_Subscription_To_BIM_load();

ALTER TASK GET_FRESHPASS_SUBSCRIPTION_TASK RESUME;
