--liquibase formatted sql
--changeset SYSTEM:table_Partner_Grocery_Order_DETAIL_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE PARTNER_GROCERY_ORDER_TENDER_EXCEPTIONS (
	ORDER_ID VARCHAR(50),
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	APPROVAL_CD VARCHAR(10),
	LOADDATE TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	MASKED_CREDIT_CARD_NBR VARCHAR(16777216)
);
