--liquibase formatted sql
--changeset SYSTEM:table_Partner_Grocery_Order_CUSTOMER_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE PARTNER_GROCERY_ORDER_CUSTOMER_EXCEPTIONS (
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	SOURCE_CUSTOMER_ID VARCHAR(100),
	LOYALTY_PHONE_NBR VARCHAR(12),
	FIRST_NM VARCHAR(50),
	LAST_NM VARCHAR(50),
	EMAIL_ADDRESS_TXT VARCHAR(100),
	CONTACT_PHONE_NBR VARCHAR(12),
	RETAIL_CUSTOMER_UUID VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
