--liquibase formatted sql
--changeset SYSTEM:table_PARTNER_GROCERY_ORDER_TENDER_DOORDASH_WRK runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE PARTNER_GROCERY_ORDER_TENDER_DOORDASH_WRK (
	ORDER_ID VARCHAR(16777216),
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	APPROVAL_CD VARCHAR(16777216),
	LOADDATE TIMESTAMP_NTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	FILENAME VARCHAR(16777216),
	MASKED_CREDIT_CARD_NBR VARCHAR(16777216),
	DML_TYPE VARCHAR(1),
	SAMEDAY_CHG_IND NUMBER(1,0)
);
