--liquibase formatted sql
--changeset SYSTEM:table_PARTNER_GROCERY_ORDER_HEADER_DOORDASH_WRK runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE PARTNER_GROCERY_ORDER_HEADER_DOORDASH_WRK (
	ORDER_ID VARCHAR(16777216),
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	TRANSACTION_DT DATE,
	STORE_TRANSACTION_TS TIMESTAMP_LTZ(9),
	NET_AMT NUMBER(19,5),
	PARTNER_ID VARCHAR(20),
	PARTNER_NM VARCHAR(100),
	FACILITY_INTEGRATION_ID NUMBER(38,0),
	STORE_ID VARCHAR(16777216),
	ALCOHOLIC_IND BOOLEAN,
	LOADDATE TIMESTAMP_NTZ(9),
	SNAP_IND BOOLEAN,
	DW_LOGICAL_DELETE_IND BOOLEAN,
	FILENAME VARCHAR(16777216),
	DML_TYPE VARCHAR(1),
	SAMEDAY_CHG_IND NUMBER(1,0)
);
