--liquibase formatted sql
--changeset SYSTEM:table_PARTNER_GROCERY_ORDER_CUSTOMER_DOORDASH_WRK runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE PARTNER_GROCERY_ORDER_CUSTOMER_DOORDASH_WRK (
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	SOURCE_CUSTOMER_ID VARCHAR(16777216),
	LOYALTY_PHONE_NBR VARCHAR(16777216),
	FIRST_NM VARCHAR(16777216),
	LAST_NM VARCHAR(16777216),
	EMAIL_ADDRESS_TXT VARCHAR(16777216),
	CONTACT_PHONE_NBR VARCHAR(16777216),
	RETAIL_CUSTOMER_UUID VARCHAR(16777216),
	DML_TYPE VARCHAR(1),
	SAMEDAY_CHG_IND NUMBER(1,0),
	FILENAME VARCHAR(16777216),
	DW_LOGICAL_DELETE_IND BOOLEAN
);
