--liquibase formatted sql
--changeset SYSTEM:SP_GETEPISODIC_TO_BIM_LOAD_EPISODIC_RECIPIES_ADDED_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK

use database <<EDM_DB_NAME>>;
use schema DW_APPL;

CREATE OR REPLACE TASK SP_GETEPISODIC_TO_BIM_LOAD_EPISODIC_RECIPIES_ADDED_TASK
WAREHOUSE='<<WAREHOUSE>>'
SCHEDULE='480 minutes'
QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_GETEPISODIC_TO_BIM_LOAD_EPISODIC_RECIPIES_ADDED_TASK", "APPCODE":"EMAQ", "OBJECT_CATEGORY":"INBOUND",
"TECHNICAL_CONTACT":"LOYALTY"}'
WHEN (SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.EPISODIC_RECIPIES_ADDED_FLAT_R_STREAM'))
AS CALL SP_GETEPISODIC_TO_BIM_LOAD_EPISODIC_RECIPIES_ADDED('<<EDM_DB_NAME_R>>.DW_APPL.EPISODIC_RECIPIES_ADDED_FLAT_R_STREAM','<<EDM_DB_NAME>>','<<EDM_DB_NAME_VIEW>>','DW_C_LOYALTY','DW_C_STAGE');

ALTER TASK SP_GETEPISODIC_TO_BIM_LOAD_EPISODIC_RECIPIES_ADDED_TASK RESUME;
