--liquibase formatted sql
--changeset SYSTEM:table_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;


create or replace TABLE PARTNER_GROCERY_ORDER_CUSTOMER_EXCEPTIONS (
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	SOURCE_CUSTOMER_ID VARCHAR(100),
	LOYALTY_PHONE_NBR VARCHAR(12),
	FIRST_NM VARCHAR(50),
	LAST_NM VARCHAR(50),
	EMAIL_ADDRESS_TXT VARCHAR(100),
	CONTACT_PHONE_NBR VARCHAR(12),
	RETAIL_CUSTOMER_UUID VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);

create or replace TABLE PARTNER_GROCERY_ORDER_DETAIL_EXCEPTIONS (
	ORDER_ID VARCHAR(50),
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	ITEM_NBR NUMBER(14,0),
	UPC_ID NUMBER(14,0),
	UPC_ID_TXT VARCHAR(14),
	ITEM_DSC VARCHAR(500),
	ITEM_QTY NUMBER(16,5),
	ITEM_TAX_AMT NUMBER(16,2),
	RECEIPT_NBR VARCHAR(50),
	UNIT_PRICE_AMT NUMBER(16,4),
	REVENUE_AMT NUMBER(16,2),
	ALCOHOLIC_IND BOOLEAN,
	STORE_TRANSACTION_TS VARCHAR(16777216),
	LOYALTY_PHONE_NBR VARCHAR(12),
	USER_ID VARCHAR(16777216),
	SNAP_IND BOOLEAN,
	EBT_SNAP_AMT NUMBER(9,2),
	EBT_CASH_AMT NUMBER(9,2),
	UNADJUSTED_ITEM_TAX_RT NUMBER(9,4),
	UNADJUSTED_ITEM_TAX_AMT NUMBER(9,4),
	FILENAME VARCHAR(16777216),
	DML_TYPE VARCHAR(16777216),
	SAMEDAY_CHG_IND VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);

create or replace TABLE PARTNER_GROCERY_ORDER_TENDER_EXCEPTIONS (
	ORDER_ID VARCHAR(50),
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	APPROVAL_CD VARCHAR(10),
	LOADDATE TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	MASKED_CREDIT_CARD_NBR VARCHAR(16777216)
);

create or replace TABLE PARTNER_GROCERY_ORDER_HEADER_EXCEPTIONS (
	ORDER_ID VARCHAR(50),
	PARTNER_GROCERY_ORDER_CUSTOMER_INTEGRATION_ID NUMBER(38,0),
	TRANSACTION_DT DATE,
	STORE_TRANSACTION_TS TIMESTAMP_LTZ(9),
	NET_AMT NUMBER(16,2),
	PARTNER_ID VARCHAR(20),
	PARTNER_NM VARCHAR(100),
	FACILITY_INTEGRATION_ID NUMBER(38,0),
	STORE_ID VARCHAR(20),
	LOADDATE TIMESTAMP_NTZ(9),
	SNAP_IND BOOLEAN,
	FILENAME VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	ALCOHOLIC_IND BOOLEAN
);
