--liquibase formatted sql
--changeset SYSTEM:insights_views runOnChange:true splitStatements:false OBJECT_TYPE:VIEW

use database <<EDM_VIEW_NAME>>;
use schema DW_VIEWS;

create or replace view F_Partner_Customer_Insight(
CUSTOMER_INSIGHT_F_SK,
DAY_ID,
RETAIL_CUSTOMER_HOUSEHOLD_D1_SK,
BUSINESS_PARTNER_D1_SK,
RETAIL_STORE_D1_SK,
BANNER_D1_SK,
DIVISION_D1_SK,
HOUSEHOLD_ID,
TRANSACTION_DT,
PRODUCT_GROUP_NM,
ORDER_ID,
GMV_ORDER_VALUE_AMT,
LOYALTY_INDICATOR_CD,
FRESHPASS_SUBSCRIBED_IND,
B4U_LINKED_IND,
DW_LAST_UPDATE_TS,
DW_CREATE_TS
)
as 
select 
CUSTOMER_INSIGHT_F_SK,
DAY_ID,
RETAIL_CUSTOMER_HOUSEHOLD_D1_SK,
BUSINESS_PARTNER_D1_SK,
RETAIL_STORE_D1_SK,
BANNER_D1_SK,
DIVISION_D1_SK,
HOUSEHOLD_ID,
TRANSACTION_DT,
PRODUCT_GROUP_NM,
ORDER_ID,
GMV_ORDER_VALUE_AMT,
LOYALTY_INDICATOR_CD,
FRESHPASS_SUBSCRIBED_IND,
B4U_LINKED_IND,
DW_LAST_UPDATE_TS,
DW_CREATE_TS

from <<EDM_DB_NAME_A>>.DW_RETAIL_EXP.F_Partner_Customer_Insight;




---------------------------

