--liquibase formatted sql
--changeset SYSTEM:task_1 runOnChange:true splitStatements:false OBJECT_TYPE:SP
use database <<EDM_DB_NAME_C>>;
use schema <<EDM_DB_NAME_C>>.DW_APPL;

ALTER TASK SP_F_ORDER_TRANSACTION_LOAD_TASK SUSPEND;

CREATE OR REPLACE TASK F_ORDER_TRANSACTION_TASK
		  WAREHOUSE = '<<WH>>'
		  SCHEDULE = 'USING CRON 30 8 * * * Asia/Kolkata'
		  QUERY_TAG = '{"OBJECT_TYPE":"SP", "OBJECT_NAME":"F_ORDER_TRANSACTION_TASK","TECHNICAL_CONTACT":"LOYALTY"}'
		  WHEN 
		  SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_C>>.DW_APPL.GW_REG99_TXNS_2020_STREAM_LOYALTY_2')
		  AS 
		  CALL "SP_F_ORDER_TRANSACTION_LOAD"();

ALTER TASK F_ORDER_TRANSACTION_TASK RESUME;


