--liquibase formatted sql
--changeset SYSTEM:Create_RERUN_for_Foodstorm runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA <<EDM_DB_NAME>>.DW_C_STAGE;

CREATE OR REPLACE TRANSIENT TABLE GETFOODSTORM_FLAT_RERUN

DATA_RETENTION_TIME_IN_DAYS = 0

AS

SELECT * FROM <<EDM_DB_NAME_R>>.DW_APPL.GetFOODSTORM_Flat_R_STREAM where 1=2;
