--liquibase formatted sql
--changeset SYSTEM:OCGP_PRIZE_TRANSACTION runOnChange:true splitStatements:false OBJECT_TYPE:VIEW

USE DATABASE <<EDM_DB_NAME_VIEW>>;
USE SCHEMA DW_VIEWS;

CREATE OR REPLACE VIEW OCGP_PRIZE_TRANSACTION(
												PRIZE_ID COMMENT 'UNIQUE IDENTIFIER OF THE PRIZE',
												PROGRAM_CD COMMENT 'UNIQUE CODE FOR THE PROGRAM. USED BY OCRP TO MANAGE POINTS / REWARDS FOR A PROGRAM BUCKET',
												RETAIL_CUSTOMER_UUID COMMENT 'THIS ID REPRESENTS AN UNIVERSAL UNIQUE IDENTIFIER FOR A RETAIL CUSTOMER',
												REDEEM_TS COMMENT 'date of which prize was redeemed',
												DW_FIRST_EFFECTIVE_DT COMMENT 'THE DATE THE RECORD WAS INSERTED.  FOR UPDATE PRIMARY KEYS THIS VALUES IS USED FROM THE PRIOR RECORD OF THE PRIMARY KEY',
												DW_LAST_EFFECTIVE_DT COMMENT 'FOR THE CURRENT RECORD THIS IS 12/31/9999 FOR UPDATED RECORDS BASED ON THE PRIMARY KEY OF THE TABLE, THIS IS THE NEW CURRENT RECORDS DW_FIRST_EFFECTIVE_DT -1 DAY',
												PRIZE_NM COMMENT 'NAME OF THE PRIZE WON',
												TRANSACTION_DSC COMMENT 'Description of the transaction',
												FULFILLMENT_DT COMMENT 'date of which prize was fulfilled',
												FULFILLMENT_STATUS_CD COMMENT 'status of prize redemption',
												SWEEPSTAKE_DRAW_DT COMMENT 'date of sweepstake draw if the prize is sweepstake',
												RETAIL_STORE_ID COMMENT 'Customers Store Identifier',
												TRANSACTION_STATUS_CD COMMENT 'Completed Vs Potential',
												DW_CREATE_TS COMMENT 'THE TIMESTAMP THE RECORD WAS INSERTED',
												DW_LAST_UPDATE_TS COMMENT 'WHEN A RECORD IS UPDATED  THIS WOULD BE THE CURRENT TIMESTAMP',
												DW_LOGICAL_DELETE_IND COMMENT 'SET TO TRUE WHEN WE RECEIVE A DELETE RECORD FOR THE PRIMARY KEY, ELSE FALSE',
												DW_SOURCE_CREATE_NM COMMENT 'THE BOD (DATA SOURCE) NAME OF THIS INSERT',
												DW_SOURCE_UPDATE_NM COMMENT 'THE BOD (DATA SOURCE) NAME OF THIS UPDATE OR DELETE',
												DW_CURRENT_VERSION_IND COMMENT 'SET TO YES WHEN THE CURRENT RECORD IS DELETED,  THE LAST EFFECTIVE DATE ON THIS RECORD IS STILL SET TO BE  CURRENT DATE -1 D'
												) COMMENT='VIEW FOR OCGP_PRIZE_TRANSACTION'
												AS
												SELECT
												 PRIZE_ID
												,PROGRAM_CD
												,RETAIL_CUSTOMER_UUID
												,REDEEM_TS
												,DW_FIRST_EFFECTIVE_DT
												,DW_LAST_EFFECTIVE_DT
												,PRIZE_NM
												,TRANSACTION_DSC
												,FULFILLMENT_DT
												,FULFILLMENT_STATUS_CD
												,SWEEPSTAKE_DRAW_DT
												,RETAIL_STORE_ID
												,TRANSACTION_STATUS_CD
												,DW_CREATE_TS
												,DW_LAST_UPDATE_TS
												,DW_LOGICAL_DELETE_IND
												,DW_SOURCE_CREATE_NM
												,DW_SOURCE_UPDATE_NM
												,DW_CURRENT_VERSION_IND
												FROM <<EDM_DB_NAME>>.DW_C_LOYALTY.OCGP_PRIZE_TRANSACTION;
