--liquibase formatted sql
--changeset SYSTEM:SP_CLICK_STREAM_BOT_LOGIC_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_PRD;
use schema DW_APPL;

CREATE OR REPLACE TASK SP_CLICK_STREAM_BOT_LOGIC_TASK
WAREHOUSE='EDM_ENGINEER_WH'
SCHEDULE='USING CRON 0 0 * * * UTC'
AS CALL SP_CLICK_STREAM_BOT_LOGIC_PRC();

ALTER TASK SP_CLICK_STREAM_BOT_LOGIC_TASK RESUME;