--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_HISTORICAL_LOAD_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database EDM_CONFIRMED_PRD;
use schema DW_APPL;

CREATE OR REPLACE TASK CLICK_STREAM_HISTORICAL_LOAD_TASK
WAREHOUSE='PROD_DELIVERY_HUGE_WH'
SCHEDULE='USING CRON 0/30 04-21 * * * America/Los_Angeles'
AS call  sp_GetAdobeClickHitData_TO_LOAD_CLICK_STREAM_HISTORY('EDM_CONFIRMED_PRD','DW_C_STAGE','DW_C_USER_ACTIVITY');

ALTER TASK CLICK_STREAM_HISTORICAL_LOAD_TASK RESUME;