--liquibase formatted sql
--changeset SYSTEM:Offer_Request_Promotion_Period_Type runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PURCHASING;

create or replace TABLE OFFER_REQUEST_PROMOTION_PERIOD_TYPE (
	OFFER_REQUEST_ID NUMBER(38,0) NOT NULL,
	PROMOTION_PERIOD_ID VARCHAR(50) NOT NULL,
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL,
	DW_LAST_EFFECTIVE_DT DATE NOT NULL,
	PROMOTION_PERIOD_NM VARCHAR(200),
	PROMOTION_WEEK_ID VARCHAR(20),
	PROMOTION_START_DT DATE,
	PROMOTION_END_DT DATE,
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	primary key (OFFER_REQUEST_ID, PROMOTION_PERIOD_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);
