--liquibase formatted sql
--changeset SYSTEM:table_Bim runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PURCHASING;

create or replace TABLE OFFER_REQUEST_BUY_PRODUCT_GROUP (
	OFFER_REQUEST_ID NUMBER(38,0) NOT NULL,
	USER_INTERFACE_UNIQUE_ID NUMBER(38,0) NOT NULL,
	PRODUCT_GROUP_NM VARCHAR(200) NOT NULL,
	PRODUCT_GROUP_VERSION_ID NUMBER(38,0) NOT NULL,
	STORE_GROUP_VERSION_ID NUMBER(38,0) NOT NULL,
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL,
	DW_LAST_EFFECTIVE_DT DATE NOT NULL,
	PRODUCT_GROUP_ID NUMBER(38,0),
	PRODUCT_GROUP_DSC VARCHAR(200),
	DISPLAY_ORDER_NBR NUMBER(38,0),
	ITEM_QTY NUMBER(14,4),
	UNIT_OF_MEASURE_CD VARCHAR(10),
	UNIT_OF_MEASURE_NM VARCHAR(25),
	UNIT_OF_MEASURE_DSC VARCHAR(100),
	GIFT_CARD_IND VARCHAR(5),
	ANY_PRODUCT_IND VARCHAR(5),
	UNIQUE_ITEM_IND VARCHAR(5),
	CONJUNCTION_DSC VARCHAR(16777216),
	MINIMUM_PURCHASE_AMT NUMBER(14,4),
	MAXIMUM_PURCHASE_AMT NUMBER(14,4),
	INHERITED_IND VARCHAR(5),
	EXCLUDED_PRODUCT_GROUP_ID NUMBER(38,0),
	EXCLUDED_PRODUCT_GROUP_NM VARCHAR(200),
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	constraint XPKPRODUCTGROUP primary key (OFFER_REQUEST_ID, USER_INTERFACE_UNIQUE_ID, PRODUCT_GROUP_NM, PRODUCT_GROUP_VERSION_ID, STORE_GROUP_VERSION_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);





create or replace TABLE OFFER_REQUEST_EXCLUDED_PROMOTION (
	OFFER_REQUEST_ID NUMBER(38,0) NOT NULL,
	PROMO_CD VARCHAR(16777216) NOT NULL COMMENT 'Promo code cannot be used (not combinable) with other promo codes',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d',
	primary key (OFFER_REQUEST_ID, PROMO_CD, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
);


