--liquibase formatted sql
--changeset SYSTEM:Offer_Request_Offer_Specification runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PURCHASING;

create or replace TABLE OFFER_REQUEST_OFFER_SPECIFICATION (
	OFFER_REQUEST_ID NUMBER(38,0) NOT NULL,
	USER_INTERFACE_UNIQUE_ID NUMBER(38,0) NOT NULL,
	STORE_GROUP_VERSION_ID NUMBER(38,0) NOT NULL,
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL,
	DW_LAST_EFFECTIVE_DT DATE NOT NULL,
	DISPLAY_ORDER_NBR NUMBER(38,0),
	PROTO_TYPE_CD VARCHAR(50),
	PROTO_TYPE_DSC VARCHAR(250),
	PROTO_TYPE_SHORT_DSC VARCHAR(50),
	STORE_TAG_NBR NUMBER(38,0),
	STORE_TAG_AMT VARCHAR(16777216),
	LOYALTY_PROGRAM_TAG_IND VARCHAR(5),
	STORE_TAG_DSC VARCHAR(500),
	POD_HEADLINE_TXT VARCHAR(100),
	POD_OFFER_DSC VARCHAR(200),
	POD_PRICE_INFO_TXT VARCHAR(100),
	POD_DISCLAIMER_TXT VARCHAR(20000),
	POD_DISPLAY_START_DT DATE,
	POD_DISPLAY_END_DT DATE,
	POD_CUSTOMER_FRIENDLY_CATEGORY_CD VARCHAR(50),
	POD_CUSTOMER_FRIENDLY_CATEGORY_DSC VARCHAR(250),
	POD_CUSTOMER_FRIENDLY_CATEGORY_SHORT_DSC VARCHAR(50),
	INSTANT_WIN_PROGRAM_ID NUMBER(38,0),
	INSTANT_WIN_VERSION_ID NUMBER(38,0),
	INSTANT_WIN_PRIZE_ITEM_QTY NUMBER(38,0),
	INSTANT_WIN_FREQUENCY_DSC VARCHAR(100),
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	POD_HEADLINE_SUB_TXT VARCHAR(16777216),
	POD_OFFER_DETAIL_CD VARCHAR(50),
	POD_OFFER_DETAIL_DSC VARCHAR(250),
	POD_OFFER_DETAIL_SHORT_DSC VARCHAR(50),
	POD_ITEM_QTY NUMBER(38,0),
	POD_UNIT_OF_MEASURE_CD VARCHAR(10),
	POD_UNIT_OF_MEASURE_NM VARCHAR(25),
	USAGE_LIMIT_TYPE_TXT VARCHAR(50),
	primary key (OFFER_REQUEST_ID, USER_INTERFACE_UNIQUE_ID, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT)
)COMMENT='Offers included in an offer request. One offer request can have multiple offers.'
;
