--liquibase formatted sql
--changeset SYSTEM:Offer_Request_Promotion_Program_Type runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view OFFER_REQUEST_PROMOTION_PROGRAM_TYPE(
	OFFER_REQUEST_ID COMMENT 'Offer_Request_Id',
	PROGRAM_TYPE_CD COMMENT 'Program_Type_Cd',
	DW_FIRST_EFFECTIVE_DT COMMENT 'DW_First_Effective_Dt',
	DW_LAST_EFFECTIVE_DT COMMENT 'DW_Last_Effective_Dt',
	PROGRAM_TYPE_NM COMMENT 'Program_Type_Nm',
	PROGRAM_SUB_TYPE_CD COMMENT 'Program_Sub_Type_Cd',
	PROGRAM_SUB_TYPE_NM COMMENT 'Program_Sub_Type_Nm',
	DW_CREATE_TS COMMENT 'DW_CREATE_TS',
	DW_LAST_UPDATE_TS COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM COMMENT 'DW_SOURCE_CREATE_NM',
	DW_SOURCE_UPDATE_NM COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IND COMMENT 'DW_CURRENT_VERSION_IND'
) COMMENT='View For Offer_Request_Promotion_Program_Type'
 as 
Select 
Offer_Request_Id	,
Program_Type_Cd	,
DW_First_Effective_Dt	,
DW_Last_Effective_Dt	,
Program_Type_Nm	,
Program_Sub_Type_Cd	,
Program_Sub_Type_Nm	,
DW_CREATE_TS	,
DW_LAST_UPDATE_TS	,
DW_LOGICAL_DELETE_IND	,
DW_SOURCE_CREATE_NM	,
DW_SOURCE_UPDATE_NM	,
DW_CURRENT_VERSION_IND	
From EDM_CONFIRMED_PRD.DW_C_PURCHASING.Offer_Request_Promotion_Program_Type;