--liquibase formatted sql
--changeset SYSTEM:BPD_OFFER_REQUEST runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view BPD_OFFER_REQUEST(
	REQUEST_ID COMMENT 'Offer Request is equivalent to the ROB. Needed for updates - like Edit Price or Cancel/Remove.',
	PROGRAM_CODE COMMENT '3 letter Program Code, BPD-Base Personalize Deals',
	TEMPLATE_ID COMMENT 'This would be used if you want to communicate to OMS to put a template in “Parked” until a certain date.',
	MOB_ID COMMENT 'This value is equivalent to the \"Offer Number\" (aka 6 Digit number) today.',
	ALLOCATION_CD COMMENT 'Formerly called price code. About how pricing works with regards to two tier pricing.',
	BRAND_AND_SIZE COMMENT 'Either use this or Product Group name in the Description field in the Pricing Tool',
	PROGRAM_TYPE COMMENT 'Offer Program Type Base or default',
	AMOUNT COMMENT 'Price, useful if you ever want to review the amounts that were used in a previous period',
	DISCOUNT COMMENT 'Price Point (Items) or Price Point (Per Lb)',
	OFFER_REQUEST_STATUS COMMENT 'To filter out Canceled ORs',
	REP_UPC COMMENT 'Universal Product Code',
	PRODUCT_GROUP_ID COMMENT 'identifier for gorup of products',
	PRICE_UNTIL_DATE COMMENT 'This value is on the OR',
	CAT_ID COMMENT 'Product Category Identifier',
	PRODUCT_GROUP_NAME COMMENT 'Usually a \"Base Product Group\" but can be a regular one.',
	GROUP_ID COMMENT ' derived in the data using Rep UPC. Needed for allocation default process per Denise. ',
	REGION_ID COMMENT 'Region unique identifier',
	PERIOD_ID COMMENT 'Year and Week of Year Identifier i.e., 202103',
	WEEK_ID COMMENT ' Week identifier i.e., 202141',
	UPC COMMENT 'Array of UPCs / PLUs - Just UPCs.  Exclude the PLUs from the list',
	OMS_LAST_MODIFIED_BY COMMENT 'person updated last',
	OMS_LAST_MODIFIED_DATE COMMENT 'latest upated timestamp of the offer'
) COMMENT='VIEW FOR BPD_OFFER_REQUEST'
 as
SELECT DISTINCT  O_REQ.OFFER_REQUEST_ID AS REQUEST_ID 
,O_REQ.PROMOTION_PROGRAM_TYPE_CD AS PROGRAM_CODE
,O_REQ.TEMPLATE_ID
,O_REQ.OFFER_BANK_ID AS MOB_ID
,O_REQ.ALLOCATION_TYPE_CD    AS  ALLOCATION_CD
,O_REQ.BRAND_INFO_TXT AS BRAND_AND_SIZE 
,UPPER(oppt.PROGRAM_TYPE_CD) AS PROGRAM_TYPE 
,O_REQ_DT.DISCOUNT_AMT AS AMOUNT
,O_REQ_DTV.BENEFIT_VALUE_TYPE_DSC AS DISCOUNT
,O_REQ_S.OFFER_REQUEST_STATUS_DSC AS OFFER_REQUEST_STATUS
,ORPG.REPRESENTATIVE_UPC_NBR AS REP_UPC
,ORPG.PRODUCT_GROUP_ID
,ORPG.ITEM_OFFER_EFFECTIVE_END_DT  AS PRICE_UNTIL_DATE
,CT.CAT_ID AS CAT_ID
,OPG.PRODUCT_GROUP_NM  AS PRODUCT_GROUP_NAME
,SMIC_GROUP_CD  AS GROUP_ID 
,O_REQ_REG.REGION_ID
,O_REQ_PPT.PROMOTION_PERIOD_ID AS PERIOD_ID
,O_REQ_PPT.PROMOTION_WEEK_ID AS WEEK_ID
,OPG.UPC_CD AS UPC
,O_REQ_UPDT.OMS_LAST_MODIFIED_BY
,O_REQ_UPDT.OMS_LAST_MODIFIED_DATE
FROM "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST" O_REQ
JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_STATUS" O_REQ_S ON  O_REQ.OFFER_REQUEST_ID = O_REQ_S.OFFER_REQUEST_ID 
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_DISCOUNT_TIER" O_REQ_DT ON O_REQ.OFFER_REQUEST_ID = O_REQ_DT.OFFER_REQUEST_ID   AND O_REQ_DT.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_DT.DW_LOGICAL_DELETE_IND =FALSE
LEFT JOIN  ( SELECT OFFER_REQUEST_ID,PROGRAM_TYPE_CD,ROW_NUMBER() OVER( PARTITION BY OFFER_REQUEST_ID ORDER BY DW_CREATE_TS DESC) RN   
            FROM "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PROMOTION_PROGRAM_TYPE" WHERE DW_CURRENT_VERSION_IND =TRUE AND DW_LOGICAL_DELETE_IND =FALSE) oppt on oppt.OFFER_REQUEST_ID = O_REQ.OFFER_REQUEST_ID AND RN =1
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_DISCOUNT_VERSION_DISCOUNT" O_REQ_DTV ON  O_REQ.OFFER_REQUEST_ID = O_REQ_DTV.OFFER_REQUEST_ID  AND O_REQ_DTV.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_DTV.DW_LOGICAL_DELETE_IND =FALSE
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PRODUCT_GROUP" ORPG ON ORPG.OFFER_REQUEST_ID = O_REQ.OFFER_REQUEST_ID AND ORPG.DW_CURRENT_VERSION_IND =TRUE AND ORPG.DW_LOGICAL_DELETE_IND =FALSE
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PRODUCT"."OMS_OFFER" O_OMS ON O_REQ.OFFER_REQUEST_ID = O_OMS.OFFER_REQUEST_ID AND O_OMS.DW_CURRENT_VERSION_IND =TRUE AND O_OMS.DW_LOGICAL_DELETE_IND =FALSE
LEFT JOIN (select  listagg(b.UPC_CD,',') UPC_CD, a.PRODUCT_GROUP_ID ,a.PRODUCT_GROUP_NM from "EDM_CONFIRMED_PRD"."DW_C_PRODUCT"."OMS_PRODUCT_GROUP" a
            JOIN "EDM_CONFIRMED_PRD"."DW_C_PRODUCT"."OMS_PRODUCT_GROUP_UPC" b on a.PRODUCT_GROUP_ID = b.PRODUCT_GROUP_ID
            WHERE a.DW_CURRENT_VERSION_IND =TRUE AND a.DW_LOGICAL_DELETE_IND =FALSE  
           AND  b.DW_CURRENT_VERSION_IND =TRUE AND b.DW_LOGICAL_DELETE_IND =FALSE
           AND  LIST_TYPE_DSC ='Final'  group by a.product_group_id,a.PRODUCT_GROUP_NM 
          )OPG ON OPG.PRODUCT_GROUP_ID = ORPG.PRODUCT_GROUP_ID  
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_GROUP" ORG ON ORG.OFFER_REQUEST_ID = O_REQ.OFFER_REQUEST_ID  
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_REGION" O_REQ_REG ON O_REQ.OFFER_REQUEST_ID = O_REQ_REG.OFFER_REQUEST_ID AND O_REQ_REG.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_REG.DW_LOGICAL_DELETE_IND =FALSE
LEFT JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PROMOTION_PERIOD_TYPE" O_REQ_PPT ON  O_REQ.OFFER_REQUEST_ID = O_REQ_PPT.OFFER_REQUEST_ID AND O_REQ_PPT.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_PPT.DW_LOGICAL_DELETE_IND =FALSE

LEFT JOIN (select OFFER_REQUEST_ID,b.CORPORATE_ITEM_CD, SMIC_GROUP_CD,SMIC_CATEGORY_CD ,
           CASE WHEN  LEN(TO_CHAR(SMIC_CATEGORY_CD))= 1 THEN  CONCAT(TO_CHAR(b.SMIC_GROUP_CD) ,  CONCAT('0',TO_CHAR(SMIC_CATEGORY_CD)  ) ) 
           ELSE CONCAT(TO_CHAR(b.SMIC_GROUP_CD) ,  TO_CHAR(SMIC_CATEGORY_CD) ) END AS CAT_ID
           from  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PRODUCT_GROUP"  a
           JOIN (SELECT CORPORATE_ITEM_CD,SMIC_GROUP_CD, SMIC_CATEGORY_CD,ROW_NUMBER() OVER ( partition by CORPORATE_ITEM_CD ORDER BY DW_CREATE_TS DESC ) RN FROM "EDM_CONFIRMED_PRD"."DW_C_PRODUCT"."CORPORATE_ITEM" )      b on a.CORPORATE_ITEM_CD = b.CORPORATE_ITEM_CD 
            WHERE RN = 1-- and a.OFFER_REQUEST_ID = '1761250134'
          ) CT ON CT.OFFER_REQUEST_ID = O_REQ.OFFER_REQUEST_ID  

LEFT JOIN ( SELECT OFFER_REQUEST_ID , MAX(UPDATE_TS)AS  OMS_LAST_MODIFIED_DATE ,   MAX(CONCAT(CONCAT(USER_FIRST_NM ,' ' ), USER_LAST_NM )) AS OMS_LAST_MODIFIED_BY
              FROM  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_USER_UPDATE"  WHERE USER_TYPE_CD = 'updatedUser' -- AND OFFER_REQUEST_ID  =1677556275 
               GROUP BY OFFER_REQUEST_ID  
          )
O_REQ_UPDT ON  O_REQ.OFFER_REQUEST_ID = O_REQ_UPDT.OFFER_REQUEST_ID 
WHERE 1=1 -- AND O_REQ.OFFER_REQUEST_ID  =1677556275
AND O_REQ.DW_CURRENT_VERSION_IND =TRUE AND O_REQ.DW_LOGICAL_DELETE_IND =FALSE
AND O_REQ_S.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_S.DW_LOGICAL_DELETE_IND =FALSE
AND NVL(O_REQ_S.OFFER_REQUEST_STATUS_DSC,'NA') IN ('Draft', 'Submitted', 'Completed', 'Canceled' )
AND O_REQ.PROMOTION_PROGRAM_TYPE_CD  ='BPD' ;