--liquibase formatted sql
--changeset SYSTEM:Offer_Request runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_VIEW_NAME>>;
use schema <<EDM_VIEW_NAME>>.DW_VIEWS;

create or replace view OFFER_REQUEST(
	OFFER_REQUEST_ID COMMENT 'Unique identifer for each offer request created in source system',
	DW_FIRST_EFFECTIVE_DT COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	DELIVERY_CHANNEL_TYPE_CD COMMENT 'Channel through which the offer will be delivered to customers',
	DELIVERY_CHANNEL_TYPE_DSC COMMENT 'values :CC - clip and click , DO-digital only, ET-email campaign',
	OFFER_BANK_TYPE_CD COMMENT 'Type of the offer bank for offer request',
	OFFER_BANK_ID COMMENT 'Identifier of the Offer Bank for offer request',
	OFFER_BANK_NM COMMENT 'Name of the Offer Bank for offer request',
	TEMPLATE_ID COMMENT 'Identifier of the reference template used for the offer request',
	TEMPLATE_NM COMMENT 'Name of the reference template used for the offer request ',
	OFFER_REQUEST_DEPARTMENT_NM COMMENT 'Name of the Department to which offer request belongs to',
	OFFER_NM COMMENT 'Name of the Offer',
	OFFER_REQUEST_DSC COMMENT 'Description of the offer request ',
	CUSTOMER_SEGMENT_INFO_TXT COMMENT 'Customer segment information text ',
	OFFER_ITEM_SIZE_DSC COMMENT 'Description of the item size on the offer',
	VENDOR_PROMOTION_NOPA_START_DT COMMENT 'NOPA start date from when the offer vendor promotion starts',
	VENDOR_PROMOTION_NOPA_END_DT COMMENT 'NOPA End date from when the offer vendor promotion ends',
	VENDOR_PROMOTION_BILLING_OPTION_TYPE_CD COMMENT 'Billing option type code for the vendor promotion of the offer',
	VENDOR_PROMOTION_BILLING_OPTION_TYPE_DSC COMMENT 'Billing option type description for the vendor promotion of the offer',
	VENDOR_PROMOTION_BILLING_OPTION_TYPE_SHORT_DSC COMMENT 'Billing option type short description for the vendor promotion of the offer',
	VENDOR_PROMOTION_NOPA_ASSIGN_STATUS_TYPE_CD COMMENT 'NOPA Assigned status type code of the vendor promotion',
	VENDOR_PROMOTION_NOPA_ASSIGN_STATUS_EFFECTIVE_TS COMMENT 'NOPA Assigned status effective timestamp of the vendor promotion',
	VENDOR_PROMOTION_NOPA_ASSIGN_STATUS_DSC COMMENT 'NOPA Assigned status description of the vendor promotion',
	VENDOR_PROMOTION_ALLOWANCE_TYPE_CD COMMENT 'Allowance type code of the vendor promotion',
	VENDOR_PROMOTION_ALLOWANCE_TYPE_DSC COMMENT 'Allowance type description of the vendor promotion',
	VENDOR_PROMOTION_ALLOWANCE_TYPE_SHORT_DSC COMMENT 'Allowance type short description of the vendor promotion',
	VENDOR_PROMOTION_BILLED_IND COMMENT 'Indicator if vendor promotion can be billed for this offer',
	PROMOTION_PROGRAM_TYPE_CD COMMENT 'Type/Sub type Code of a promotion program.Type could be Meat and …',
	PROMOTION_PROGRAM_TYPE_NM COMMENT 'Type/Sub type Name of a promotion program.Type could be Meat and …',
	ADVERTISEMENT_TYPE_CD COMMENT 'Type code of the advertisement for the offer',
	ADVERTISEMENT_TYPE_DSC COMMENT 'Type description of the advertisement for the offer',
	ADVERTISEMENT_TYPE_SHORT_DSC COMMENT 'Type Short description of the advertisement for the offer',
	TRIGGER_ID COMMENT 'Identifier of the offer request trigger',
	SAVINGS_VALUE_TXT COMMENT 'Savings value of the offer',
	BRAND_INFO_TXT COMMENT 'Brand Information providing the offer',
	DISCLAIMER_TXT COMMENT 'Disclaimer Text for the offer request ',
	IMAGE_ID COMMENT 'Identifier of the Image of item on the offer request',
	DISPLAY_START_DT COMMENT 'Offer Display start date',
	DISPLAY_END_DT COMMENT 'Offer Display end date',
	OFFER_START_DT COMMENT 'Start date of the offer',
	OFFER_END_DT COMMENT 'End date of the offer',
	TEST_START_DT COMMENT 'offer test period start date',
	TEST_END_DT COMMENT 'offer test period end date',
	SOURCE_SYSTEM_ID COMMENT 'Identifier of the source system',
	APPLICATION_ID COMMENT 'Identifier of the application',
	UPDATED_APPLICATION_ID COMMENT 'Identifier of the application updated the offer',
	OFFER_EFFECTIVE_DAY_MONDAY_IND COMMENT 'Indicator if the Offer is effective from Monday',
	OFFER_EFFECTIVE_DAY_TUESDAY_IND COMMENT 'Indicator if the Offer is effective from Tuesday',
	OFFER_EFFECTIVE_DAY_WEDNESDAY_IND COMMENT 'Indicator if the Offer is effective from Wednesday',
	OFFER_EFFECTIVE_DAY_THURSDAY_IND COMMENT 'Indicator if the Offer is effective from Thursday',
	OFFER_EFFECTIVE_DAY_FRIDAY_IND COMMENT 'Indicator if the Offer is effective from Friday',
	OFFER_EFFECTIVE_DAY_SATURDAY_IND COMMENT 'Indicator if the Offer is effective from Saturday ',
	OFFER_EFFECTIVE_DAY_SUNDAY_IND COMMENT 'Indicator if the Offer is effective from Sunday',
	OFFER_EFFECTIVE_START_TM COMMENT 'Offer Effective Start Time ',
	OFFER_EFFECTIVE_END_TM COMMENT 'Offer Effective End Time',
	OFFER_EFFECTIVE_TIME_ZONE_CD COMMENT 'Time Zone code where the offer will be effective',
	OFFER_ITEM_DSC COMMENT 'Description of the item on the offer',
	MANUFACTURER_TYPE_ID COMMENT 'Identifier for the Manufacturer type',
	MANUFACTURER_TYPE_ID_TXT COMMENT 'Text field for storing manufacturer identifier',
	MANUFACTURER_TYPE_SHORT_DSC COMMENT 'Short description of the manufacturer type',
	MANUFACTURER_TYPE_FILE_NM COMMENT 'File name of the manufacturer type',
	MANUFACTURER_TYPE_CREATE_FILE_DT COMMENT 'Date when the request file was created on manufacturer system',
	MANUFACTURER_TYPE_CREATE_FILE_TS COMMENT 'Timestamp when the request file was created on manufacturer system',
	MANUFACTURER_TYPE_FILE_SEQUENCE_NBR COMMENT 'File sequence number of the manufacturer type',
	MANUFACTURER_TYPE_SOURCE_ID COMMENT 'Source Identifier of the manufacturer type',
	MANUFACTURER_TYPE_DESTINATION_ID COMMENT 'Identifier of the Manufacturer on the Destination system',
	MANUFACTURER_TYPE_DSC COMMENT 'Description of the Manufacturer type',
	OFFER_REQUEST_TYPE_CD COMMENT 'Type of the offer request',
	BUSINESS_JUSTIFICATION_TXT COMMENT 'Business justification of the offer',
	OFFER_REQUEST_COMMENT_TXT COMMENT 'Offer request comments text',
	ADDITIONAL_DETAILS_TXT COMMENT 'Additional details of the offer',
	VERSION_QTY COMMENT 'version id generated with in source system UI to identify a store group with offer. One Store Group Version can have multiple type so fs to regroup.',
	TIER_QTY COMMENT 'Tiers quantity for the offer Request',
	PRODUCT_QTY COMMENT 'Offer applicble to products quantity',
	STORE_GROUP_QTY COMMENT 'Offer Request Store group Quantity ',
	CHARGEBACK_DEPARTMENT_ID COMMENT 'Identifier of the chargeback department for the offer',
	ALLOCATION_TYPE_CD COMMENT 'Type of the Allocation on the Offer',
	ALLOCATION_TYPE_DESC COMMENT 'Description of the Allocation on the offer',
	ALLOCATION_TYPE_SHORT_DESC COMMENT 'Short description of the allocation on the offer',
	OFFER_TEMPLATE_STATUS_CD COMMENT 'Template Code for the offer request',
	UPC_QTY_TXT COMMENT 'Range of Upc',
	ECOMM_PROGRAM_TYPE_NM COMMENT 'Name of a Ecomm promotion program type',
	ECOMM_PROGRAM_TYPE_CD COMMENT 'Type/Sub type of a Ecomm promotion program',
	VALID_WITH_OTHER_OFFERS_IND COMMENT 'Promo code can be used (is combinable) with other promo codes',
	VALID_FOR_FIRST_TIME_CUSTOMER_IND COMMENT 'Promo code can only apply on a customers first order',
	AUTO_APPLY_PROMO_IND COMMENT 'Promo code can be auto applied without the customer entering it on the site.',
	OFFER_ELIGIBLE_ORDER_CNT COMMENT 'Count of number of Orderson which promotion is valid/Number of orders or the order number on which the promo ',
	GAMING_VENDOR_NM COMMENT 'Gaming vendor name',
	GAMING_LAND_NM COMMENT 'Gaming land name',
	GAMING_LAND_SPACE_NM COMMENT 'Gaming Land Space Name',
	GAMING_LAND_SPACE_SLOT_NM COMMENT 'Gaming Land Space Slot Name',
	PROMOTION_SUBPROGRAM_TYPE_CD COMMENT 'Sub Program Code',
	OFFER_QUALIFICATION_BEHAVIOR_CD COMMENT 'Offer Qualification Behavior Code',
	INITIAL_SUBSCRIPTION_OFFER_IND COMMENT 'Initial Subscription offer indicator',
	OFFER_TEMPLATE_STATUS_IND COMMENT 'Offer Template Status indicator',
	DYNAMIC_OFFER_IND COMMENT 'Dynamic Offer indicator',
	DAYS_TO_REDEEM_OFFER_CNT COMMENT 'Days to redeem offer count',
	DW_CREATE_TS COMMENT 'The timestamp the record was inserted',
	DW_LAST_UPDATE_TS COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM COMMENT 'The Bod (data source) name of this insert',
	DW_SOURCE_UPDATE_NM COMMENT 'The Bod (data source) name of this update or delete',
	DW_CURRENT_VERSION_IND COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d'
) COMMENT='View For Offer_Request'
 as
select
Offer_Request_Id ,
DW_First_Effective_Dt ,
DW_Last_Effective_Dt ,
Delivery_Channel_Type_Cd ,
Delivery_Channel_Type_Dsc ,
Offer_Bank_Type_Cd ,
Offer_Bank_Id ,
Offer_Bank_Nm ,
Template_Id ,
Template_Nm ,
Offer_Request_Department_Nm ,
Offer_Nm ,
Offer_Request_Dsc ,
Customer_Segment_Info_Txt ,
Offer_Item_Size_Dsc ,
Vendor_Promotion_NOPA_Start_Dt ,
Vendor_Promotion_NOPA_End_Dt ,
Vendor_Promotion_Billing_Option_Type_Cd ,
Vendor_Promotion_Billing_Option_Type_Dsc ,
Vendor_Promotion_Billing_Option_Type_Short_Dsc ,
Vendor_Promotion_NOPA_Assign_Status_Type_Cd ,
Vendor_Promotion_NOPA_Assign_Status_Effective_Ts ,
Vendor_Promotion_NOPA_Assign_Status_Dsc ,
Vendor_Promotion_Allowance_Type_Cd ,
Vendor_Promotion_Allowance_Type_Dsc ,
Vendor_Promotion_Allowance_Type_Short_Dsc ,
Vendor_Promotion_Billed_Ind ,
Promotion_Program_Type_Cd ,
Promotion_Program_Type_Nm ,
Advertisement_Type_Cd ,
Advertisement_Type_Dsc ,
Advertisement_Type_Short_Dsc ,
Trigger_Id ,
Savings_Value_Txt ,
Brand_Info_Txt ,
Disclaimer_Txt ,
Image_Id ,
Display_Start_Dt ,
Display_End_Dt ,
Offer_Start_Dt ,
Offer_End_Dt ,
Test_Start_Dt ,
Test_End_Dt ,
Source_System_Id ,
Application_Id ,
Updated_Application_Id ,
Offer_Effective_Day_Monday_Ind ,
Offer_Effective_Day_Tuesday_Ind ,
Offer_Effective_Day_Wednesday_Ind ,
Offer_Effective_Day_Thursday_Ind ,
Offer_Effective_Day_Friday_Ind ,
Offer_Effective_Day_Saturday_Ind ,
Offer_Effective_Day_Sunday_Ind ,
Offer_Effective_Start_Tm ,
Offer_Effective_End_Tm ,
Offer_Effective_Time_Zone_Cd ,
Offer_Item_Dsc ,
Manufacturer_Type_Id ,
Manufacturer_Type_Id_Txt ,
Manufacturer_Type_Short_Dsc ,
Manufacturer_Type_File_Nm ,
Manufacturer_Type_Create_File_Dt ,
Manufacturer_Type_Create_File_Ts ,
Manufacturer_Type_File_Sequence_Nbr ,
Manufacturer_Type_Source_Id ,
Manufacturer_Type_Destination_Id ,
Manufacturer_Type_Dsc ,
Offer_Request_Type_Cd ,
Business_Justification_Txt ,
Offer_Request_Comment_Txt ,
Additional_Details_Txt ,
Version_Qty ,
Tier_Qty ,
Product_Qty ,
Store_Group_Qty ,
Chargeback_Department_Id ,
Allocation_Type_Cd ,
Allocation_Type_Desc ,
Allocation_Type_Short_Desc ,
Offer_Template_Status_Cd,
UPC_QTY_TXT,
Ecomm_Program_Type_Nm,
Ecomm_Program_Type_Cd,
Valid_With_Other_Offers_Ind ,
Valid_For_First_Time_Customer_Ind ,
Auto_Apply_Promo_Ind ,
Offer_Eligible_Order_CnT ,
Gaming_Vendor_Nm,
Gaming_land_Nm,
Gaming_Land_Space_Nm,
Gaming_Land_Space_Slot_Nm,
Promotion_Subprogram_Type_Cd,
Offer_Qualification_Behavior_Cd,
Initial_Subscription_Offer_Ind,
Offer_Template_Status_Ind,
Dynamic_Offer_Ind,
Days_To_Redeem_Offer_Cnt,
DW_CREATE_TS ,
DW_LAST_UPDATE_TS ,
DW_LOGICAL_DELETE_IND ,
DW_SOURCE_CREATE_NM ,
DW_SOURCE_UPDATE_NM ,
DW_CURRENT_VERSION_IND
From  <<EDM_DB_NAME>>.DW_C_PURCHASING.Offer_Request;
