--liquibase formatted sql
--changeset SYSTEM:Offer_Request_Product_Group runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view OFFER_REQUEST_PRODUCT_GROUP(
	OFFER_REQUEST_ID COMMENT 'Offer_Request_Id',
	USER_INTERFACE_UNIQUE_ID COMMENT 'User_Interface_Unique_Id',
	PRODUCT_GROUP_ID COMMENT 'Product_Group_Id',
	DW_FIRST_EFFECTIVE_DT COMMENT 'DW_First_Effective_Dt',
	DW_LAST_EFFECTIVE_DT COMMENT 'DW_Last_Effective_Dt',
	PRODUCT_GROUP_VERSION_ID COMMENT 'Product_Group_Version_Id',
	DISPLAY_ORDER_NBR COMMENT 'Display_Order_Nbr',
	ITEM_QTY COMMENT 'Item_Qty',
	UNIT_OF_MEASURE_CD COMMENT 'Unit_Of_Measure_Cd',
	UNIT_OF_MEASURE_DSC COMMENT 'Unit_Of_Measure_Dsc',
	UNIT_OF_MEASURE_NM COMMENT 'Unit_Of_Measure_Nm',
	GIFT_CARD_IND COMMENT 'Gift_Card_Ind',
	ANY_PRODUCT_IND COMMENT 'Any_Product_Ind',
	UNIQUE_ITEM_IND COMMENT 'Unique_Item_Ind',
	CONJUNCTION_DSC COMMENT 'Conjunction_Dsc',
	MINIMUM_PURCHASE_AMT COMMENT 'Minimum_Purchase_Amt',
	MAXIMUM_PURCHASE_AMT COMMENT 'Maximum_Purchase_Amt',
	INHERITED_IND COMMENT 'Inherited_Ind',
	EXCLUDED_PRODUCT_GROUP_ID COMMENT 'Excluded_Product_Group_Id',
	EXCLUDED_PRODUCT_GROUP_NM COMMENT 'Excluded_Product_Group_Nm',
	CORPORATE_ITEM_CD COMMENT 'Corporate_Item_Cd',
	REPRESENTATIVE_UPC_CD COMMENT 'Representative_UPC_Cd',
	REPRESENTATIVE_UPC_NBR COMMENT 'Representative_UPC_Nbr',
	REPRESENTATIVE_UPC_TXT COMMENT 'Representative_UPC_Txt',
	REPRESENTATIVE_UPC_DSC COMMENT 'Representative_UPC_Dsc',
	REPRESENTATIVE_STATUS_TYPE_CD COMMENT 'Representative_Status_Type_Cd',
	REPRESENTATIVE_STATUS_TYPE_DSC COMMENT 'Representative_Status_Type_Dsc',
	REPRESENTATIVE_STATUS_TYPE_EFFECTIVE_TS COMMENT 'Representative_Status_Type_Effective_Ts',
	REPRESENTATIVE_STATUS_TYPE_EFFECTIVE_END_DT COMMENT 'Representative_Status_Type_Effective_End_Dt',
	STATUS_REASON_CD COMMENT 'Status_Reason_Cd',
	STATUS_REASON_DSC COMMENT 'Status_Reason_Dsc',
	STATUS_REASON_SHORT_DSC COMMENT 'Status_Reason_Short_Dsc',
	ITEM_OFFER_PRICE_AMT COMMENT 'Item_Offer_Price_Amt',
	ITEM_OFFER_UOM_CD COMMENT 'Item_Offer_UOM_Cd',
	ITEM_OFFER_UOM_NM COMMENT 'Item_Offer_UOM_Nm',
	ITEM_OFFER_EFFECTIVE_START_DT COMMENT 'Item_Offer_Effective_Start_Dt',
	ITEM_OFFER_EFFECTIVE_END_DT COMMENT 'Item_Offer_Effective_End_Dt',
	DW_CREATE_TS COMMENT 'DW_CREATE_TS',
	DW_LAST_UPDATE_TS COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM COMMENT 'DW_SOURCE_CREATE_NM',
	DW_SOURCE_UPDATE_NM COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IND COMMENT 'DW_CURRENT_VERSION_IND'
) COMMENT='View For Offer_Request_Product_Group'
 as
SELECT 
Offer_Request_Id ,
User_Interface_Unique_Id ,
Product_Group_Id ,
DW_First_Effective_Dt ,
DW_Last_Effective_Dt ,
Product_Group_Version_Id ,
Display_Order_Nbr ,
Item_Qty ,
Unit_Of_Measure_Cd ,	
Unit_Of_Measure_Dsc ,	
Unit_Of_Measure_Nm ,
Gift_Card_Ind ,	
Any_Product_Ind	,
Unique_Item_Ind	,
Conjunction_Dsc ,	
Minimum_Purchase_Amt ,
Maximum_Purchase_Amt ,
Inherited_Ind ,
Excluded_Product_Group_Id ,
Excluded_Product_Group_Nm ,
Corporate_Item_Cd ,
Representative_UPC_Cd ,	 
Representative_UPC_Nbr ,	
Representative_UPC_Txt ,
Representative_UPC_Dsc ,
Representative_Status_Type_Cd ,									
Representative_Status_Type_Dsc ,
Representative_Status_Type_Effective_Ts ,
Representative_Status_Type_Effective_End_Dt , 
Status_Reason_Cd ,
Status_Reason_Dsc ,
Status_Reason_Short_Dsc , 
Item_Offer_Price_Amt ,
Item_Offer_UOM_Cd ,
Item_Offer_UOM_Nm ,
Item_Offer_Effective_Start_Dt ,
Item_Offer_Effective_End_Dt ,
DW_CREATE_TS ,
DW_LAST_UPDATE_TS ,
DW_LOGICAL_DELETE_IND ,
DW_SOURCE_CREATE_NM ,
DW_SOURCE_UPDATE_NM ,
DW_CURRENT_VERSION_IND   
FROM EDM_CONFIRMED_PRD.DW_C_PURCHASING.Offer_Request_Product_Group;