--liquibase formatted sql
--changeset SYSTEM:Offer_Request_Sub_Group runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view OFFER_REQUEST_SUB_GROUP(
	GROUP_ID COMMENT 'Group_Id',
	SUB_GROUP_ID COMMENT 'Sub_Group_Id ',
	DW_FIRST_EFFECTIVE_DT COMMENT 'DW_First_Effective_Dt',
	DW_LAST_EFFECTIVE_DT COMMENT 'DW_Last_Effective_Dt',
	OFFER_REQUEST_ID COMMENT 'Offer_Request_Id',
	SUB_GROUP_CD COMMENT 'Sub_Group_Cd',
	SUB_GROUP_NM COMMENT 'Sub_Group_Nm',
	DW_CREATE_TS COMMENT 'DW_CREATE_TS',
	DW_LAST_UPDATE_TS COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM COMMENT 'DW_SOURCE_CREATE_NM ',
	DW_SOURCE_UPDATE_NM COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IND COMMENT 'DW_CURRENT_VERSION_IND'
) COMMENT='View For Offer_Request_Sub_Group'
 as 
Select
Group_Id	,
Sub_Group_Id	,
DW_First_Effective_Dt	,
DW_Last_Effective_Dt	,
Offer_Request_Id	,
Sub_Group_Cd	,
Sub_Group_Nm	,
DW_CREATE_TS	,
DW_LAST_UPDATE_TS	,
DW_LOGICAL_DELETE_IND	,
DW_SOURCE_CREATE_NM	,
DW_SOURCE_UPDATE_NM	,
DW_CURRENT_VERSION_IND	
From EDM_CONFIRMED_PRD.DW_C_PURCHASING.Offer_Request_Sub_Group;