--liquibase formatted sql
--changeset SYSTEM:OFFER_REQUEST_GROUP runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view OFFER_REQUEST_GROUP(
	OFFER_REQUEST_ID COMMENT 'Offer_Request_Id',
	GROUP_ID COMMENT 'GROUP_ID',
	DW_FIRST_EFFECTIVE_DT COMMENT 'DW_FIRST_EFFECTIVE_DT',
	DW_LAST_EFFECTIVE_DT COMMENT 'DW_LAST_EFFECTIVE_DT ',
	GROUP_CD COMMENT 'GROUP_CD',
	GROUP_NM COMMENT 'GROUP_NM ',
	DW_CREATE_TS COMMENT 'DW_CREATE_TS ',
	DW_LAST_UPDATE_TS COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM COMMENT 'DW_SOURCE_CREATE_NM ',
	DW_SOURCE_UPDATE_NM COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IND COMMENT 'DW_CURRENT_VERSION_IND'
) COMMENT='View For OFFER_REQUEST_GROUP'
 as 
Select 
Offer_Request_Id
,GROUP_ID
,DW_FIRST_EFFECTIVE_DT
,DW_LAST_EFFECTIVE_DT
,GROUP_CD
,GROUP_NM
,DW_CREATE_TS
,DW_LAST_UPDATE_TS
,DW_LOGICAL_DELETE_IND
,DW_SOURCE_CREATE_NM
,DW_SOURCE_UPDATE_NM
,DW_CURRENT_VERSION_IND
From EDM_CONFIRMED_PRD.DW_C_PURCHASING.OFFER_REQUEST_GROUP;