--liquibase formatted sql
--changeset SYSTEM:Offer_Request_POD_Display_Image runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view OFFER_REQUEST_POD_DISPLAY_IMAGE(
	OFFER_REQUEST_ID COMMENT 'Offer_Request_Id',
	USER_INTERFACE_UNIQUE_ID COMMENT 'User_Interface_Unique_Id',
	POD_IMAGE_TYPE_CD COMMENT 'POD_Image_Type_Cd',
	DW_FIRST_EFFECTIVE_DT COMMENT 'DW_First_Effective_Dt',
	DW_LAST_EFFECTIVE_DT COMMENT 'DW_Last_Effective_Dt',
	POD_IMAGE_ID COMMENT 'POD_Image_Id',
	DW_CREATE_TS COMMENT 'DW_CREATE_TS',
	DW_LAST_UPDATE_TS COMMENT 'DW_LAST_UPDATE_TS',
	DW_LOGICAL_DELETE_IND COMMENT 'DW_LOGICAL_DELETE_IND',
	DW_SOURCE_CREATE_NM COMMENT 'DW_SOURCE_CREATE_NM',
	DW_SOURCE_UPDATE_NM COMMENT 'DW_SOURCE_UPDATE_NM',
	DW_CURRENT_VERSION_IN COMMENT 'DW_CURRENT_VERSION_IN'
) COMMENT='View For Offer_Request_POD_Display_Image'
 as
SELECT 
  Offer_Request_Id ,
  User_Interface_Unique_Id ,
  POD_Image_Type_Cd ,
  DW_First_Effective_Dt ,
  DW_Last_Effective_Dt ,
  POD_Image_Id ,
  DW_CREATE_TS ,
  DW_LAST_UPDATE_TS ,
  DW_LOGICAL_DELETE_IND ,
  DW_SOURCE_CREATE_NM ,
  DW_SOURCE_UPDATE_NM ,
  DW_CURRENT_VERSION_IND
FROM EDM_CONFIRMED_PRD.DW_C_PURCHASING.Offer_Request_POD_Display_Image;