--liquibase formatted sql
--changeset SYSTEM:OFFER_BANK runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_PRD;
use schema EDM_VIEWS_PRD.DW_VIEWS;

create or replace view OFFER_BANK(
	OFFER_REQUEST_ID COMMENT 'Offer Request Identifier',
	MOB_ID COMMENT 'Master Offer Bank Identifier',
	OFFER_START_DATE COMMENT 'Offer Start Date',
	OFFER_END_DATE COMMENT 'Offer End Date',
	REGION_ID COMMENT 'Region unique identifier',
	PERIOD_ID COMMENT 'Year and Week of Year Identifier i.e., 202103',
	PROMO_WEEK_ID COMMENT 'Promotion Week identifier i.e., 202141',
	PERIOD COMMENT 'Period identifier, combination of year and 3-weeks i.e., 21_wk13_16',
	PROGRAM_TYPE COMMENT 'Offer Program Type (i.e., Employee, Business Unit)',
	PROGRAM_SUBTYPE COMMENT 'Offer Program Subcategory (Division Request, Elite Offer)',
	OFFER_ID COMMENT 'Unique Offer Identifier',
	GROUP_ID COMMENT 'Product Group Identifier ',
	REP_UPC COMMENT 'Universal Product Code ',
	CAT_ID COMMENT 'Product Category Identifier',
	HEADLINE_1 COMMENT 'Headline Product Name i.e., Signature Cafe',
	HEADLINE_2 COMMENT 'Secondary Product Name i.e., Chicken Tenders',
	OFFER_DESCRIPTION COMMENT 'Full Product Name i.e., Signature Café Chicken Tenders',
	PRICE_TEXT COMMENT 'Price of Product',
	LAST_UPDATE COMMENT 'Last Updated date',
	OFFER_RANK COMMENT 'Offer Rank Priority ',
	TEMPLATE_ID COMMENT 'Template Identifier',
	OFFER_TYPE COMMENT 'Type of Offer, is it a Personalize Deal, Store Coupon, Rewards , etc.',
	OFFER_STATUS COMMENT 'Status of offer, is it Deployed, Draft etc. ',
	ALLOCATION_CODE COMMENT 'Allocation Price Code',
	ALLOCATION_NAME COMMENT 'Name of Allocation Price Code ',
	POD_FLAG COMMENT 'Indicates whether offer will be clippable',
	PROGRAM_CODE COMMENT '3 letter Program Code, SPD-Special Personalize Deals',
	ADDITIONAL_DETAILS_TXT COMMENT 'Additional Comments  '
) COMMENT='VIEW FOR OFFER_BANK'
 as

SELECT OFFER_REQUEST_ID 
,MOB_ID 
,OFFER_START_DATE
,OFFER_END_DATE
,REGION_ID
,PERIOD_ID
,PROMO_WEEK_ID
,PERIOD
,PROGRAM_TYPE
,PROGRAM_SUBTYPE
,OFFER_ID
,GROUP_ID
,REP_UPC
,CAT_ID
,HEADLINE_1
,HEADLINE_2
,OFFER_DESCRIPTION
,PRICE_TEXT
,LAST_UPDATE
,OFFER_RANK
,TEMPLATE_ID
,OFFER_TYPE
,OFFER_STATUS
,ALLOCATION_CODE
,ALLOCATION_NAME
,POD_FLAG
,PROGRAM_CODE
,ADDITIONAL_DETAILS_TXT
FROM (
SELECT 
O_OMS.OFFER_REQUEST_ID 
,O_REQ.OFFER_BANK_ID    AS MOB_ID 
,O_REQ.OFFER_START_DT AS OFFER_START_DATE
,O_REQ.OFFER_END_DT AS OFFER_END_DATE
,O_REQ_REG.REGION_ID AS REGION_ID
,O_REQ_PPT.PROMOTION_PERIOD_ID AS PERIOD_ID
,O_REQ_PPT.PROMOTION_WEEK_ID AS PROMO_WEEK_ID
,O_REQ_PPT.PROMOTION_PERIOD_NM AS PERIOD
,UPPER(O_REQ_PPRG.PROGRAM_TYPE_CD) AS PROGRAM_TYPE
,O_REQ_PPRG.PROGRAM_SUB_TYPE_CD AS PROGRAM_SUBTYPE
,ORO.OFFER_EXTERNAL_ID AS OFFER_ID
,SMIC_GROUP_CD AS GROUP_ID
,ORPG.REPRESENTATIVE_UPC_NBR AS REP_UPC
,CT.CAT_ID AS CAT_ID
,OROS.POD_HEADLINE_TXT AS HEADLINE_1
,OROS.POD_HEADLINE_SUB_TXT AS HEADLINE_2
,OROS.POD_OFFER_DSC AS OFFER_DESCRIPTION
,OROS.POD_PRICE_INFO_TXT AS PRICE_TEXT
,TO_CHAR(max(ORU.UPDATE_TS), 'MM/DD/YYYY') As LAST_UPDATE
,ROW_NUMBER() OVER (PARTITION BY O_REQ_PPT.PROMOTION_WEEK_ID, O_REQ_PPRG.PROGRAM_TYPE_CD,   O_REQ_REG.REGION_ID ORDER BY O_REQ.OFFER_BANK_ID) AS OFFER_RANK
,O_REQ.TEMPLATE_ID
,O_REQ.OFFER_REQUEST_TYPE_CD AS OFFER_TYPE
,O_OMS.OFFER_STATUS_DSC AS OFFER_STATUS
,O_OMS.ALLOCATION_CD AS ALLOCATION_CODE
,O_OMS.ALLOCATION_NM  AS ALLOCATION_NAME
,O_OMS.IS_PRIMARY_POD_OFFER_IND AS POD_FLAG
,O_REQ.PROMOTION_PROGRAM_TYPE_CD AS PROGRAM_CODE
,O_REQ.ADDITIONAL_DETAILS_TXT AS ADDITIONAL_DETAILS_TXT
,ROW_NUMBER() OVER (PARTITION BY O_OMS.EXTERNAL_OFFER_ID ORDER BY O_REQ_PPT.DW_CREATE_TS DESC) RN
FROM "EDM_CONFIRMED_PRD"."DW_C_PRODUCT"."OMS_OFFER" O_OMS
JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST" O_REQ ON O_REQ.OFFER_REQUEST_ID = O_OMS.OFFER_REQUEST_ID 
LEFT JOIN  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_GROUP" ORG ON O_REQ.OFFER_REQUEST_ID = ORG.OFFER_REQUEST_ID 
LEFT JOIN  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_OFFER_SPECIFICATION" OROS ON O_REQ.OFFER_REQUEST_ID = OROS.OFFER_REQUEST_ID 
JOIN  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_OFFER" ORO ON ORO.OFFER_REQUEST_ID = OROS.OFFER_REQUEST_ID  AND O_REQ.OFFER_REQUEST_ID =OROS.OFFER_REQUEST_ID  AND  O_OMS.EXTERNAL_OFFER_ID = ORO.OFFER_EXTERNAL_ID
JOIN  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PRODUCT_GROUP" ORPG ON ORPG.OFFER_REQUEST_ID  =O_REQ.OFFER_REQUEST_ID  
JOIN  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_REGION" O_REQ_REG ON O_REQ.OFFER_REQUEST_ID = O_REQ_REG.OFFER_REQUEST_ID
JOIN  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PROMOTION_PERIOD_TYPE" O_REQ_PPT ON  O_REQ.OFFER_REQUEST_ID = O_REQ_PPT.OFFER_REQUEST_ID
LEFT JOIN (select OFFER_REQUEST_ID,b.CORPORATE_ITEM_CD, SMIC_GROUP_CD,SMIC_CATEGORY_CD ,
           CASE WHEN  LEN(TO_CHAR(SMIC_CATEGORY_CD))= 1 THEN  CONCAT(TO_CHAR(b.SMIC_GROUP_CD) ,  CONCAT('0',TO_CHAR(SMIC_CATEGORY_CD)  ) ) 
           ELSE CONCAT(TO_CHAR(b.SMIC_GROUP_CD) ,  TO_CHAR(SMIC_CATEGORY_CD) ) END AS CAT_ID
           from  "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PRODUCT_GROUP"  a
           JOIN (SELECT CORPORATE_ITEM_CD,SMIC_GROUP_CD, SMIC_CATEGORY_CD,ROW_NUMBER() OVER ( partition by CORPORATE_ITEM_CD ORDER BY DW_CREATE_TS DESC ) RN FROM "EDM_CONFIRMED_PRD"."DW_C_PRODUCT"."CORPORATE_ITEM" )      b on a.CORPORATE_ITEM_CD = b.CORPORATE_ITEM_CD 
            WHERE RN = 1 
          ) CT ON CT.OFFER_REQUEST_ID = O_REQ.OFFER_REQUEST_ID  
JOIN  ( select OFFER_REQUEST_ID, PROGRAM_TYPE_CD , PROGRAM_SUB_TYPE_CD , DW_CURRENT_VERSION_IND , DW_LOGICAL_DELETE_IND, 
       ROW_NUMBER() OVER (PARTITION BY OFFER_REQUEST_ID ORDER BY  DW_CREATE_TS DESC) RN1
from "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_PROMOTION_PROGRAM_TYPE" 
  ) O_REQ_PPRG ON  O_REQ.OFFER_REQUEST_ID = O_REQ_PPRG.OFFER_REQUEST_ID AND RN1 =1
JOIN "EDM_CONFIRMED_PRD"."DW_C_PURCHASING"."OFFER_REQUEST_USER_UPDATE" ORU ON O_REQ.OFFER_REQUEST_ID  = ORU.OFFER_REQUEST_ID
WHERE O_REQ.OFFER_BANK_ID  IS NOT NULL
AND  O_OMS.OFFER_STATUS_CD IN ( 'DE','CN','PU')
AND O_REQ.PROMOTION_PROGRAM_TYPE_CD IN('SPD', 'GR', 'BPD')
AND O_OMS.DW_CURRENT_VERSION_IND =TRUE AND O_OMS.DW_LOGICAL_DELETE_IND =FALSE
AND O_REQ.DW_CURRENT_VERSION_IND =TRUE AND O_REQ.DW_LOGICAL_DELETE_IND =FALSE
AND OROS.DW_CURRENT_VERSION_IND =TRUE AND OROS.DW_LOGICAL_DELETE_IND =FALSE
AND ORO.DW_CURRENT_VERSION_IND =TRUE AND ORO.DW_LOGICAL_DELETE_IND =FALSE
AND ORPG.DW_CURRENT_VERSION_IND =TRUE AND ORPG.DW_LOGICAL_DELETE_IND =FALSE
AND O_REQ_REG.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_REG.DW_LOGICAL_DELETE_IND =FALSE
AND O_REQ_PPT.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_PPT.DW_LOGICAL_DELETE_IND =FALSE
AND O_REQ_PPRG.DW_CURRENT_VERSION_IND =TRUE AND O_REQ_PPRG.DW_LOGICAL_DELETE_IND =FALSE
AND ORU.DW_CURRENT_VERSION_IND =TRUE AND ORU.DW_LOGICAL_DELETE_IND =FALSE
GROUP BY 
O_OMS.OFFER_REQUEST_ID 
,O_OMS.EXTERNAL_OFFER_ID
,O_OMS.ALLOCATION_CD
,O_OMS.ALLOCATION_NM
,O_OMS.OFFER_STATUS_DSC
,O_REQ.TEMPLATE_ID
,O_REQ.OFFER_REQUEST_TYPE_CD
,O_REQ.OFFER_BANK_ID
,O_REQ.OFFER_START_DT
,O_REQ.OFFER_END_DT
,O_REQ.ADDITIONAL_DETAILS_TXT
,O_REQ_REG.REGION_ID 
,O_REQ_PPT.PROMOTION_PERIOD_NM
,O_REQ_PPT.PROMOTION_PERIOD_ID 
,O_REQ_PPT.PROMOTION_WEEK_ID
,O_REQ_PPRG.PROGRAM_TYPE_CD 
,O_REQ_PPRG.PROGRAM_SUB_TYPE_CD
,SMIC_GROUP_CD
,ORO.OFFER_EXTERNAL_ID
,ORPG.REPRESENTATIVE_UPC_CD
,OROS.POD_HEADLINE_TXT
,OROS.POD_HEADLINE_SUB_TXT
,OROS.POD_OFFER_DSC
,CT.CAT_ID
,OROS.POD_PRICE_INFO_TXT
,O_OMS.IS_PRIMARY_POD_OFFER_IND
,O_REQ.PROMOTION_PROGRAM_TYPE_CD
,ORPG.REPRESENTATIVE_UPC_NBR
,O_REQ_PPT.DW_CREATE_TS
)
WHERE RN = 1;