--liquibase formatted sql
--changeset SYSTEM:SP_StoreGroup_To_BIM_load_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PRODUCT;

CREATE OR REPLACE TASK SP_STOREGROUP_TO_BIM_LOAD_TASK
WAREHOUSE='PROD_INGESTION_BIG_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_R_PRODUCT.StoreGroup_Flat_R_STREAM')
AS CALL SP_STOREGROUP_TO_BIM_LOAD();

ALTER TASK SP_STOREGROUP_TO_BIM_LOAD_TASK RESUME;
