--liquibase formatted sql
--changeset SYSTEM:EPISODIC_CUSTOMMETRICS_FLAT_R_STREAM runOnChange:true splitStatements:false OBJECT_TYPE:STREAM
use database EDM_REFINED_PRD;
use schema DW_APPL;

Create or replace stream DW_APPL.EPISODIC_CUSTOMMETRICS_FLAT_R_STREAM ON TABLE EDM_REFINED_PRD.DW_R_LOYALTY.EPISODIC_CUSTOMMETRICS_FLAT;