--liquibase formatted sql
--changeset SYSTEM:SP_ONE_TAG_CAROUSEL_TO_BIM_LOAD runOnChange:true splitStatements:false OBJECT_TYPE:SP
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_APPL;

DROP VIEW <<EDM_DB_NAME_VIEWS>>.<<EDM_SCHEMA_VIEWS>>.ONE_TAG_CLICK_STREAM_VISIT;
DROP TABLE EDM_CONFIRMED_<<ENV>>.DW_C_STAGE.ONE_TAG_CLICK_STREAM_VISIT_WRK;