--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_OPERATING_SYSTEM runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_USER_ACTIVITY;

DELETE FROM EDM_CONFIRMED_<<ENV>>.DW_C_USER_ACTIVITY.CLICK_STREAM_EVENT_MASTER;
DELETE FROM EDM_CONFIRMED_<<ENV>>.DW_C_USER_ACTIVITY.CLICK_STREAM_VISITOR;
DELETE FROM EDM_CONFIRMED_<<ENV>>.DW_C_USER_ACTIVITY.CLICK_STREAM_PAGE_DETAIL;
DELETE FROM EDM_CONFIRMED_<<ENV>>.DW_C_USER_ACTIVITY.CLICK_STREAM_OPERATING_SYSTEM_DETAIL;
DELETE FROM EDM_REFINED_<<ENV>>.DW_R_USER_ACTIVITY.ONE_TAG_OTHER;
insert into EDM_REFINED_<<ENV>>.DW_R_USER_ACTIVITY.ONE_TAG_OTHER select * from EDM_REFINED_QA.DW_R_USER_ACTIVITY.ONE_TAG_OTHER_BKP_12182023;
