--liquibase formatted sql
--changeset SYSTEM:ONETAG_PRODUCT_IMPRESSION runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database EDM_ANALYTICS_<<ENV>>;
use schema DW_DIGITAL_EXP;

DROP TABLE IF EXISTS EDM_ANALYTICS_<<ENV>>.DW_DIGITAL_EXP.ONETAG_PRODUCT_IMPRESSION;
DROP VIEW IF EXISTS EDM_VIEWS_<<ENV>>.DW_VIEWS.ONETAG_PRODUCT_IMPRESSION;
