--liquibase formatted sql
--changeset SYSTEM:CUSTOMER_SESSION runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_USER_ACTIVITY;

ALTER TABLE CUSTOMER_SESSION_PAGE RENAME TO CLICK_STREAM_PAGE_DETAIL;
ALTER TABLE CUSTOMER_SESSION_OPERATING_SYSTEM RENAME TO CLICK_STREAM_OPERATING_SYSTEM_DETAIL;
ALTER TABLE CUSTOMER_SESSION_USER RENAME TO CLICK_STREAM_VISITOR;
ALTER TABLE CUSTOMER_SESSION_IMPRESSION RENAME TO CLICK_STREAM_IMPRESSIONS;
ALTER TABLE CUSTOMER_SESSION_EVENT_MASTER RENAME TO CLICK_STREAM_EVENT_MASTER;