--liquibase formatted sql
--changeset SYSTEM:CUSTOMER_SESSION runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_USER_ACTIVITY;

ALTER TABLE CLICK_STREAM_PAGE_DETAIL RENAME TO CUSTOMER_SESSION_PAGE;
ALTER TABLE CLICK_STREAM_OPERATING_SYSTEM_DETAIL RENAME TO CUSTOMER_SESSION_OPERATING_SYSTEM;
ALTER TABLE CLICK_STREAM_VISITOR RENAME TO CUSTOMER_SESSION_VISITOR;
ALTER TABLE CLICK_STREAM_IMPRESSIONS RENAME TO CUSTOMER_SESSION_IMPRESSION;
ALTER TABLE CLICK_STREAM_EVENT_MASTER RENAME TO CUSTOMER_SESSION_EVENT_MASTER;