--liquibase formatted sql
--changeset SYSTEM:EDM_WH_CONFIG_TBL runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_REFINED_<<ENV>>;
use schema DW_R_MASTERDATA;

delete from EDM_WH_CONFIG_TBL where TABLE_NAME='CLICK_STREAM_OTHER';

insert into EDM_WH_CONFIG_TBL
(TABLE_NAME,RECORD_COUNT_XSMALL_WH,RECORD_COUNT_MEDIUM_WH,RECORD_COUNT_LARGE_WH,RECORD_COUNT_XLARGE_WH)
values('CLICK_STREAM_OTHER','100000','1000000','5000000','10000000');

delete from EDM_WH_CONFIG_TBL where TABLE_NAME='CLICK_STREAM_EVENT_MASTER';

insert into EDM_WH_CONFIG_TBL
(TABLE_NAME,RECORD_COUNT_XSMALL_WH,RECORD_COUNT_MEDIUM_WH,RECORD_COUNT_LARGE_WH,RECORD_COUNT_XLARGE_WH)
values('CLICK_STREAM_EVENT_MASTER','100000','1000000','5000000','10000000');