--liquibase formatted sql
--changeset SYSTEM:ONE_TAG_OTHER runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

use database <<EDM_DB_R_NAME>>;
use schema DW_R_USER_ACTIVITY;

CREATE OR REPLACE TABLE ONE_TAG_OTHER
(	event_hr   NUMBER
,	event_id	VARCHAR
, 	event_subevent	VARCHAR
,   eventtime	timestamp
, 	error_id	VARCHAR
, 	error_feature	VARCHAR
, 	error_msg	VARCHAR
, 	rewards_id	VARCHAR
, 	rewards_redeemed	VARCHAR
, 	coupon_type	VARCHAR
, 	coupon_name	VARCHAR
, 	coupon_id	VARCHAR
, 	coupon_clipmthd	VARCHAR
, 	coupon_clipcnt	VARCHAR
, 	coupon_savings	VARCHAR
, 	coupon_sku	VARCHAR
, 	coupon_carouselsec	VARCHAR
, 	search_type	VARCHAR
, 	search_filter	VARCHAR
, 	search_orderby	VARCHAR
, 	search_offset	NUMBER
, 	search_completionattrtoken	VARCHAR
, 	search_selposition	NUMBER
, 	search_apisearchterm	VARCHAR
, 	search_tst	VARCHAR
, 	search_asf	VARCHAR
, 	search_tfc	VARCHAR
, 	search_ist	VARCHAR
, 	search_rescnt	VARCHAR
, 	modal_action	VARCHAR
, 	modal_msg	VARCHAR
, 	link_name	VARCHAR
, 	productinfo_pid	VARCHAR
, 	productinfo_pname	VARCHAR
, 	productinfo_fname	VARCHAR
, 	productinfo_units	NUMBER
, 	productinfo_utyp	VARCHAR
, 	productinfo_ppunit	VARCHAR
, 	productinfo_lp	VARCHAR
, 	productinfo_carouselsec	VARCHAR
, 	productinfo_bp	VARCHAR
, 	productinfo_ptype	VARCHAR
, 	productinfo_cpnflg	VARCHAR
, 	productinfo_cpnclpd	VARCHAR
, 	productinfo_cpnid	VARCHAR
, 	productinfo_cpnapld	VARCHAR
, 	productinfo_aid	VARCHAR
, 	productinfo_upc	VARCHAR
, 	productinfo_pfmdtl	VARCHAR
, 	productinfo_ics	boolean
, 	productinfo_mto	VARCHAR
, 	productinfo_deptnam	VARCHAR
, 	productinfo_lbs	VARCHAR
, 	productinfo_each	VARCHAR
, 	productinfo_aisle	VARCHAR
, 	productinfo_shelf	VARCHAR
, 	productinfo_offtyp	VARCHAR
, 	productinfo_offtext	VARCHAR
, 	productinfo_carouselsz	NUMBER
, 	productinfo_isrcmnd	VARCHAR
, 	productinfo_iqn	VARCHAR
, 	productinfo_iv	VARCHAR
, 	productinfo_sellerid	VARCHAR
, 	productinfo_sellernam	VARCHAR
, 	pagefilter_filtyp	VARCHAR
, 	pagefilter_filsel	VARCHAR
, 	pagefilter_sortsel	VARCHAR
, 	pagefilter_topnav	VARCHAR
, 	pagefilter_carousel	VARCHAR
, 	pagefilter_adaflg	VARCHAR
, 	pagefilter_rtyp	VARCHAR
, 	pagefilter_placement	VARCHAR
, 	pagefilter_fpdismon	VARCHAR
, 	pagefilter_premslots	VARCHAR
, 	pagefilter_promocode	VARCHAR
, 	pagefilter_mtyp	VARCHAR
, 	pagefilter_subsfunnel	VARCHAR
, 	cart_iswysiwygenabled	boolean
, 	cart_savings_ccsav	VARCHAR
, 	cart_savings_j4usav	VARCHAR
, 	cart_savings_rwdsav	VARCHAR
, 	cart_savings_empsav	VARCHAR
, 	cart_savings_pcsav	VARCHAR
, 	cart_savings_catinvalidid	VARCHAR
, 	cart_savings_catinvalidname	VARCHAR
, 	cart_savings_catinvalidnone	VARCHAR
, 	cart_savings_ttlsav	VARCHAR
, 	cart_savings_totcpns	NUMBER
, 	cart_savings_cpnsclip	NUMBER
, 	cart_transaction_ordid	VARCHAR
, 	cart_transaction_paymthd	VARCHAR
, 	cart_transaction_dlvtime	VARCHAR
, 	cart_transaction_dlvwin	VARCHAR
, 	cart_transaction_dlvst	VARCHAR
, 	cart_transaction_shipfee	VARCHAR
, 	cart_transaction_servcfee	VARCHAR
, 	cart_transaction_taxes	VARCHAR
, 	cart_transaction_fuelsur	VARCHAR
, 	cart_transaction_subttl	NUMBER
, 	cart_transaction_trev	VARCHAR
, 	cart_transaction_tmode	VARCHAR
, 	cart_transaction_rev	VARCHAR
, 	cart_transaction_ordver	VARCHAR
, 	cart_transaction_uniqueorderflag	NUMBER
, 	cart_transaction_subttlwinecart_sellerid	VARCHAR
, 	cart_transaction_subttlwinecart_subtotal	NUMBER
, 	cart_cartinfo_cid	VARCHAR
, 	cart_cartinfo_totunits	VARCHAR
, 	cart_cartinfo_ctype	VARCHAR
, 	cart_cartinfo_ismfc	VARCHAR
, 	cart_cartinfo_mfcunavcnt	VARCHAR
, 	cart_cartinfo_acrt	VARCHAR
, 	user_uuid	VARCHAR
, 	user_shopzc	VARCHAR
, 	user_j4uzc	VARCHAR
, 	user_dlvbnr	VARCHAR
, 	user_dlvpre	VARCHAR
, 	user_picloc	VARCHAR
, 	user_dlvcomb	VARCHAR
, 	user_ssid	VARCHAR
, 	user_j4usid	VARCHAR
, 	user_loginsts	VARCHAR
, 	user_ccn	VARCHAR
, 	user_hhid	VARCHAR
, 	user_utype	VARCHAR
, 	user_custid	VARCHAR
, 	user_substs	VARCHAR
, 	user_subdate	VARCHAR
, 	user_jrnsts	VARCHAR
, 	user_addtype	VARCHAR
, 	user_type	VARCHAR
, 	user_custsts	VARCHAR
, 	user_ordcnt	VARCHAR
, 	user_loctck	VARCHAR
, 	user_datalc	boolean
, 	user_odrsts	VARCHAR
, 	user_clientua	VARCHAR
, 	user_absvisitorid	VARCHAR
, 	user_adobevisitorid	VARCHAR
, 	user_sessionid	VARCHAR
, 	user_cookiepref	VARCHAR
, 	user_emailoptin	VARCHAR
, 	user_smsoptin	VARCHAR
, 	user_cameraallowed	VARCHAR
, 	user_notificationallowed	VARCHAR
, 	user_locationsharing	VARCHAR
, 	user_os	VARCHAR
, 	user_ostype	VARCHAR
, 	user_device	VARCHAR
, 	page_pgname	VARCHAR
, 	page_channel	VARCHAR
, 	page_bnr	VARCHAR
, 	page_ss1	VARCHAR
, 	page_ss2	VARCHAR
, 	page_ss3	VARCHAR
, 	page_ss4	VARCHAR
, 	page_purl	VARCHAR
, 	page_platform	VARCHAR
, 	page_rurl	VARCHAR
, 	page_tp	VARCHAR
, 	page_pt	VARCHAR
, 	page_sid	VARCHAR
, 	page_sitetp	VARCHAR
, 	page_appver	VARCHAR
, 	event_name	VARCHAR
, 	global_attrtoken	VARCHAR
 	) Change_Tracking = TRUE;
