--liquibase formatted sql
--changeset SYSTEM:ONETAG_PRODUCT_IMPRESSION runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_ANALYTICS_<<ENV>>;
use schema DW_DIGITAL_EXP;

CREATE TRANSIENT TABLE ONETAG_PRODUCT_IMPRESSION (
					APPLICATION_DETAIL_TXT	VARCHAR	NULL,
					BASE_PRODUCT_NBR	NUMBER	NOT NULL,
					CAROUSEL_NM	VARCHAR	NULL,
					CLUB_CARD_NBR	VARCHAR	NULL,
					EVENT_ID VARCHAR NOT NULL,	
					HOUSEHOLD_ID	VARCHAR	NULL,
					MODEL_ID_TXT	VARCHAR	NULL,
					PRODUCT_FINDING_METHOD_DSC	VARCHAR	NULL,
					PAGE_NM VARCHAR NULL,
					PRODUCT_SEEN_IND	BOOLEAN	NULL,
					PRODUCT_SEEN_TS	TIMESTAMP	NULL,
					PRODUCTS_SEEN_IN_CAROUSEL_IND	BOOLEAN	NULL,
					RETAIL_CUSTOMER_UUID	VARCHAR	NULL,
					ROW_LOCATION_CD	VARCHAR	NULL,
					SLOT_LOCATION_CD	VARCHAR	NULL,
					SESSION_ID	VARCHAR	NOT NULL,
					SESSION_SEQUENCE_NBR	NUMBER	NOT NULL,
					COOKIE_PREFERENCE_CD	VARCHAR	NULL,
					DW_LOGICAL_DELETE_IND	BOOLEAN	NULL,
					DW_CURRENT_VERSION_IND	BOOLEAN	NULL,
					DW_CREATE_TS	TIMESTAMP	NULL,
					DW_LAST_UPDATE_TS	TIMESTAMP	NULL
);
					
