--liquibase formatted sql
--changeset SYSTEM:CUSTOMER_SESSION_OPERATING_SYSTEM runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database EDM_CONFIRMED_<<ENV>>;
use schema DW_C_USER_ACTIVITY;

create TABLE CUSTOMER_SESSION_OPERATING_SYSTEM (
	OPERATING_SYSTEM_INTEGRATION_ID INTEGER NOT NULL,
	OPERATING_SYSTEM_CD VARCHAR NULL,
	OPERATING_SYSTEM_TYPE_CD VARCHAR NULL,
	PLATFORM_CD VARCHAR NULL,
	DW_CREATE_TS TIMESTAMP NULL,
	DW_LAST_UPDATE_TS TIMESTAMP NULL,
	DW_LOGICAL_DELETE_IND BOOLEAN NULL,
	DW_SOURCE_CREATE_NM VARCHAR(255) NULL,
	DW_SOURCE_UPDATE_NM VARCHAR(255) NULL,
	DW_CURRENT_VERSION_IND BOOLEAN NULL 
);
