--liquibase formatted sql
--changeset SYSTEM:ONE_TAG_OTHER runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_DB_NAME_VIEWS>>;
use schema <<EDM_SCHEMA_VIEWS>>;

CREATE OR REPLACE VIEW  ONE_TAG_OTHER
(	
 	event_id
, 	event_subevent
,   event_time
,   error_id
, 	error_feature
, 	error_msg
, 	rewards_id
, 	rewards_redeemed
, 	coupon_type
, 	coupon_name
, 	coupon_id
, 	coupon_clipmthd
, 	coupon_clipcnt
, 	coupon_savings
, 	coupon_sku
, 	coupon_carouselsec
, 	search_type
, 	search_filter
, 	search_orderby
, 	search_offset
, 	search_completionattrtoken
, 	search_selposition
, 	search_apisearchterm
, 	search_tst
, 	search_asf
, 	search_tfc
, 	search_ist
, 	search_rescnt
, 	modal_action
, 	modal_msg
, 	link_name
, 	productinfo_pid
, 	productinfo_pname
, 	productinfo_fname
, 	productinfo_units
, 	productinfo_utyp
, 	productinfo_ppunit
, 	productinfo_lp
, 	productinfo_carouselsec
, 	productinfo_bp
, 	productinfo_ptype
, 	productinfo_cpnflg
, 	productinfo_cpnclpd
, 	productinfo_cpnid
, 	productinfo_cpnapld
, 	productinfo_aid
, 	productinfo_upc
, 	productinfo_pfmdtl
, 	productinfo_ics
, 	productinfo_mto
, 	productinfo_deptnam
, 	productinfo_lbs
, 	productinfo_each
, 	productinfo_aisle
, 	productinfo_shelf
, 	productinfo_offtyp
, 	productinfo_offtext
, 	productinfo_carouselsz
, 	productinfo_isrcmnd
, 	productinfo_iqn
, 	productinfo_iv
, 	productinfo_sellerid
, 	productinfo_sellernam
, 	pagefilter_filtyp
, 	pagefilter_filsel
, 	pagefilter_sortsel
, 	pagefilter_topnav
, 	pagefilter_carousel
, 	pagefilter_adaflg
, 	pagefilter_rtyp
, 	pagefilter_placement
, 	pagefilter_fpdismon
, 	pagefilter_premslots
, 	pagefilter_promocode
, 	pagefilter_mtyp
, 	pagefilter_subsfunnel
, 	cart_iswysiwygenabled
, 	cart_savings_ccsav
, 	cart_savings_j4usav
, 	cart_savings_rwdsav
, 	cart_savings_empsav
, 	cart_savings_pcsav
, 	cart_savings_catinvalidid
, 	cart_savings_catinvalidname
, 	cart_savings_catinvalidnone
, 	cart_savings_ttlsav
, 	cart_savings_totcpns
, 	cart_savings_cpnsclip
, 	cart_transaction_ordid
, 	cart_transaction_paymthd
, 	cart_transaction_dlvtime
, 	cart_transaction_dlvwin
, 	cart_transaction_dlvst
, 	cart_transaction_shipfee
, 	cart_transaction_servcfee
, 	cart_transaction_taxes
, 	cart_transaction_fuelsur
, 	cart_transaction_subttl
, 	cart_transaction_trev
, 	cart_transaction_tmode
, 	cart_transaction_rev
, 	cart_transaction_ordver
, 	cart_transaction_uniqueorderflag
, 	cart_transaction_subttlwinecart_sellerid
, 	cart_transaction_subttlwinecart_subtotal
, 	cart_cartinfo_cid
, 	cart_cartinfo_totunits
, 	cart_cartinfo_ctype
, 	cart_cartinfo_ismfc
, 	cart_cartinfo_mfcunavcnt
, 	cart_cartinfo_acrt
, 	user_uuid
, 	user_shopzc
, 	user_j4uzc
, 	user_dlvbnr
, 	user_dlvpre
, 	user_picloc
, 	user_dlvcomb
, 	user_ssid
, 	user_j4usid
, 	user_loginsts
, 	user_ccn
, 	user_hhid
, 	user_utype
, 	user_custid
, 	user_substs
, 	user_subdate
, 	user_jrnsts
, 	user_addtype
, 	user_type
, 	user_custsts
, 	user_ordcnt
, 	user_loctck
, 	user_datalc
, 	user_odrsts
, 	user_clientua
, 	user_absvisitorid
, 	user_adobevisitorid
, 	user_sessionid
, 	user_cookiepref
, 	user_emailoptin
, 	user_smsoptin
, 	user_cameraallowed
, 	user_notificationallowed
, 	user_locationsharing
, 	user_os
, 	user_ostype
, 	user_device
, 	page_pgname
, 	page_channel
, 	page_bnr
, 	page_ss1
, 	page_ss2
, 	page_ss3
, 	page_ss4
, 	page_purl
, 	page_platform
, 	page_rurl
, 	page_tp
, 	page_pt
, 	page_sid
, 	page_sitetp
, 	page_appver
, 	event_name
, 	global_attrtoken


) COPY GRANTS comment = 'VIEW FOR ONE_TAG_OTHER' 
AS
SELECT 	
    event_id
, 	event_subevent
,   eventtime
,   error_id
, 	error_feature
, 	error_msg
, 	rewards_id
, 	rewards_redeemed
, 	coupon_type
, 	coupon_name
, 	coupon_id
, 	coupon_clipmthd
, 	coupon_clipcnt
, 	coupon_savings
, 	coupon_sku
, 	coupon_carouselsec
, 	search_type
, 	search_filter
, 	search_orderby
, 	search_offset
, 	search_completionattrtoken
, 	search_selposition
, 	search_apisearchterm
, 	search_tst
, 	search_asf
, 	search_tfc
, 	search_ist
, 	search_rescnt
, 	modal_action
, 	modal_msg
, 	link_name
, 	productinfo_pid
, 	productinfo_pname
, 	productinfo_fname
, 	productinfo_units
, 	productinfo_utyp
, 	productinfo_ppunit
, 	productinfo_lp
, 	productinfo_carouselsec
, 	productinfo_bp
, 	productinfo_ptype
, 	productinfo_cpnflg
, 	productinfo_cpnclpd
, 	productinfo_cpnid
, 	productinfo_cpnapld
, 	productinfo_aid
, 	productinfo_upc
, 	productinfo_pfmdtl
, 	productinfo_ics
, 	productinfo_mto
, 	productinfo_deptnam
, 	productinfo_lbs
, 	productinfo_each
, 	productinfo_aisle
, 	productinfo_shelf
, 	productinfo_offtyp
, 	productinfo_offtext
, 	productinfo_carouselsz
, 	productinfo_isrcmnd
, 	productinfo_iqn
, 	productinfo_iv
, 	productinfo_sellerid
, 	productinfo_sellernam
, 	pagefilter_filtyp
, 	pagefilter_filsel
, 	pagefilter_sortsel
, 	pagefilter_topnav
, 	pagefilter_carousel
, 	pagefilter_adaflg
, 	pagefilter_rtyp
, 	pagefilter_placement
, 	pagefilter_fpdismon
, 	pagefilter_premslots
, 	pagefilter_promocode
, 	pagefilter_mtyp
, 	pagefilter_subsfunnel
, 	cart_iswysiwygenabled
, 	cart_savings_ccsav
, 	cart_savings_j4usav
, 	cart_savings_rwdsav
, 	cart_savings_empsav
, 	cart_savings_pcsav
, 	cart_savings_catinvalidid
, 	cart_savings_catinvalidname
, 	cart_savings_catinvalidnone
, 	cart_savings_ttlsav
, 	cart_savings_totcpns
, 	cart_savings_cpnsclip
, 	cart_transaction_ordid
, 	cart_transaction_paymthd
, 	cart_transaction_dlvtime
, 	cart_transaction_dlvwin
, 	cart_transaction_dlvst
, 	cart_transaction_shipfee
, 	cart_transaction_servcfee
, 	cart_transaction_taxes
, 	cart_transaction_fuelsur
, 	cart_transaction_subttl
, 	cart_transaction_trev
, 	cart_transaction_tmode
, 	cart_transaction_rev
, 	cart_transaction_ordver
, 	cart_transaction_uniqueorderflag
, 	cart_transaction_subttlwinecart_sellerid
, 	cart_transaction_subttlwinecart_subtotal
, 	cart_cartinfo_cid
, 	cart_cartinfo_totunits
, 	cart_cartinfo_ctype
, 	cart_cartinfo_ismfc
, 	cart_cartinfo_mfcunavcnt
, 	cart_cartinfo_acrt
, 	user_uuid
, 	user_shopzc
, 	user_j4uzc
, 	user_dlvbnr
, 	user_dlvpre
, 	user_picloc
, 	user_dlvcomb
, 	user_ssid
, 	user_j4usid
, 	user_loginsts
, 	user_ccn
, 	user_hhid
, 	user_utype
, 	user_custid
, 	user_substs
, 	user_subdate
, 	user_jrnsts
, 	user_addtype
, 	user_type
, 	user_custsts
, 	user_ordcnt
, 	user_loctck
, 	user_datalc
, 	user_odrsts
, 	user_clientua
, 	user_absvisitorid
, 	user_adobevisitorid
, 	user_sessionid
, 	user_cookiepref
, 	user_emailoptin
, 	user_smsoptin
, 	user_cameraallowed
, 	user_notificationallowed
, 	user_locationsharing
, 	user_os
, 	user_ostype
, 	user_device
, 	page_pgname
, 	page_channel
, 	page_bnr
, 	page_ss1
, 	page_ss2
, 	page_ss3
, 	page_ss4
, 	page_purl
, 	page_platform
, 	page_rurl
, 	page_tp
, 	page_pt
, 	page_sid
, 	page_sitetp
, 	page_appver
, 	event_name
, 	global_attrtoken
FROM <<EDM_DB_R_NAME>>.<<EDM_SCHEMA_R_TARGET>>."ONE_TAG_OTHER";
