--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_OTHER runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_DB_NAME_VIEWS>>;
use schema <<EDM_SCHEMA_VIEWS>>;

CREATE OR REPLACE VIEW  CLICK_STREAM_FLAT
(	eventtime
, 	year
, 	month
, 	day
, 	hour
, 	carousel_section
, 	carousel_detail
, 	carousel_lp
, 	carousel_pfm
, 	carousel_pid
, 	carousel_units
, 	error_id
, 	error_feature
, 	error_msg
, 	rewards_id
, 	rewards_redeemed
, 	coupon_type
, 	coupon_name
, 	coupon_id
, 	coupon_clipmthd
, 	coupon_clipcnt
, 	coupon_savings
, 	coupon_sku
, 	coupon_carouselsec
, 	search_type
, 	search_filter
, 	search_orderby
, 	search_offset
, 	search_pagecategories
, 	search_completionattrtoken
, 	search_selposition
, 	search_apisearchterm
, 	search_tst
, 	search_asf
, 	search_tfc
, 	search_ist
, 	search_rescnt
, 	modal_action
, 	modal_msg
, 	link_name
, 	productinfo_pid
, 	productinfo_pname
, 	productinfo_fname
, 	productinfo_units
, 	productinfo_utyp
, 	productinfo_ppunit
, 	productinfo_lp
, 	productinfo_carouselsec
, 	productinfo_bp
, 	productinfo_ptype
, 	productinfo_cpnflg
, 	productinfo_cpnclpd
, 	productinfo_cpnid
, 	productinfo_cpnapld
, 	productinfo_aid
, 	productinfo_upc
, 	productinfo_pfmdtl
, 	productinfo_ics
, 	productinfo_mto
, 	productinfo_deptnam
, 	productinfo_lbs
, 	productinfo_each
, 	productinfo_aisle
, 	productinfo_shelf
, 	productinfo_offtyp
, 	productinfo_offtext
, 	productinfo_carouselsz
, 	productinfo_isrcmnd
, 	productinfo_iqn
, 	productinfo_iv
, 	productinfo_sellerid
, 	productinfo_sellernam
, 	pagefilter_filtyp
, 	pagefilter_filsel
, 	pagefilter_sortsel
, 	pagefilter_topnav
, 	pagefilter_carousel
, 	pagefilter_adaflg
, 	pagefilter_rtyp
, 	pagefilter_placement
, 	pagefilter_fpdismon
, 	pagefilter_premslots
, 	pagefilter_promocode
, 	pagefilter_mtyp
, 	pagefilter_subsfunnel
, 	cart_iswysiwygenabled
, 	cart_savings_ccsav
, 	cart_savings_j4usav
, 	cart_savings_rwdsav
, 	cart_savings_empsav
, 	cart_savings_pcsav
, 	cart_savings_catinvalidid
, 	cart_savings_catinvalidname
, 	cart_savings_catinvalidnone
, 	cart_savings_ttlsav
, 	cart_savings_totcpns
, 	cart_savings_cpnsclip
, 	cart_transaction_ordid
, 	cart_transaction_paymthd
, 	cart_transaction_dlvtime
, 	cart_transaction_dlvwin
, 	cart_transaction_dlvst
, 	cart_transaction_shipfee
, 	cart_transaction_servcfee
, 	cart_transaction_taxes
, 	cart_transaction_fuelsur
, 	cart_transaction_subttl
, 	cart_transaction_trev
, 	cart_transaction_tmode
, 	cart_transaction_rev
, 	cart_transaction_ordver
, 	cart_transaction_uniqueorderflag
, 	cart_transaction_subttlwinecart_sellerid
, 	cart_transaction_subttlwinecart_subtotal
, 	cart_cartinfo_cid
, 	cart_cartinfo_totunits
, 	cart_cartinfo_ctype
, 	cart_cartinfo_ismfc
, 	cart_cartinfo_mfcunavcnt
, 	cart_cartinfo_acrt
, 	user_uuid
, 	user_shopzc
, 	user_j4uzc
, 	user_dlvbnr
, 	user_dlvpre
, 	user_picloc
, 	user_dlvcomb
, 	user_ssid
, 	user_j4usid
, 	user_loginsts
, 	user_ccn
, 	user_hhid
, 	user_utype
, 	user_custid
, 	user_substs
, 	user_subdate
, 	user_jrnsts
, 	user_addtype
, 	user_type
, 	user_custsts
, 	user_ordcnt
, 	user_loctck
, 	user_datalc
, 	user_odrsts
, 	user_clientua
, 	user_absvisitorid
, 	user_adobevisitorid
, 	user_sessionid
, 	user_cookiepref
, 	user_emailoptin
, 	user_smsoptin
, 	user_cameraallowed
, 	user_notificationallowed
, 	user_locationsharing
, 	user_os
, 	user_ostype
, 	user_device
, 	page_pgname
, 	page_channel
, 	page_bnr
, 	page_ss1
, 	page_ss2
, 	page_ss3
, 	page_ss4
, 	page_purl
, 	page_platform
, 	page_rurl
, 	page_tp
, 	page_pt
, 	page_sid
, 	page_sitetp
, 	page_appver
, 	event_name
, 	event_id
, 	event_subevent
, 	event_time
, 	global_attrtoken
, 	global_expids
, 	user_vendor_name
, 	cart_cartinfo_mpcart_vendor
, 	cart_transaction_subttlmpcarts_sellerid
, 	cart_transaction_subttlmpcarts_subtotal
, 	cart_item_prdid
, 	cart_item_prdnam
, 	cart_item_units
, 	cart_item_bp
, 	cart_item_lp
, 	cart_item_itemp
, 	cart_item_totp
, 	cart_item_inv
, 	cart_item_cpnflg
, 	cart_item_cpnclpd
, 	cart_item_cpnapld
, 	cart_item_cpnid
, 	cart_item_ccsav
, 	cart_item_j4usav
, 	cart_item_rsav
, 	cart_item_esav
, 	cart_item_pcsav
, 	cart_item_catinvalidid
, 	cart_item_catinvalidname
, 	cart_item_catinvalidnone
, 	cart_item_tsav
, 	cart_item_ppunit
, 	cart_item_utyp
, 	cart_item_otyp
, 	cart_item_otext
, 	cart_item_isfound
, 	search_impressions_pid
, 	search_impressions_pname
, 	search_impressions_fname
, 	search_impressions_units
, 	search_impressions_utyp
, 	search_impressions_ppunit
, 	search_impressions_lp
, 	search_impressions_carouselsec
, 	search_impressions_bp
, 	search_impressions_ptype
, 	search_impressions_cpnflg
, 	search_impressions_cpnclpd
, 	search_impressions_cpnid
, 	search_impressions_cpnapld
, 	search_impressions_aid
, 	search_impressions_upc
, 	search_impressions_pfmdtl
, 	search_impressions_ics
, 	search_impressions_mto
, 	search_impressions_deptnam
, 	search_impressions_lbs
, 	search_impressions_each
, 	search_impressions_aisle
, 	search_impressions_shelf
, 	search_impressions_offtyp
, 	search_impressions_offtext
, 	search_impressions_carouselsz
, 	search_impressions_isrcmnd
, 	search_impressions_iqn
, 	search_impressions_iv
, 	search_impressions_sellerid
, 	search_impressions_sellernam
, 	cart_cartinfo_mpcart_cart_id
, 	cart_cartinfo_mpcart_cart_type
, 	cart_cartinfo_mpcart_cart_skus
, 	cart_cartinfo_mpcart_cart_total
, 	user_vendor_vars_key
, 	user_vendor_vars_value
) COPY GRANTS comment = 'VIEW FOR CLICK_STREAM_FLAT' 
AS
SELECT 	eventtime
, 	year
, 	month
, 	day
, 	hour
, 	carousel_section
, 	carousel_detail
, 	carousel_lp
, 	carousel_pfm
, 	carousel_pid
, 	carousel_units
, 	error_id
, 	error_feature
, 	error_msg
, 	rewards_id
, 	rewards_redeemed
, 	coupon_type
, 	coupon_name
, 	coupon_id
, 	coupon_clipmthd
, 	coupon_clipcnt
, 	coupon_savings
, 	coupon_sku
, 	coupon_carouselsec
, 	search_type
, 	search_filter
, 	search_orderby
, 	search_offset
, 	search_pagecategories
, 	search_completionattrtoken
, 	search_selposition
, 	search_apisearchterm
, 	search_tst
, 	search_asf
, 	search_tfc
, 	search_ist
, 	search_rescnt
, 	modal_action
, 	modal_msg
, 	link_name
, 	productinfo_pid
, 	productinfo_pname
, 	productinfo_fname
, 	productinfo_units
, 	productinfo_utyp
, 	productinfo_ppunit
, 	productinfo_lp
, 	productinfo_carouselsec
, 	productinfo_bp
, 	productinfo_ptype
, 	productinfo_cpnflg
, 	productinfo_cpnclpd
, 	productinfo_cpnid
, 	productinfo_cpnapld
, 	productinfo_aid
, 	productinfo_upc
, 	productinfo_pfmdtl
, 	productinfo_ics
, 	productinfo_mto
, 	productinfo_deptnam
, 	productinfo_lbs
, 	productinfo_each
, 	productinfo_aisle
, 	productinfo_shelf
, 	productinfo_offtyp
, 	productinfo_offtext
, 	productinfo_carouselsz
, 	productinfo_isrcmnd
, 	productinfo_iqn
, 	productinfo_iv
, 	productinfo_sellerid
, 	productinfo_sellernam
, 	pagefilter_filtyp
, 	pagefilter_filsel
, 	pagefilter_sortsel
, 	pagefilter_topnav
, 	pagefilter_carousel
, 	pagefilter_adaflg
, 	pagefilter_rtyp
, 	pagefilter_placement
, 	pagefilter_fpdismon
, 	pagefilter_premslots
, 	pagefilter_promocode
, 	pagefilter_mtyp
, 	pagefilter_subsfunnel
, 	cart_iswysiwygenabled
, 	cart_savings_ccsav
, 	cart_savings_j4usav
, 	cart_savings_rwdsav
, 	cart_savings_empsav
, 	cart_savings_pcsav
, 	cart_savings_catinvalidid
, 	cart_savings_catinvalidname
, 	cart_savings_catinvalidnone
, 	cart_savings_ttlsav
, 	cart_savings_totcpns
, 	cart_savings_cpnsclip
, 	cart_transaction_ordid
, 	cart_transaction_paymthd
, 	cart_transaction_dlvtime
, 	cart_transaction_dlvwin
, 	cart_transaction_dlvst
, 	cart_transaction_shipfee
, 	cart_transaction_servcfee
, 	cart_transaction_taxes
, 	cart_transaction_fuelsur
, 	cart_transaction_subttl
, 	cart_transaction_trev
, 	cart_transaction_tmode
, 	cart_transaction_rev
, 	cart_transaction_ordver
, 	cart_transaction_uniqueorderflag
, 	cart_transaction_subttlwinecart_sellerid
, 	cart_transaction_subttlwinecart_subtotal
, 	cart_cartinfo_cid
, 	cart_cartinfo_totunits
, 	cart_cartinfo_ctype
, 	cart_cartinfo_ismfc
, 	cart_cartinfo_mfcunavcnt
, 	cart_cartinfo_acrt
, 	user_uuid
, 	user_shopzc
, 	user_j4uzc
, 	user_dlvbnr
, 	user_dlvpre
, 	user_picloc
, 	user_dlvcomb
, 	user_ssid
, 	user_j4usid
, 	user_loginsts
, 	user_ccn
, 	user_hhid
, 	user_utype
, 	user_custid
, 	user_substs
, 	user_subdate
, 	user_jrnsts
, 	user_addtype
, 	user_type
, 	user_custsts
, 	user_ordcnt
, 	user_loctck
, 	user_datalc
, 	user_odrsts
, 	user_clientua
, 	user_absvisitorid
, 	user_adobevisitorid
, 	user_sessionid
, 	user_cookiepref
, 	user_emailoptin
, 	user_smsoptin
, 	user_cameraallowed
, 	user_notificationallowed
, 	user_locationsharing
, 	user_os
, 	user_ostype
, 	user_device
, 	page_pgname
, 	page_channel
, 	page_bnr
, 	page_ss1
, 	page_ss2
, 	page_ss3
, 	page_ss4
, 	page_purl
, 	page_platform
, 	page_rurl
, 	page_tp
, 	page_pt
, 	page_sid
, 	page_sitetp
, 	page_appver
, 	event_name
, 	event_id
, 	event_subevent
, 	event_time
, 	global_attrtoken
, 	global_expids
, 	user_vendor_name
, 	cart_cartinfo_mpcart_vendor
, 	cart_transaction_subttlmpcarts_sellerid
, 	cart_transaction_subttlmpcarts_subtotal
, 	cart_item_prdid
, 	cart_item_prdnam
, 	cart_item_units
, 	cart_item_bp
, 	cart_item_lp
, 	cart_item_itemp
, 	cart_item_totp
, 	cart_item_inv
, 	cart_item_cpnflg
, 	cart_item_cpnclpd
, 	cart_item_cpnapld
, 	cart_item_cpnid
, 	cart_item_ccsav
, 	cart_item_j4usav
, 	cart_item_rsav
, 	cart_item_esav
, 	cart_item_pcsav
, 	cart_item_catinvalidid
, 	cart_item_catinvalidname
, 	cart_item_catinvalidnone
, 	cart_item_tsav
, 	cart_item_ppunit
, 	cart_item_utyp
, 	cart_item_otyp
, 	cart_item_otext
, 	cart_item_isfound
, 	search_impressions_pid
, 	search_impressions_pname
, 	search_impressions_fname
, 	search_impressions_units
, 	search_impressions_utyp
, 	search_impressions_ppunit
, 	search_impressions_lp
, 	search_impressions_carouselsec
, 	search_impressions_bp
, 	search_impressions_ptype
, 	search_impressions_cpnflg
, 	search_impressions_cpnclpd
, 	search_impressions_cpnid
, 	search_impressions_cpnapld
, 	search_impressions_aid
, 	search_impressions_upc
, 	search_impressions_pfmdtl
, 	search_impressions_ics
, 	search_impressions_mto
, 	search_impressions_deptnam
, 	search_impressions_lbs
, 	search_impressions_each
, 	search_impressions_aisle
, 	search_impressions_shelf
, 	search_impressions_offtyp
, 	search_impressions_offtext
, 	search_impressions_carouselsz
, 	search_impressions_isrcmnd
, 	search_impressions_iqn
, 	search_impressions_iv
, 	search_impressions_sellerid
, 	search_impressions_sellernam
, 	cart_cartinfo_mpcart_cart_id
, 	cart_cartinfo_mpcart_cart_type
, 	cart_cartinfo_mpcart_cart_skus
, 	cart_cartinfo_mpcart_cart_total
, 	user_vendor_vars_key
, 	user_vendor_vars_value
FROM <<EDM_DB_NAME>>.<<EDM_SCHEMA_STAGE>>."CLICK_STREAM_FLAT";