--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_PRODUCT_IMPRESSIONS_OT runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_DB_NAME_VIEWS>>;
use schema <<EDM_SCHEMA_VIEWS>>;

CREATE VIEW ONETAG_PRODUCT_IMPRESSION (
	APPLICATION_DETAIL_TXT,
	BASE_PRODUCT_NBR,
	CAROUSEL_NM,
	CLUB_CARD_NBR,
	EVENT_ID,
	HOUSEHOLD_ID,
	MODEL_ID_TXT,
	PRODUCT_FINDING_METHOD_DSC,
	PAGE_NM,
	PRODUCT_SEEN_IND,
	PRODUCT_SEEN_TS,
	PRODUCTS_SEEN_IN_CAROUSEL_IND,
	RETAIL_CUSTOMER_UUID,
	ROW_LOCATION_CD,
	SLOT_LOCATION_CD,
	SESSION_ID,
	SESSION_SEQUENCE_NBR,
	COOKIE_PREFERENCE_CD,
	DW_LOGICAL_DELETE_IND,
	DW_CURRENT_VERSION_IND,
	DW_CREATE_TS,
	DW_LAST_UPDATE_TS
) comment = 'VIEW FOR ONE_TAG_PRODUCT_IMPRESSIONS' 
AS
SELECT
 	APPLICATION_DETAIL_TXT,
	BASE_PRODUCT_NBR,
	CAROUSEL_NM,
	CLUB_CARD_NBR,
	EVENT_ID,
	HOUSEHOLD_ID,
	MODEL_ID_TXT,
	PRODUCT_FINDING_METHOD_DSC,
	PAGE_NM,
	PRODUCT_SEEN_IND,
	PRODUCT_SEEN_TS,
	PRODUCTS_SEEN_IN_CAROUSEL_IND,
	RETAIL_CUSTOMER_UUID,
	ROW_LOCATION_CD,
	SLOT_LOCATION_CD,
	SESSION_ID,
	SESSION_SEQUENCE_NBR,
	COOKIE_PREFERENCE_CD,
	DW_LOGICAL_DELETE_IND,
	DW_CURRENT_VERSION_IND,
	DW_CREATE_TS,
	DW_LAST_UPDATE_TS
FROM EDM_ANALYTICS_<<ENV>>.DW_DIGITAL_EXP.ONETAG_PRODUCT_IMPRESSION;
