--liquibase formatted sql
--changeset SYSTEM:ONE_TAG_CLICK_STREAM_VISIT runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_DB_NAME_VIEWS>>;
use schema <<EDM_SCHEMA_VIEWS>>;

CREATE OR REPLACE VIEW ONE_TAG_CLICK_STREAM_VISIT (
	EVENT_ID,
	SESSION_ID,
	VISIT_ID,
	VISIT_PAGE_NBR,
	EVENT_TS,
	ADOBE_CREATE_TS
) comment = 'VIEW FOR ONE_TAG_CLICK_STREAM_VISIT' 
AS
SELECT
 	EVENT_ID,
	SESSION_ID,
	VISIT_ID,
	VISIT_PAGE_NBR,
	EVENT_TS,
	ADOBE_CREATE_TS
FROM EDM_CONFIRMED_<<ENV>>.DW_C_STAGE.ONE_TAG_CLICK_STREAM_VISIT_WRK;