--liquibase formatted sql
--changeset SYSTEM:CLICK_STREAM_OPERATING_SYSTEM runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_<<ENV>>;
use schema DW_VIEWS;

CREATE OR REPLACE VIEW  CLICK_STREAM_OPERATING_SYSTEM
(	
	OPERATING_SYSTEM_INTEGRATION_ID
	,OPERATING_SYSTEM_CD
	,OPERATING_SYSTEM_TYPE_CD
	,PLATFORM_CD
	,DW_CREATE_TS
	,DW_LAST_UPDATE_TS
	,DW_LOGICAL_DELETE_IND
	,DW_SOURCE_CREATE_NM
	,DW_SOURCE_UPDATE_NM
	,DW_CURRENT_VERSION_IND
) COPY GRANTS comment = 'VIEW FOR CLICK_STREAM_OPERATING_SYSTEM' 
AS
SELECT 	OPERATING_SYSTEM_INTEGRATION_ID
	,OPERATING_SYSTEM_CD
	,OPERATING_SYSTEM_TYPE_CD
	,PLATFORM_CD
	,DW_CREATE_TS
	,DW_LAST_UPDATE_TS
	,DW_LOGICAL_DELETE_IND
	,DW_SOURCE_CREATE_NM
	,DW_SOURCE_UPDATE_NM
	,DW_CURRENT_VERSION_IND
FROM EDM_CONFIRMED_<<ENV>>.DW_C_USER_ACTIVITY."CLICK_STREAM_OPERATING_SYSTEM";