--liquibase formatted sql
--changeset SYSTEM:CUSTOMER_SESSION_EVENT_MASTER runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database EDM_VIEWS_<<ENV>>;
use schema DW_VIEWS;

CREATE OR REPLACE VIEW CUSTOMER_SESSION_EVENT_MASTER
(	
	EVENT_ID,
	EVENT_TS,
	SESSION_ID,
	PAGE_INTEGRATION_ID,
	EVENT_NM,
	VISITOR_INTEGRATION_ID,
	VISITOR_ID,
	HOUSEHOLD_ID,
	CLUB_CARD_NBR,
	RETAIL_CUSTOMER_UUID,
	ADOBE_VISITOR_ID,
	EVENT_TYPE_CD,
	EVENT_DT,
	SESSION_SEQUENCE_NBR,
	BANNER_NM,
	Division_Id,
	DIVISION_NM,
	OPERATING_SYSTEM_INTEGRATION_ID,
	FACILITY_NBR,
	FACILITY_INTEGRATION_ID,
	POSTAL_ZONE_CD,
	APP_VERSION_CD,
	PAGE_URL_TXT,
	DEVICE_NM,
	DW_CREATE_TS,
	DW_LAST_UPDATE_TS,
	DW_LOGICAL_DELETE_IND,
	DW_SOURCE_CREATE_NM,
	DW_SOURCE_UPDATE_NM,
	DW_CURRENT_VERSION_IND
	
) COPY GRANTS comment = 'VIEW FOR CUSTOMER_SESSION_EVENT_MASTER' 
AS
SELECT 
	EVENT_ID,
	EVENT_TS,
	SESSION_ID,
	PAGE_INTEGRATION_ID,
	EVENT_NM,
	VISITOR_INTEGRATION_ID,
	VISITOR_ID,
	HOUSEHOLD_ID,
	CLUB_CARD_NBR,
	RETAIL_CUSTOMER_UUID,
	ADOBE_VISITOR_ID,
	EVENT_TYPE_CD,
	EVENT_DT,
	SESSION_SEQUENCE_NBR,
	BANNER_NM,
	Division_Id,
	DIVISION_NM,
	OPERATING_SYSTEM_INTEGRATION_ID,
	FACILITY_NBR,
	FACILITY_INTEGRATION_ID,
	POSTAL_ZONE_CD,
	APP_VERSION_CD,
	PAGE_URL_TXT,
	DEVICE_NM,
	DW_CREATE_TS,
	DW_LAST_UPDATE_TS,
	DW_LOGICAL_DELETE_IND,
	DW_SOURCE_CREATE_NM,
	DW_SOURCE_UPDATE_NM,
	DW_CURRENT_VERSION_IND
FROM EDM_CONFIRMED_<<ENV>>.DW_C_USER_ACTIVITY."CUSTOMER_SESSION_EVENT_MASTER";