--liquidbase formatted sql
--changeset SYSTEM:ITEM_PRICE_ADJUSTMENTS runOnChange: true splitStatements:false OBJECT_TYPE:TASK

USE DATABASE <<TGT_EDM_DB_NAME>>;
USE SCHEMA <<SP_DEPLOY_SCHEMA>>;

CREATE OR REPLACE TASK <<TGT_EDM_DB_NAME>>.<<SP_DEPLOY_SCHEMA>>.CATALINA_OUTBOUND_ITEM_PRICE_ADJUSTMENTS_LOAD_TASK
    WAREHOUSE = <<WAREHOUSE>>
    SCHEDULE = 'USING CRON 0 2 * * * MST'
        QUERY_TAG = '{"OBJECT_TYPE":"TASK", "OBJECT_NAME":"SP_ITEM_PRICE_ADJUSTMENTS_Incremental", "APPCODE":"EDDW"}'
    AS
    call CATALINA_OUTBOUND.DW_APPL.SP_ITEM_PRICE_ADJUSTMENTS_Incremental();
    
ALTER TASK CATALINA_OUTBOUND_ITEM_PRICE_ADJUSTMENTS_LOAD_TASK RESUME;
