--liquibase formatted sql
--changeset SYSTEM:BUSINESS_PARTNER_SERVICE_FEE_EXCEPTIONS runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE BUSINESS_PARTNER_SERVICE_FEE_EXCEPTIONS (
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0),
	PARTNER_NM VARCHAR(250),
	SERVICE_FEE_TYPE_CD VARCHAR(50),
	SERVICE_FEE_CATEGORY_CD VARCHAR(50),
	SERVICE_FEE_AMT NUMBER(38,0),
	SERVICE_FEE_ITEM_ID VARCHAR(20),
	CREATIONDT DATE,
	FILENAME VARCHAR(16777216),
	DML_TYPE VARCHAR(16777216),
	SAMEDAY_CHG_IND VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
