--liquibase formatted sql
--changeset SYSTEM:Business_Partner_Service_Override_Exceptions runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE BUSINESS_PARTNER_SERVICE_OVERRIDE_EXCEPTIONS (
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0),
	PARTNER_NM VARCHAR(250),
	OVERRIDE_PARTNER_ID NUMBER(38,0),
	OVERRIDE_PARTNER_NM VARCHAR(250),
	OVERRIDE_TYPE_CD VARCHAR(50),
	OVERRIDE_TYPE_DSC VARCHAR(250),
	OVERRIDE_TYPE_SHORT_DSC VARCHAR(50),
	OVERRIDE_IND BOOLEAN,
	OVERRIDE_REASON_TYPE_CD VARCHAR(50),
	OVERRIDE_REASON_TYPE_DSC VARCHAR(250),
	OVERRIDE_REASON_TYPE_SHORT_DSC VARCHAR(50),
	CREATIONDT DATE,
	FILENAME VARCHAR(16777216),
	DML_TYPE VARCHAR(16777216),
	SAMEDAY_CHG_IND VARCHAR(16777216),
	EXCEPTION_REASON VARCHAR(16777216),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
