--liquibase formatted sql
--changeset SYSTEM:FRESHPASS_SUBSCRIPTION_EVENT runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_VIEW_NAME>>;
use schema <<EDM_VIEW_NAME>>.DW_VIEWS;

create or replace view FRESHPASS_SUBSCRIPTION_EVENT(
	RETAIL_CUSTOMER_UUID COMMENT 'Customer Unique Identifier',
	EVENT_ID COMMENT 'Identifier of the event',
	SUBSCRIPTION_PLAN_INTEGRATION_ID COMMENT 'Generated Integration Identifier based on alternate keys',
	DW_FIRST_EFFECTIVE_DT COMMENT 'The date the record was inserted.  For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_DT COMMENT 'for the current record this is ''12/31/9999''.  for updated records based on the primary key of the table, this is the new current records DW_First_Effective_Dt -1 day',
	RETAIL_CUSTOMER_GUID COMMENT 'Customer Global Unique Identifier',
	CUSTOMER_HOUSEHOLD_ID COMMENT 'Customer Household Identifier',
	BANNER_NM COMMENT 'Banner Name',
	CUSTOMER_COMMENT_TXT COMMENT 'Comment added by customer before cancelling the subscription',
	CUSTOMER_ORDER_CNT COMMENT 'Customer Order count',
	CYCLE_DELIVERY_SAVINGS_AMT COMMENT 'Freshpass delivery savings amount',
	CYCLE_PERK_SAVINGS_AMT COMMENT 'Freshpass Perk Savings amount',
	CYCLE_TOTAL_SAVINGS_AMT COMMENT 'Freshpass Cycle total savings',
	EVENT_TS COMMENT 'Timestamp when the event took place',
	EVENT_TYPE_DSC COMMENT 'Description of the frespass event',
	LIFE_DELIVERY_SAVINGS_AMT COMMENT 'Freshpass Life Delivery Savings',
	LIFE_PERK_SAVINGS_AMT COMMENT 'Freshpass Life Perk Savings',
	LIFE_TOTAL_SAVINGS_AMT COMMENT 'FreshPass Life Total Savings',
	MASKED_CARD_NBR COMMENT 'MaskedNumber with Last 4 Digits',
	REENROLLED_USER_IND COMMENT 'Indicator to identify if the user is re-enrolled user',
	SUBSCRIPTION_STATUS_DSC COMMENT 'Customer Subscription Status of the plan',
	SUBSCRIPTION_STATUS_ID COMMENT 'Generated Identifier of the Subscription Status of the plan',
	SOURCE_SYSTEM_CD COMMENT 'Source System Code',
	SUBSCRIPTION_PAYMENT_DT COMMENT 'FreshPass Payment Date',
	TENDER_TYPE_DSC COMMENT 'TenderType - Shop Or DeliverySubscription',
	PLAN_CANCELLATION_REASON_DSC COMMENT 'FreshPass Cancellation reason',
	PLAN_ENROLLMENT_DT COMMENT 'FreshPass Plan Active Date',
	PLAN_EXPIRY_DT COMMENT 'Current FreshPassPlan Expiry Date',
	PLAN_RENEWAL_DT COMMENT 'Plan Renewal Date',
	PLAN_SIGNUP_DT COMMENT 'Customer SignUp Date',
	SUBSCRIPTION_TAX_AMT COMMENT 'Freshpass plan Price tax',
	TOTAL_CHARGES_AMT COMMENT 'Total Plan Charges',
	DW_CREATE_TS COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS COMMENT 'When a record is updated  this would be the current timestamp',
	DW_LOGICAL_DELETE_IND COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d'
) COMMENT='VIEW For Freshpass_Subscription_Event'
 as
SELECT 
Retail_Customer_Uuid,
Event_Id,
Subscription_Plan_Integration_Id,
Dw_First_Effective_Dt,
Dw_Last_Effective_Dt,
Retail_Customer_Guid,
Customer_Household_Id,
Banner_Nm,
Customer_Comment_Txt,
Customer_Order_Cnt,
Cycle_Delivery_Savings_Amt,
Cycle_Perk_Savings_Amt,
Cycle_Total_Savings_Amt,
Event_Ts,
Event_Type_Dsc,
Life_Delivery_Savings_Amt,
Life_Perk_Savings_Amt,
Life_Total_Savings_Amt,
Masked_Card_Nbr,
Reenrolled_User_Ind,
Subscription_Status_Dsc,
Subscription_Status_Id,
Source_System_Cd,
Subscription_Payment_Dt,
Tender_Type_Dsc,
Plan_Cancellation_Reason_Dsc,
Plan_Enrollment_Dt,
Plan_Expiry_Dt,
Plan_Renewal_Dt,
Plan_Signup_Dt,
Subscription_Tax_Amt,
Total_Charges_Amt,
Dw_Create_Ts,
Dw_Last_Update_Ts,
Dw_Logical_Delete_Ind,
Dw_Source_Create_Nm,
Dw_Source_Update_Nm,
Dw_Current_Version_Ind
FROM EDM_CONFIRMED_PRD.DW_C_LOYALTY.FRESHPASS_SUBSCRIPTION_EVENT;
