--liquibase formatted sql
--changeset SYSTEM:FRESHPASS_SUBSCRIPTION_DISCOUNT runOnChange:true splitStatements:false OBJECT_TYPE:view

USE DATABASE <<EDM_DB_NAME_VIEW>>;
USE SCHEMA DW_VIEWS;

create or replace view FRESHPASS_SUBSCRIPTION_DISCOUNT (
										DISCOUNT_TYPE_NM,
										DW_FIRST_EFFECTIVE_DT,
										DW_LAST_EFFECTIVE_DT,
										SUBSCRIPTION_CD,
										DISCOUNT_FEE_AMT,
										CAMPAIGN_START_TS,
										CAMPAIGN_END_TS,
										DISCOUNT_DURATION_QTY,
										IS_ACTIVE_IND,
										TRIAL_DURATION_QTY,
										CAMPAIGN_THRESHOLD_QTY,
										ENROLLMENT_CNT,
										CMAPIGN_RULES_TXT,
										CAMPAIGN_TYPE_NM,
										CAMPAIGN_TITLE_NM,
										CAMPAIGN_SAVINGS_TXT,
										CATEGORY_NM,
										CREATE_TS,
										CREATE_USER_ID,
										UPDATE_TS,
										UPDATE_USER_ID,
										DW_CREATE_TS,
										DW_LAST_UPDATE_TS,
										DW_LOGICAL_DELETE_IND,
										DW_SOURCE_CREATE_NM,
										DW_SOURCE_UPDATE_NM,
										DW_CURRENT_VERSION_IND
) COMMENT='VIEW For FRESHPASS_SUBSCRIPTION_DISCOUNT'
	as
	SELECT 
	DISCOUNT_TYPE_NM,
	DW_FIRST_EFFECTIVE_DT,
	DW_LAST_EFFECTIVE_DT,
	SUBSCRIPTION_CD,
	DISCOUNT_FEE_AMT,
	CAMPAIGN_START_TS,
	CAMPAIGN_END_TS,
	DISCOUNT_DURATION_QTY,
	IS_ACTIVE_IND,
	TRIAL_DURATION_QTY,
	CAMPAIGN_THRESHOLD_QTY,
	ENROLLMENT_CNT,
	CMAPIGN_RULES_TXT,
	CAMPAIGN_TYPE_NM,
	CAMPAIGN_TITLE_NM,
	CAMPAIGN_SAVINGS_TXT,
	CATEGORY_NM,
	CREATE_TS,
	CREATE_USER_ID,
	UPDATE_TS,
	UPDATE_USER_ID,
	DW_CREATE_TS,
	DW_LAST_UPDATE_TS,
	DW_LOGICAL_DELETE_IND,
	DW_SOURCE_CREATE_NM,
	DW_SOURCE_UPDATE_NM,
	DW_CURRENT_VERSION_IND
	FROM EDM_CONFIRMED_<<ENV>>.DW_C_LOYALTY.FRESHPASS_SUBSCRIPTION_DISCOUNT;
