--liquibase formatted sql
--changeset SYSTEM:GET_SMS_MARKETING_CONTENT_DEFITION_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_APPL;

CREATE OR REPLACE TASK GET_SMS_MARKETING_CONTENT_DEFITION_TASK
WAREHOUSE='EDM_ADMIN_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('EDM_REFINED_PRD.DW_APPL.Get_SMS_Marketing_Defition_Flat_R_STREAM')
AS CALL SP_GetSMS_MARKETING_CONTENT_DEFITION_To_BIM_load();

ALTER TASK GET_SMS_MARKETING_CONTENT_DEFITION_TASK RESUME;
