--liquibase formatted sql
--changeset SYSTEM:SP_GETOFFEROMS_TO_BIM_LOAD_OFFEROMS_FLAT runOnChange:true splitStatements:false OBJECT_TYPE:SP

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_APPL;

CREATE OR REPLACE PROCEDURE SP_GETOFFEROMS_TO_BIM_LOAD_OFFEROMS_FLAT("FLAT_STREAM" VARCHAR(16777216), "CNF_DB" VARCHAR(16777216), "DW_SCHEMA" VARCHAR(16777216), "WRK_SCHEMA" VARCHAR(16777216))
RETURNS VARCHAR(16777216)
LANGUAGE JAVASCRIPT
EXECUTE AS OWNER
AS
$$
   
    // **************        Load for OfferOMS_Flat table BEGIN *****************

    var src_flat_strm  = FLAT_STREAM;	
    var cnf_db = CNF_DB;
    var cnf_schema = DW_SCHEMA;
    var wrk_schema = WRK_SCHEMA;
    var Ref_db = "EDM_REFINED_PRD";
    var Ref_schema = "DW_R_PRODUCT";
    
    var src_flat_table=Ref_db + "." +Ref_schema+".offeroms_flat" ;
    // identify  if the columns have changed between Target table and changed dataset and create a work table specific to the BIM table. 
    var tgt_wrk_tbl = cnf_db + "." + wrk_schema + ".OfferOMS_Flat_Wrk";
    var tgt_tbl = cnf_db +"."+ cnf_schema +".OfferOMS_Flat";

		// Empty the target work table
		var sql_empty_src_wrk_tbl = `TRUNCATE TABLE `+ tgt_wrk_tbl +` `;
		try {
			snowflake.execute ({sqlText: sql_empty_src_wrk_tbl });
			}
		catch (err) { 
			throw "Truncation of table "+ tgt_wrk_tbl +" Failed with error: " + err;   // Return a error message.
		}
	
		var wrk_tbl = `INSERT INTO `+ tgt_wrk_tbl +` 
	             select src.filename 
						,src.PayloadPart 
						,src.PageNum 
						,src.TotalPages 
						,src.EntityId 
						,src.PayLoadType 
						,src.EntityType 
						,src.SourceAction 
						,src.payload_id 
						,src.payload_externalOfferId 
						,src.payload_offerRequestId 
						,src.payload_aggregatorOfferId 
						,src.payload_manufacturerId 
						,src.payload_manufacturerOfferRefCd 
						,src.payload_providerName 
						,src.payload_categories_additionalProperties 
						,src.payload_primaryCategory_additionalProperties 
						,src.payload_events_additionalProperties 
						,src.payload_hiddenEvents_additionalProperties 
						,src.payload_programCode 
						,src.payload_programCodeDesc 
						,src.payload_subProgram 
						,src.payload_subProgramDesc 
						,src.payload_deliveryChannel 
						,src.payload_deliveryChannelDesc 
						,src.payload_status 
						,src.payload_statusDesc 
						,src.payload_priceTitle 
						,src.payload_priceValue 
						,src.payload_savingsValueText 
						,src.payload_titleDescription_additionalProperties 
						,src.payload_productDescription_additionalProperties 
						,src.payload_disclaimerText 
						,src.payload_description 
						,src.payload_printTags 
						,src.payload_productImageId 
						,src.payload_priceCode 
						,src.payload_time 
						,src.payload_year 
						,src.payload_productCd 
						,src.payload_isEmployeeOffer 
						,src.payload_isDefaultAllocationOffer 
						,src.payload_programType 
						,src.payload_shouldReportRedemptions 
						,src.payload_createdTs 
						,src.payload_createdApplicationId 
						,src.payload_createdUserId 
						,src.payload_lastUpdatedApplicationId 
						,src.payload_lastUpdatedUserId 
						,src.payload_lastUpdatedTs 
						,src.payload_displayEffectiveStartDate 
						,src.payload_displayEffectiveEndDate 
						,src.payload_effectiveStartDate 
						,src.payload_effectiveEndDate 
						,src.payload_testEffectiveStartDate 
						,src.payload_testEffectiveEndDate 
						,src.payload_postalCodes 
						,src.payload_terminals 
						,src.payload_excludedTerminals 
						,src.payload_qualificationUnitType 
						,src.payload_qualificationUnitSubType 
						,src.payload_benefitValueType 
						,src.payload_usageLimitTypePerUser 
						,src.payload_pluTriggerBarcode 
						,src.payload_copientCategory 
						,src.payload_engine 
						,src.payload_priority 
						,src.payload_tiers 
						,src.payload_sendOutboundData 
						,src.payload_chargebackVendor 
						,src.payload_autoTransferable 
						,src.payload_enableIssuance 
						,src.payload_deferEvaluationUntilEOS 
						,src.payload_enableImpressionReporting 
						,src.payload_limitEligibilityFrequency 
						,src.payload_isApplicableToJ4U 
						,src.payload_customerSegment 
						,src.payload_assignment_userId 
						,src.payload_assignment_firstName 
						,src.payload_assignment_lastName 
						,src.payload_qualificationProductGroups 
						,src.payload_qualificationCustomergroups 
						,src.payload_qualificationPointsGroups 
						,src.payload_testStoreGroups 
						,src.payload_testCustomerGroups 
						,src.payload_benefit_benefitValueType 
						,src.payload_benefit_benefitValueDesc 
						,src.payload_benefit_benefitValue 
						,src.payload_benefit_discount 
						,src.payload_benefit_points 
						,src.payload_benefit_groupMemberShip_customerGroupName 
						,src.payload_benefit_printedMessage_message 
						,src.payload_benefit_printedMessage_isApplicableForNotifications 
						,src.payload_benefit_cashierMessage_cashierMessageTiers 
						,src.payload_benefit_cashierMessage_isApplicableForNotifications 
						,src.payload_qualificationStoreGroups_podStoreGroups 
						,src.payload_qualificationStoreGroups_nonDigitalRedemptionStoreGroups 
						,src.payload_qualificationStoreGroups_digitalRedemptionStoreGroups 
						,src.payload_qualificationProductDisQualifier 
						,src.payload_qualificationDay_monday 
						,src.payload_qualificationDay_tuesday 
						,src.payload_qualificationDay_wednesday 
						,src.payload_qualificationDay_thursday 
						,src.payload_qualificationDay_friday 
						,src.payload_qualificationDay_saturday 
						,src.payload_qualificationDay_sunday 
						,src.payload_qualificationTime_start 
						,src.payload_qualificationTime_end 
						,src.payload_qualificationEnterpriseInstantWin_numberOfPrizes 
						,src.payload_qualificationEnterpriseInstantWin_frequency 
						,src.payload_qualificationTriggerCodes 
						,src.payload_qualificationAttributes 
						,src.payload_nopaNumbers 
						,src.payload_offerName 
						,src.payload_adType 
						,src.payload_offerProtoType 
						,src.payload_offerPrototypeDesc 
						,src.payload_storeGroupVersionId 
						,src.payload_storeTag_printJ4uTagEnabled 
						,src.payload_storeTag_multiple 
						,src.payload_storeTag_amount 
						,src.payload_storeTag_comments 
						,src.payload_requestedRemovalForAll 
						,src.payload_removedOn 
						,src.payload_removedUnclippedOn 
						,src.payload_removedForAllOn 
						,src.payload_brandNSize 
						,src.payload_createdUser_userId 
						,src.payload_createdUser_firstName 
						,src.payload_createdUser_lastName 
						,src.payload_updatedUser_userId 
						,src.payload_updatedUser_firstName 
						,src.payload_updatedUser_lastName 
						,src.payload_firstUpdateToRedemptionEngine 
						,src.payload_lastUpdateToRedemptionEngine 
						,src.payload_firstUpdateToJ4U 
						,src.payload_lastUpdateToJ4U 
						,src.payload_offerRequestorGroup 
						,src.payload_headLine 
						,src.payload_isPODApproved 
						,src.payload_podUsageLimitTypePerUser 
						,src.payload_podReferenceOfferId 
						,src.payload_ivieImageId 
						,src.payload_vehicleNm 
						,src.payload_adPageNbr 
						,src.payload_adModNbr 
						,src.payload_ecomDesc 
						,src.payload_requestedUser_userId 
						,src.payload_requestedUser_firstName 
						,src.payload_requestedUser_lastName 
						,src.payload_isPrimaryPODOffer 
						,src.lastUpdateTs 
						,src.DW_CREATE_TS 
						,src.PAYLOAD_PRODUCT_DESCPRODDSC1
						,src.PAYLOAD_PRODUCT_DESCPRODDSC2
						,src.PAYLOAD_TITLE_DESCTITLEDSC1
						,src.PAYLOAD_TITLE_DESCTITLEDSC2
						,src.PAYLOAD_TITLE_DESCTITLEDSC3 
						,src.payload_redemptionSystemId
						,src.payload_events
						,src.payload_regionIdMap
						,src.payload_usageLimitPerUser 
						,src.payload_customPeriod 
						,src.payload_customType 
						,src.QUALIFICATIONPRODUCTDISQUALIFIERNAME
					    ,src.ISDISPLAYIMMEDIATE	
						,src.payload_qualificationStoreGroups_redemptionStoreGroups
						,src.PAYLOAD_QUALIFICATIONTENDERTYPES
						,src.PAYLOAD_FULFILLMENTCHANNEL
					    ,src.PAYLOAD_ECOMMPROMOTYPE 
						,src.payload_ecommPromoCode
						,src.payload_validWithOtherOffer
						,src.payload_orderCount
						,src.payload_firstTimeCustomerOnly
						,src.payload_autoApplyPromoCode
						,src.payload_notCombinableWith
						,src.PAYLOAD_SUBPROGRAMCODE
						,src.PAYLOAD_QUALIFICATIONBEHAVIOR
						,src.PAYLOAD_INITIALSUBSCRIPTIONOFFER
						,src.PAYLOAD_ISDYNAMICOFFER
						,src.PAYLOAD_DAYSTOREDEEM
                            From (
             SELECT   filename 
					,PayloadPart 
					,PageNum 
					,TotalPages 
					,EntityId 
					,PayLoadType 
					,EntityType 
					,SourceAction 
					,payload_id 
					,payload_externalOfferId 
					,payload_offerRequestId 
					,payload_aggregatorOfferId 
					,payload_manufacturerId 
					,payload_manufacturerOfferRefCd 
					,payload_providerName 
					,payload_categories_additionalProperties 
					,payload_primaryCategory_additionalProperties 
					,payload_events_additionalProperties 
					,payload_hiddenEvents_additionalProperties 
					,payload_programCode 
					,payload_programCodeDesc 
					,payload_subProgram 
					,payload_subProgramDesc 
					,payload_deliveryChannel 
					,payload_deliveryChannelDesc 
					,payload_status 
					,payload_statusDesc 
					,payload_priceTitle 
					,payload_priceValue 
					,payload_savingsValueText 
					,payload_titleDescription_additionalProperties 
					,payload_productDescription_additionalProperties 
					,payload_disclaimerText 
					,payload_description 
					,payload_printTags 
					,payload_productImageId 
					,payload_priceCode 
					,payload_time 
					,payload_year 
					,payload_productCd 
					,payload_isEmployeeOffer 
					,payload_isDefaultAllocationOffer 
					,payload_programType 
					,payload_shouldReportRedemptions 
					,payload_createdTs 
					,payload_createdApplicationId 
					,payload_createdUserId 
					,payload_lastUpdatedApplicationId 
					,payload_lastUpdatedUserId 
					,payload_lastUpdatedTs 
					,payload_displayEffectiveStartDate 
					,payload_displayEffectiveEndDate 
					,payload_effectiveStartDate 
					,payload_effectiveEndDate 
					,payload_testEffectiveStartDate 
					,payload_testEffectiveEndDate 
					,payload_postalCodes 
					,payload_terminals 
					,payload_excludedTerminals 
					,payload_qualificationUnitType 
					,payload_qualificationUnitSubType 
					,payload_benefitValueType 
					,payload_usageLimitTypePerUser 
					,payload_pluTriggerBarcode 
					,payload_copientCategory 
					,payload_engine 
					,payload_priority 
					,payload_tiers 
					,payload_sendOutboundData 
					,payload_chargebackVendor 
					,payload_autoTransferable 
					,payload_enableIssuance 
					,payload_deferEvaluationUntilEOS 
					,payload_enableImpressionReporting 
					,payload_limitEligibilityFrequency 
					,payload_isApplicableToJ4U 
					,payload_customerSegment 
					,payload_assignment_userId 
					,payload_assignment_firstName 
					,payload_assignment_lastName 
					,payload_qualificationProductGroups 
					,payload_qualificationCustomergroups 
					,payload_qualificationPointsGroups 
					,payload_testStoreGroups 
					,payload_testCustomerGroups 
					,payload_benefit_benefitValueType 
					,payload_benefit_benefitValueDesc 
					,payload_benefit_benefitValue 
					,payload_benefit_discount 
					,payload_benefit_points 
					,payload_benefit_groupMemberShip_customerGroupName 
					,payload_benefit_printedMessage_message 
					,payload_benefit_printedMessage_isApplicableForNotifications 
					,payload_benefit_cashierMessage_cashierMessageTiers 
					,payload_benefit_cashierMessage_isApplicableForNotifications 
					,payload_qualificationStoreGroups_podStoreGroups 
					,payload_qualificationStoreGroups_nonDigitalRedemptionStoreGroups 
					,payload_qualificationStoreGroups_digitalRedemptionStoreGroups 
					,payload_qualificationProductDisQualifier 
					,payload_qualificationDay_monday 
					,payload_qualificationDay_tuesday 
					,payload_qualificationDay_wednesday 
					,payload_qualificationDay_thursday 
					,payload_qualificationDay_friday 
					,payload_qualificationDay_saturday 
					,payload_qualificationDay_sunday 
					,payload_qualificationTime_start 
					,payload_qualificationTime_end 
					,payload_qualificationEnterpriseInstantWin_numberOfPrizes 
					,payload_qualificationEnterpriseInstantWin_frequency 
					,payload_qualificationTriggerCodes 
					,payload_qualificationAttributes 
					,payload_nopaNumbers 
					,payload_offerName 
					,payload_adType 
					,payload_offerProtoType 
					,payload_offerPrototypeDesc 
					,payload_storeGroupVersionId 
					,payload_storeTag_printJ4uTagEnabled 
					,payload_storeTag_multiple 
					,payload_storeTag_amount 
					,payload_storeTag_comments 
					,payload_requestedRemovalForAll 
					,payload_removedOn 
					,payload_removedUnclippedOn 
					,payload_removedForAllOn 
					,payload_brandNSize 
					,payload_createdUser_userId 
					,payload_createdUser_firstName 
					,payload_createdUser_lastName 
					,payload_updatedUser_userId 
					,payload_updatedUser_firstName 
					,payload_updatedUser_lastName 
					,payload_firstUpdateToRedemptionEngine 
					,payload_lastUpdateToRedemptionEngine 
					,payload_firstUpdateToJ4U 
					,payload_lastUpdateToJ4U 
					,payload_offerRequestorGroup 
					,payload_headLine 
					,payload_isPODApproved 
					,payload_podUsageLimitTypePerUser 
					,payload_podReferenceOfferId 
					,payload_ivieImageId 
					,payload_vehicleNm 
					,payload_adPageNbr 
					,payload_adModNbr 
					,payload_ecomDesc 
					,payload_requestedUser_userId 
					,payload_requestedUser_firstName 
					,payload_requestedUser_lastName 
					,payload_isPrimaryPODOffer 
					,lastUpdateTs 
					,DW_CREATE_TS
					,PAYLOAD_PRODUCT_DESCPRODDSC1
					,PAYLOAD_PRODUCT_DESCPRODDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC1
					,PAYLOAD_TITLE_DESCTITLEDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC3
                    ,payload_redemptionSystemId	
                    ,payload_events
                    ,payload_regionIdMap
					,payload_usageLimitPerUser 
					,payload_customPeriod 
					,payload_customType 
					,QUALIFICATIONPRODUCTDISQUALIFIERNAME
					,ISDISPLAYIMMEDIATE	
					,payload_qualificationStoreGroups_redemptionStoreGroups
					,PAYLOAD_QUALIFICATIONTENDERTYPES
					,PAYLOAD_FULFILLMENTCHANNEL
					,PAYLOAD_ECOMMPROMOTYPE 					
					,payload_ecommPromoCode
					,payload_validWithOtherOffer
					,payload_orderCount
					,payload_firstTimeCustomerOnly
					,payload_autoApplyPromoCode
					,payload_notCombinableWith
					,PAYLOAD_SUBPROGRAMCODE
					,PAYLOAD_QUALIFICATIONBEHAVIOR
					,PAYLOAD_INITIALSUBSCRIPTIONOFFER
					,PAYLOAD_ISDYNAMICOFFER
					,PAYLOAD_DAYSTOREDEEM
				
   FROM (
              SELECT   ftab.filename 
					,ftab.PayloadPart 
					,ftab.PageNum 
					,ftab.TotalPages 
					,ftab.EntityId 
					,ftab.PayLoadType 
					,ftab.EntityType 
					,ftab.SourceAction 
					,ftab.payload_id 
					,ftab.payload_externalOfferId 
					,ftab.payload_offerRequestId 
					,ftab.payload_aggregatorOfferId 
					,ftab.payload_manufacturerId 
					,ftab.payload_manufacturerOfferRefCd 
					,ftab.payload_providerName 
					,ftab.payload_categories_additionalProperties 
					,ftab.payload_primaryCategory_additionalProperties 
					,ftab.payload_events_additionalProperties 
					,ftab.payload_hiddenEvents_additionalProperties 
					,ftab.payload_programCode 
					,ftab.payload_programCodeDesc 
					,ftab.payload_subProgram 
					,ftab.payload_subProgramDesc 
					,ftab.payload_deliveryChannel 
					,ftab.payload_deliveryChannelDesc 
					,ftab.payload_status 
					,ftab.payload_statusDesc 
					,ftab.payload_priceTitle 
					,ftab.payload_priceValue 
					,ftab.payload_savingsValueText 
					,ftab.payload_titleDescription_additionalProperties 
					,ftab.payload_productDescription_additionalProperties 
					,ftab.payload_disclaimerText 
					,ftab.payload_description 
					,ftab.payload_printTags 
					,ftab.payload_productImageId 
					,ftab.payload_priceCode 
					,ftab.payload_time 
					,ftab.payload_year 
					,ftab.payload_productCd 
					,ftab.payload_isEmployeeOffer 
					,ftab.payload_isDefaultAllocationOffer 
					,ftab.payload_programType 
					,ftab.payload_shouldReportRedemptions 
					,ftab.payload_createdTs 
					,ftab.payload_createdApplicationId 
					,ftab.payload_createdUserId 
					,ftab.payload_lastUpdatedApplicationId 
					,ftab.payload_lastUpdatedUserId 
					,ftab.payload_lastUpdatedTs 
					,ftab.payload_displayEffectiveStartDate 
					,ftab.payload_displayEffectiveEndDate 
					,ftab.payload_effectiveStartDate 
					,ftab.payload_effectiveEndDate 
					,ftab.payload_testEffectiveStartDate 
					,ftab.payload_testEffectiveEndDate 
					,ftab.payload_postalCodes 
					,ftab.payload_terminals 
					,ftab.payload_excludedTerminals 
					,ftab.payload_qualificationUnitType 
					,ftab.payload_qualificationUnitSubType 
					,ftab.payload_benefitValueType 
					,ftab.payload_usageLimitTypePerUser 
					,ftab.payload_pluTriggerBarcode 
					,ftab.payload_copientCategory 
					,ftab.payload_engine 
					,ftab.payload_priority 
					,ftab.payload_tiers 
					,ftab.payload_sendOutboundData 
					,ftab.payload_chargebackVendor 
					,ftab.payload_autoTransferable 
					,ftab.payload_enableIssuance 
					,ftab.payload_deferEvaluationUntilEOS 
					,ftab.payload_enableImpressionReporting 
					,ftab.payload_limitEligibilityFrequency 
					,ftab.payload_isApplicableToJ4U 
					,ftab.payload_customerSegment 
					,ftab.payload_assignment_userId 
					,ftab.payload_assignment_firstName 
					,ftab.payload_assignment_lastName 
					,ftab.payload_qualificationProductGroups 
					,ftab.payload_qualificationCustomergroups 
					,ftab.payload_qualificationPointsGroups 
					,ftab.payload_testStoreGroups 
					,ftab.payload_testCustomerGroups 
					,ftab.payload_benefit_benefitValueType 
					,ftab.payload_benefit_benefitValueDesc 
					,ftab.payload_benefit_benefitValue 
					,ftab.payload_benefit_discount 
					,ftab.payload_benefit_points 
					,ftab.payload_benefit_groupMemberShip_customerGroupName 
					,ftab.payload_benefit_printedMessage_message 
					,ftab.payload_benefit_printedMessage_isApplicableForNotifications 
					,ftab.payload_benefit_cashierMessage_cashierMessageTiers 
					,ftab.payload_benefit_cashierMessage_isApplicableForNotifications 
					,ftab.payload_qualificationStoreGroups_podStoreGroups 
					,ftab.payload_qualificationStoreGroups_nonDigitalRedemptionStoreGroups 
					,ftab.payload_qualificationStoreGroups_digitalRedemptionStoreGroups 
					,ftab.payload_qualificationProductDisQualifier 
					,ftab.payload_qualificationDay_monday 
					,ftab.payload_qualificationDay_tuesday 
					,ftab.payload_qualificationDay_wednesday 
					,ftab.payload_qualificationDay_thursday 
					,ftab.payload_qualificationDay_friday 
					,ftab.payload_qualificationDay_saturday 
					,ftab.payload_qualificationDay_sunday 
					,ftab.payload_qualificationTime_start 
					,ftab.payload_qualificationTime_end 
					,ftab.payload_qualificationEnterpriseInstantWin_numberOfPrizes 
					,ftab.payload_qualificationEnterpriseInstantWin_frequency 
					,ftab.payload_qualificationTriggerCodes 
					,ftab.payload_qualificationAttributes 
					,ftab.payload_nopaNumbers 
					,ftab.payload_offerName 
					,ftab.payload_adType 
					,ftab.payload_offerProtoType 
					,ftab.payload_offerPrototypeDesc 
					,ftab.payload_storeGroupVersionId 
					,ftab.payload_storeTag_printJ4uTagEnabled 
					,ftab.payload_storeTag_multiple 
					,ftab.payload_storeTag_amount 
					,ftab.payload_storeTag_comments 
					,ftab.payload_requestedRemovalForAll 
					,ftab.payload_removedOn 
					,ftab.payload_removedUnclippedOn 
					,ftab.payload_removedForAllOn 
					,ftab.payload_brandNSize 
					,ftab.payload_createdUser_userId 
					,ftab.payload_createdUser_firstName 
					,ftab.payload_createdUser_lastName 
					,ftab.payload_updatedUser_userId 
					,ftab.payload_updatedUser_firstName 
					,ftab.payload_updatedUser_lastName 
					,ftab.payload_firstUpdateToRedemptionEngine 
					,ftab.payload_lastUpdateToRedemptionEngine 
					,ftab.payload_firstUpdateToJ4U 
					,ftab.payload_lastUpdateToJ4U 
					,ftab.payload_offerRequestorGroup 
					,ftab.payload_headLine 
					,ftab.payload_isPODApproved 
					,ftab.payload_podUsageLimitTypePerUser 
					,ftab.payload_podReferenceOfferId 
					,ftab.payload_ivieImageId 
					,ftab.payload_vehicleNm 
					,ftab.payload_adPageNbr 
					,ftab.payload_adModNbr 
					,ftab.payload_ecomDesc 
					,ftab.payload_requestedUser_userId 
					,ftab.payload_requestedUser_firstName 
					,ftab.payload_requestedUser_lastName 
					,ftab.payload_isPrimaryPODOffer 
					,ftab.lastUpdateTs 
					,ftab.DW_CREATE_TS
					,ftab.PAYLOAD_PRODUCT_DESCPRODDSC1
					,ftab.PAYLOAD_PRODUCT_DESCPRODDSC2
					,ftab.PAYLOAD_TITLE_DESCTITLEDSC1
					,ftab.PAYLOAD_TITLE_DESCTITLEDSC2
					,ftab.PAYLOAD_TITLE_DESCTITLEDSC3
					,ftab.payload_redemptionSystemId
					,ftab.payload_events
                    ,ftab.payload_regionIdMap
					,ftab.payload_usageLimitPerUser 
					,ftab.payload_customPeriod 
					,ftab.payload_customType 
					,ftab.QUALIFICATIONPRODUCTDISQUALIFIERNAME
					,ftab.ISDISPLAYIMMEDIATE	
					,ftab.payload_qualificationStoreGroups_redemptionStoreGroups
					,ftab.PAYLOAD_QUALIFICATIONTENDERTYPES
					,ftab.PAYLOAD_FULFILLMENTCHANNEL
					,ftab.PAYLOAD_ECOMMPROMOTYPE 
					,ftab.payload_ecommPromoCode
					,ftab.payload_validWithOtherOffer
					,ftab.payload_orderCount
					,ftab.payload_firstTimeCustomerOnly
					,ftab.payload_autoApplyPromoCode
					,ftab.payload_notCombinableWith
					,ftab.PAYLOAD_SUBPROGRAMCODE
					,ftab.PAYLOAD_QUALIFICATIONBEHAVIOR
					,ftab.PAYLOAD_INITIALSUBSCRIPTIONOFFER
					,ftab.PAYLOAD_ISDYNAMICOFFER
					,ftab.PAYLOAD_DAYSTOREDEEM
                            ,row_number() over(PARTITION BY ftab.payload_id ORDER BY to_timestamp_ntz(ftab.lastUpdateTs) desc) as rn
			         FROM ` + src_flat_strm  +`  str
                     inner join ` + src_flat_table  +` ftab on str.payload_id=ftab.payload_id
                         WHERE   str.payload_id is not null
						
                            
					) where rn = 1 
                       )src
					LEFT JOIN
					(
					SELECT filename 
					,PayloadPart 
					,PageNum 
					,TotalPages 
					,EntityId 
					,PayLoadType 
					,EntityType 
					,SourceAction 
					,payload_id 
					,payload_externalOfferId 
					,payload_offerRequestId 
					,payload_aggregatorOfferId 
					,payload_manufacturerId 
					,payload_manufacturerOfferRefCd 
					,payload_providerName 
					,payload_categories_additionalProperties 
					,payload_primaryCategory_additionalProperties 
					,payload_events_additionalProperties 
					,payload_hiddenEvents_additionalProperties 
					,payload_programCode 
					,payload_programCodeDesc 
					,payload_subProgram 
					,payload_subProgramDesc 
					,payload_deliveryChannel 
					,payload_deliveryChannelDesc 
					,payload_status 
					,payload_statusDesc 
					,payload_priceTitle 
					,payload_priceValue 
					,payload_savingsValueText 
					,payload_titleDescription_additionalProperties 
					,payload_productDescription_additionalProperties 
					,payload_disclaimerText 
					,payload_description 
					,payload_printTags 
					,payload_productImageId 
					,payload_priceCode 
					,payload_time 
					,payload_year 
					,payload_productCd 
					,payload_isEmployeeOffer 
					,payload_isDefaultAllocationOffer 
					,payload_programType 
					,payload_shouldReportRedemptions 
					,payload_createdTs 
					,payload_createdApplicationId 
					,payload_createdUserId 
					,payload_lastUpdatedApplicationId 
					,payload_lastUpdatedUserId 
					,payload_lastUpdatedTs 
					,payload_displayEffectiveStartDate 
					,payload_displayEffectiveEndDate 
					,payload_effectiveStartDate 
					,payload_effectiveEndDate 
					,payload_testEffectiveStartDate 
					,payload_testEffectiveEndDate 
					,payload_postalCodes 
					,payload_terminals 
					,payload_excludedTerminals 
					,payload_qualificationUnitType 
					,payload_qualificationUnitSubType 
					,payload_benefitValueType 
					,payload_usageLimitTypePerUser 
					,payload_pluTriggerBarcode 
					,payload_copientCategory 
					,payload_engine 
					,payload_priority 
					,payload_tiers 
					,payload_sendOutboundData 
					,payload_chargebackVendor 
					,payload_autoTransferable 
					,payload_enableIssuance 
					,payload_deferEvaluationUntilEOS 
					,payload_enableImpressionReporting 
					,payload_limitEligibilityFrequency 
					,payload_isApplicableToJ4U 
					,payload_customerSegment 
					,payload_assignment_userId 
					,payload_assignment_firstName 
					,payload_assignment_lastName 
					,payload_qualificationProductGroups 
					,payload_qualificationCustomergroups 
					,payload_qualificationPointsGroups 
					,payload_testStoreGroups 
					,payload_testCustomerGroups 
					,payload_benefit_benefitValueType 
					,payload_benefit_benefitValueDesc 
					,payload_benefit_benefitValue 
					,payload_benefit_discount 
					,payload_benefit_points 
					,payload_benefit_groupMemberShip_customerGroupName 
					,payload_benefit_printedMessage_message 
					,payload_benefit_printedMessage_isApplicableForNotifications 
					,payload_benefit_cashierMessage_cashierMessageTiers 
					,payload_benefit_cashierMessage_isApplicableForNotifications 
					,payload_qualificationStoreGroups_podStoreGroups 
					,payload_qualificationStoreGroups_nonDigitalRedemptionStoreGroups 
					,payload_qualificationStoreGroups_digitalRedemptionStoreGroups 
					,payload_qualificationProductDisQualifier 
					,payload_qualificationDay_monday 
					,payload_qualificationDay_tuesday 
					,payload_qualificationDay_wednesday 
					,payload_qualificationDay_thursday 
					,payload_qualificationDay_friday 
					,payload_qualificationDay_saturday 
					,payload_qualificationDay_sunday 
					,payload_qualificationTime_start 
					,payload_qualificationTime_end 
					,payload_qualificationEnterpriseInstantWin_numberOfPrizes 
					,payload_qualificationEnterpriseInstantWin_frequency 
					,payload_qualificationTriggerCodes 
					,payload_qualificationAttributes 
					,payload_nopaNumbers 
					,payload_offerName 
					,payload_adType 
					,payload_offerProtoType 
					,payload_offerPrototypeDesc 
					,payload_storeGroupVersionId 
					,payload_storeTag_printJ4uTagEnabled 
					,payload_storeTag_multiple 
					,payload_storeTag_amount 
					,payload_storeTag_comments 
					,payload_requestedRemovalForAll 
					,payload_removedOn 
					,payload_removedUnclippedOn 
					,payload_removedForAllOn 
					,payload_brandNSize 
					,payload_createdUser_userId 
					,payload_createdUser_firstName 
					,payload_createdUser_lastName 
					,payload_updatedUser_userId 
					,payload_updatedUser_firstName 
					,payload_updatedUser_lastName 
					,payload_firstUpdateToRedemptionEngine 
					,payload_lastUpdateToRedemptionEngine 
					,payload_firstUpdateToJ4U 
					,payload_lastUpdateToJ4U 
					,payload_offerRequestorGroup 
					,payload_headLine 
					,payload_isPODApproved 
					,payload_podUsageLimitTypePerUser 
					,payload_podReferenceOfferId 
					,payload_ivieImageId 
					,payload_vehicleNm 
					,payload_adPageNbr 
					,payload_adModNbr 
					,payload_ecomDesc 
					,payload_requestedUser_userId 
					,payload_requestedUser_firstName 
					,payload_requestedUser_lastName 
					,payload_isPrimaryPODOffer 
					,lastUpdateTs 
					,DW_CREATE_TS
					,PAYLOAD_PRODUCT_DESCPRODDSC1
					,PAYLOAD_PRODUCT_DESCPRODDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC1
					,PAYLOAD_TITLE_DESCTITLEDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC3
                    ,payload_redemptionSystemId
                    ,payload_events
                    ,payload_regionIdMap
					,payload_usageLimitPerUser 
					,payload_customPeriod 
					,payload_customType 
					,QUALIFICATIONPRODUCTDISQUALIFIERNAME
					,ISDISPLAYIMMEDIATE	
					,payload_qualificationStoreGroups_redemptionStoreGroups
					,PAYLOAD_QUALIFICATIONTENDERTYPES
					,PAYLOAD_FULFILLMENTCHANNEL
					,PAYLOAD_ECOMMPROMOTYPE 
					,payload_ecommPromoCode
					,payload_validWithOtherOffer
					,payload_orderCount
					,payload_firstTimeCustomerOnly
					,payload_autoApplyPromoCode
					,payload_notCombinableWith
					,PAYLOAD_SUBPROGRAMCODE
					,PAYLOAD_QUALIFICATIONBEHAVIOR
					,PAYLOAD_INITIALSUBSCRIPTIONOFFER
					,PAYLOAD_ISDYNAMICOFFER
					,PAYLOAD_DAYSTOREDEEM
				
					FROM ` + tgt_tbl + `
          ) tgt on src.payload_id  = tgt.payload_id 
		  `;

		    try {
        snowflake.execute ( 
            {sqlText: wrk_tbl  }
        );
    }
    catch (err)  { 
    return "Creation of OfferOMS_Flat tgt_wrk_tbl table  Failed with error: " + err;   // Return a error message.
    }
    
   
 var delete_duplicate = `DELETE FROM ` + tgt_tbl + ` WHERE payload_id IN (SELECT payload_id FROM `+ tgt_wrk_tbl +`)`;
                      
							
	var sql_begin = "BEGIN"
    // Processing Inserts
    var sql_inserts = `insert INTO ` + tgt_tbl + `
	               (filename 
					,PayloadPart 
					,PageNum 
					,TotalPages 
					,EntityId 
					,PayLoadType 
					,EntityType 
					,SourceAction 
					,payload_id 
					,payload_externalOfferId 
					,payload_offerRequestId 
					,payload_aggregatorOfferId 
					,payload_manufacturerId 
					,payload_manufacturerOfferRefCd 
					,payload_providerName 
					,payload_categories_additionalProperties 
					,payload_primaryCategory_additionalProperties 
					,payload_events_additionalProperties 
					,payload_hiddenEvents_additionalProperties 
					,payload_programCode 
					,payload_programCodeDesc 
					,payload_subProgram 
					,payload_subProgramDesc 
					,payload_deliveryChannel 
					,payload_deliveryChannelDesc 
					,payload_status 
					,payload_statusDesc 
					,payload_priceTitle 
					,payload_priceValue 
					,payload_savingsValueText 
					,payload_titleDescription_additionalProperties 
					,payload_productDescription_additionalProperties 
					,payload_disclaimerText 
					,payload_description 
					,payload_printTags 
					,payload_productImageId 
					,payload_priceCode 
					,payload_time 
					,payload_year 
					,payload_productCd 
					,payload_isEmployeeOffer 
					,payload_isDefaultAllocationOffer 
					,payload_programType 
					,payload_shouldReportRedemptions 
					,payload_createdTs 
					,payload_createdApplicationId 
					,payload_createdUserId 
					,payload_lastUpdatedApplicationId 
					,payload_lastUpdatedUserId 
					,payload_lastUpdatedTs 
					,payload_displayEffectiveStartDate 
					,payload_displayEffectiveEndDate 
					,payload_effectiveStartDate 
					,payload_effectiveEndDate 
					,payload_testEffectiveStartDate 
					,payload_testEffectiveEndDate 
					,payload_postalCodes 
					,payload_terminals 
					,payload_excludedTerminals 
					,payload_qualificationUnitType 
					,payload_qualificationUnitSubType 
					,payload_benefitValueType 
					,payload_usageLimitTypePerUser 
					,payload_pluTriggerBarcode 
					,payload_copientCategory 
					,payload_engine 
					,payload_priority 
					,payload_tiers 
					,payload_sendOutboundData 
					,payload_chargebackVendor 
					,payload_autoTransferable 
					,payload_enableIssuance 
					,payload_deferEvaluationUntilEOS 
					,payload_enableImpressionReporting 
					,payload_limitEligibilityFrequency 
					,payload_isApplicableToJ4U 
					,payload_customerSegment 
					,payload_assignment_userId 
					,payload_assignment_firstName 
					,payload_assignment_lastName 
					,payload_qualificationProductGroups 
					,payload_qualificationCustomergroups 
					,payload_qualificationPointsGroups 
					,payload_testStoreGroups 
					,payload_testCustomerGroups 
					,payload_benefit_benefitValueType 
					,payload_benefit_benefitValueDesc 
					,payload_benefit_benefitValue 
					,payload_benefit_discount 
					,payload_benefit_points 
					,payload_benefit_groupMemberShip_customerGroupName 
					,payload_benefit_printedMessage_message 
					,payload_benefit_printedMessage_isApplicableForNotifications 
					,payload_benefit_cashierMessage_cashierMessageTiers 
					,payload_benefit_cashierMessage_isApplicableForNotifications 
					,payload_qualificationStoreGroups_podStoreGroups 
					,payload_qualificationStoreGroups_nonDigitalRedemptionStoreGroups 
					,payload_qualificationStoreGroups_digitalRedemptionStoreGroups 
					,payload_qualificationProductDisQualifier 
					,payload_qualificationDay_monday 
					,payload_qualificationDay_tuesday 
					,payload_qualificationDay_wednesday 
					,payload_qualificationDay_thursday 
					,payload_qualificationDay_friday 
					,payload_qualificationDay_saturday 
					,payload_qualificationDay_sunday 
					,payload_qualificationTime_start 
					,payload_qualificationTime_end 
					,payload_qualificationEnterpriseInstantWin_numberOfPrizes 
					,payload_qualificationEnterpriseInstantWin_frequency 
					,payload_qualificationTriggerCodes 
					,payload_qualificationAttributes 
					,payload_nopaNumbers 
					,payload_offerName 
					,payload_adType 
					,payload_offerProtoType 
					,payload_offerPrototypeDesc 
					,payload_storeGroupVersionId 
					,payload_storeTag_printJ4uTagEnabled 
					,payload_storeTag_multiple 
					,payload_storeTag_amount 
					,payload_storeTag_comments 
					,payload_requestedRemovalForAll 
					,payload_removedOn 
					,payload_removedUnclippedOn 
					,payload_removedForAllOn 
					,payload_brandNSize 
					,payload_createdUser_userId 
					,payload_createdUser_firstName 
					,payload_createdUser_lastName 
					,payload_updatedUser_userId 
					,payload_updatedUser_firstName 
					,payload_updatedUser_lastName 
					,payload_firstUpdateToRedemptionEngine 
					,payload_lastUpdateToRedemptionEngine 
					,payload_firstUpdateToJ4U 
					,payload_lastUpdateToJ4U 
					,payload_offerRequestorGroup 
					,payload_headLine 
					,payload_isPODApproved 
					,payload_podUsageLimitTypePerUser 
					,payload_podReferenceOfferId 
					,payload_ivieImageId 
					,payload_vehicleNm 
					,payload_adPageNbr 
					,payload_adModNbr 
					,payload_ecomDesc 
					,payload_requestedUser_userId 
					,payload_requestedUser_firstName 
					,payload_requestedUser_lastName 
					,payload_isPrimaryPODOffer 
					,lastUpdateTs 
					,DW_CREATE_TS
					,PAYLOAD_PRODUCT_DESCPRODDSC1
					,PAYLOAD_PRODUCT_DESCPRODDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC1
					,PAYLOAD_TITLE_DESCTITLEDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC3
					,payload_redemptionSystemId
					,payload_events
                    ,payload_regionIdMap
					,payload_usageLimitPerUser 
					,payload_customPeriod 
					,payload_customType 
					,QUALIFICATIONPRODUCTDISQUALIFIERNAME
					,ISDISPLAYIMMEDIATE	
					,payload_qualificationStoreGroups_redemptionStoreGroups
					,PAYLOAD_QUALIFICATIONTENDERTYPES
					,PAYLOAD_FULFILLMENTCHANNEL
					,PAYLOAD_ECOMMPROMOTYPE 
					,payload_ecommPromoCode
					,payload_validWithOtherOffer
					,payload_orderCount
					,payload_firstTimeCustomerOnly
					,payload_autoApplyPromoCode
					,payload_notCombinableWith
					,PAYLOAD_SUBPROGRAMCODE
					,PAYLOAD_QUALIFICATIONBEHAVIOR
					,PAYLOAD_INITIALSUBSCRIPTIONOFFER
					,PAYLOAD_ISDYNAMICOFFER
					,PAYLOAD_DAYSTOREDEEM
					)
				Select 
                     filename 
					,PayloadPart 
					,PageNum 
					,TotalPages 
					,EntityId 
					,PayLoadType 
					,EntityType 
					,SourceAction 
					,payload_id 
					,payload_externalOfferId 
					,payload_offerRequestId 
					,payload_aggregatorOfferId 
					,payload_manufacturerId 
					,payload_manufacturerOfferRefCd 
					,payload_providerName 
					,payload_categories_additionalProperties 
					,payload_primaryCategory_additionalProperties 
					,payload_events_additionalProperties 
					,payload_hiddenEvents_additionalProperties 
					,payload_programCode 
					,payload_programCodeDesc 
					,payload_subProgram 
					,payload_subProgramDesc 
					,payload_deliveryChannel 
					,payload_deliveryChannelDesc 
					,payload_status 
					,payload_statusDesc 
					,payload_priceTitle 
					,payload_priceValue 
					,payload_savingsValueText 
					,payload_titleDescription_additionalProperties 
					,payload_productDescription_additionalProperties 
					,payload_disclaimerText 
					,payload_description 
					,payload_printTags 
					,payload_productImageId 
					,payload_priceCode 
					,payload_time 
					,payload_year 
					,payload_productCd 
					,payload_isEmployeeOffer 
					,payload_isDefaultAllocationOffer 
					,payload_programType 
					,payload_shouldReportRedemptions 
					,payload_createdTs 
					,payload_createdApplicationId 
					,payload_createdUserId 
					,payload_lastUpdatedApplicationId 
					,payload_lastUpdatedUserId 
					,payload_lastUpdatedTs 
					,payload_displayEffectiveStartDate 
					,payload_displayEffectiveEndDate 
					,payload_effectiveStartDate 
					,payload_effectiveEndDate 
					,payload_testEffectiveStartDate 
					,payload_testEffectiveEndDate 
					,payload_postalCodes 
					,payload_terminals 
					,payload_excludedTerminals 
					,payload_qualificationUnitType 
					,payload_qualificationUnitSubType 
					,payload_benefitValueType 
					,payload_usageLimitTypePerUser 
					,payload_pluTriggerBarcode 
					,payload_copientCategory 
					,payload_engine 
					,payload_priority 
					,payload_tiers 
					,payload_sendOutboundData 
					,payload_chargebackVendor 
					,payload_autoTransferable 
					,payload_enableIssuance 
					,payload_deferEvaluationUntilEOS 
					,payload_enableImpressionReporting 
					,payload_limitEligibilityFrequency 
					,payload_isApplicableToJ4U 
					,payload_customerSegment 
					,payload_assignment_userId 
					,payload_assignment_firstName 
					,payload_assignment_lastName 
					,payload_qualificationProductGroups 
					,payload_qualificationCustomergroups 
					,payload_qualificationPointsGroups 
					,payload_testStoreGroups 
					,payload_testCustomerGroups 
					,payload_benefit_benefitValueType 
					,payload_benefit_benefitValueDesc 
					,payload_benefit_benefitValue 
					,payload_benefit_discount 
					,payload_benefit_points 
					,payload_benefit_groupMemberShip_customerGroupName 
					,payload_benefit_printedMessage_message 
					,payload_benefit_printedMessage_isApplicableForNotifications 
					,payload_benefit_cashierMessage_cashierMessageTiers 
					,payload_benefit_cashierMessage_isApplicableForNotifications 
					,payload_qualificationStoreGroups_podStoreGroups 
					,payload_qualificationStoreGroups_nonDigitalRedemptionStoreGroups 
					,payload_qualificationStoreGroups_digitalRedemptionStoreGroups 
					,payload_qualificationProductDisQualifier 
					,payload_qualificationDay_monday 
					,payload_qualificationDay_tuesday 
					,payload_qualificationDay_wednesday 
					,payload_qualificationDay_thursday 
					,payload_qualificationDay_friday 
					,payload_qualificationDay_saturday 
					,payload_qualificationDay_sunday 
					,payload_qualificationTime_start 
					,payload_qualificationTime_end 
					,payload_qualificationEnterpriseInstantWin_numberOfPrizes 
					,payload_qualificationEnterpriseInstantWin_frequency 
					,payload_qualificationTriggerCodes 
					,payload_qualificationAttributes 
					,payload_nopaNumbers 
					,payload_offerName 
					,payload_adType 
					,payload_offerProtoType 
					,payload_offerPrototypeDesc 
					,payload_storeGroupVersionId 
					,payload_storeTag_printJ4uTagEnabled 
					,payload_storeTag_multiple 
					,payload_storeTag_amount 
					,payload_storeTag_comments 
					,payload_requestedRemovalForAll 
					,payload_removedOn 
					,payload_removedUnclippedOn 
					,payload_removedForAllOn 
					,payload_brandNSize 
					,payload_createdUser_userId 
					,payload_createdUser_firstName 
					,payload_createdUser_lastName 
					,payload_updatedUser_userId 
					,payload_updatedUser_firstName 
					,payload_updatedUser_lastName 
					,payload_firstUpdateToRedemptionEngine 
					,payload_lastUpdateToRedemptionEngine 
					,payload_firstUpdateToJ4U 
					,payload_lastUpdateToJ4U 
					,payload_offerRequestorGroup 
					,payload_headLine 
					,payload_isPODApproved 
					,payload_podUsageLimitTypePerUser 
					,payload_podReferenceOfferId 
					,payload_ivieImageId 
					,payload_vehicleNm 
					,payload_adPageNbr 
					,payload_adModNbr 
					,payload_ecomDesc 
					,payload_requestedUser_userId 
					,payload_requestedUser_firstName 
					,payload_requestedUser_lastName 
					,payload_isPrimaryPODOffer 
					,lastUpdateTs 
					,DW_CREATE_TS
					,PAYLOAD_PRODUCT_DESCPRODDSC1
					,PAYLOAD_PRODUCT_DESCPRODDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC1
					,PAYLOAD_TITLE_DESCTITLEDSC2
					,PAYLOAD_TITLE_DESCTITLEDSC3
                    ,payload_redemptionSystemId	
                    ,payload_events
                    ,payload_regionIdMap
					,payload_usageLimitPerUser 
					,payload_customPeriod 
					,payload_customType 
					,QUALIFICATIONPRODUCTDISQUALIFIERNAME
					,ISDISPLAYIMMEDIATE	
					,payload_qualificationStoreGroups_redemptionStoreGroups
					,PAYLOAD_QUALIFICATIONTENDERTYPES
					,PAYLOAD_FULFILLMENTCHANNEL
					,PAYLOAD_ECOMMPROMOTYPE 
					,payload_ecommPromoCode
					,payload_validWithOtherOffer
					,payload_orderCount
					,payload_firstTimeCustomerOnly
					,payload_autoApplyPromoCode
					,payload_notCombinableWith
					,PAYLOAD_SUBPROGRAMCODE
					,PAYLOAD_QUALIFICATIONBEHAVIOR
					,PAYLOAD_INITIALSUBSCRIPTIONOFFER
					,PAYLOAD_ISDYNAMICOFFER
					,PAYLOAD_DAYSTOREDEEM
							from `+ tgt_wrk_tbl +` 
							`;
                      
    var sql_commit = "COMMIT"
    var sql_rollback = "ROLLBACK"
    try {
       snowflake.execute (
            {sqlText: sql_begin}
        );
        snowflake.execute(
			{sqlText: delete_duplicate}
			);              
        snowflake.execute (
            {sqlText: sql_inserts}
        );
        snowflake.execute (
            {sqlText: sql_commit}
        );    
    }
    catch (err) {
        snowflake.execute (
            {sqlText: sql_rollback}
        );
         return "Loading of "  + tgt_tbl + " Failed with error: " + err;   // Return a error message.
    }
            // **************        Load for OfferOMS_Flat  ENDs *****************
 return "Done"
 
 $$;
