--liquibase formatted sql
--changeset SYSTEM:EPE_OMS_OFFER_COPY_PAYLOAD_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME_OUT>>;
use schema <<EDM_DB_NAME_OUT>>.DW_APPL;

CREATE OR REPLACE TASK EPE_OMS_OFFER_COPY_PAYLOAD_TASK
WAREHOUSE='PROD_INGESTION_SMALL_WH'
SCHEDULE='1 minute'
WHEN SYSTEM$STREAM_HAS_DATA('EPE_OMS_OFFER_JSON_O_STREAM')
AS CALL SP_EPE_OMS_OFFER_COPY_PAYLOAD();

ALTER TASK EPE_OMS_OFFER_COPY_PAYLOAD_TASK RESUME;
