--liquibase formatted sql
--changeset SYSTEM:ESED_OfferOMS_R_TASK runOnChange:true splitStatements:false OBJECT_TYPE:TASK
use database <<EDM_DB_NAME_R>>;
use schema <<EDM_DB_NAME_R>>.DW_APPL;

CREATE OR REPLACE TASK ESED_OFFEROMS_R_TASK
WAREHOUSE='PROD_INGESTION_BIG_WH'
SCHEDULE='1 minutes'
WHEN SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME_R>>.DW_APPL.ESED_OfferOMS_R_STREAM')
AS call SP_OFFEROMS_TO_FLAT_LOAD();

ALTER TASK ESED_OFFEROMS_R_TASK RESUME;
