--liquibase formatted sql
--changeset SYSTEM:OMS_PRODUCT_GROUP_DEPARTMENT_SECTION runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_PRODUCT;

create or replace TABLE OMS_PRODUCT_GROUP_DEPARTMENT_SECTION (
	PRODUCT_GROUP_ID NUMBER(38,0) NOT NULL,
	SECTION_CD VARCHAR(20) NOT NULL,
	DW_FIRST_EFFECTIVE_TS TIMESTAMP_LTZ(9) NOT NULL,
	DW_LAST_EFFECTIVE_TS TIMESTAMP_LTZ(9) NOT NULL,
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	primary key (PRODUCT_GROUP_ID, SECTION_CD, DW_FIRST_EFFECTIVE_TS, DW_LAST_EFFECTIVE_TS)
)COMMENT='This table contains information about OMS_PRODUCT_GROUP_DEPARTMENT_SECTION'
;
