--liquibase formatted sql
--changeset SYSTEM:OMS_Product_Group_Upc runOnChange:true splitStatements:false OBJECT_TYPE:VIEW
use database <<EDM_VIEW_NAME>>;
use schema <<EDM_VIEW_NAME>>.DW_VIEWS;

create or replace view OMS_PRODUCT_GROUP_UPC(
	PRODUCT_GROUP_ID COMMENT 'Product Group Primary Key.',
	UPC_CD COMMENT 'UPC number e.g: 3520450097',
	DW_FIRST_EFFECTIVE_TS COMMENT 'The date the record was inserted. For update Primary Keys this values is used from the prior record of the primary key',
	DW_LAST_EFFECTIVE_TS COMMENT 'for the current record this is 12/31/9999. for updated records based on the primary key of the table, this is the new current records',
	UPC_VERSION_TXT COMMENT 'Text Description of UPC version',
	UPC_DSC COMMENT 'Description of UPC',
	LIST_TYPE_DSC COMMENT 'description of type of UPC e.g: suggested, final..',
	ORIGIN_DSC COMMENT 'represents how this specific UPC is originated, whether it is \"Original/Added/Removed\"',
	STATUS_DSC COMMENT 'UPC status \"accepted/review\"',
	GROUP_ID COMMENT 'UPC group Id, e.g: \"95\"',
	GROUP_NM COMMENT 'UPC group name e.g: \"IN-STORE SWEET BAKED GOODS\"',
	BRAND_ID COMMENT 'UPC brnad Id, e.g: \"95221\"',
	BRAND_NM COMMENT 'UPC brand name, e.g: \"Mc Bakers\"',
	CATEGORY_ID COMMENT 'UPC category id, e.g: \"9501\"',
	CATEGORY_DSC COMMENT 'UPC category description, e.g: \"ISB DESERTS\"',
	MANUFACTURER_CD COMMENT 'UPC manufacturer code, e.g: \"10374\"',
	ITEM_QTY COMMENT 'UPC qty, e.g: 1/2…',
	ITEM_UOM_CD COMMENT 'Unit of measurement of the UPC, e.g: \"EA/LB\"',
	ITEM_PRICE_AMT COMMENT 'Average price of the UPC',
	ITEM_SCORE_NBR COMMENT 'UPC expansion score reference to similarity of the origin UPC, score 100 is perfect match, 400 is distant match',
	CREATE_TS COMMENT 'UPC added date time, e.g: \"2021-08-01T03:48:40.712Z\"',
	UPDATE_TS COMMENT 'UPC updated date time, e.g: \"2021-08-01T03:48:40.712Z\"',
	CREATE_USER_ID COMMENT 'Overall product group created or updated user id, e.g: \"rkasi01\"',
	UPDATE_USER_ID COMMENT 'User ID of the user who created or updated this product group',
	DW_CREATE_TS COMMENT 'The timestamp the record was inserted.',
	DW_LAST_UPDATE_TS COMMENT 'When a record is updated this would be the current timestamp',
	DW_LOGICAL_DELETE_IND COMMENT 'Set to True when we receive a delete record for the primary key, else False',
	DW_SOURCE_CREATE_NM COMMENT 'The Bod (data source) name of this insert.',
	DW_SOURCE_UPDATE_NM COMMENT 'The Bod (data source) name of this update or delete.',
	DW_CURRENT_VERSION_IND COMMENT 'set to yes when the current record is deleted,  the Last Effective date on this record is still set to be  current date -1 d'
) COMMENT='VIEW for OMS_Product_Group_Upc'
 as
SELECT
Product_Group_Id,
Upc_Cd,
DW_First_Effective_TS,
DW_Last_Effective_TS,
Upc_Version_Txt,
Upc_Dsc,
List_Type_Dsc,
Origin_Dsc,
Status_Dsc,
Group_Id,
Group_Nm,
Brand_Id,
Brand_Nm,
Category_Id,
Category_Dsc,
Manufacturer_Cd,
Item_Qty,
Item_Uom_Cd,
Item_Price_Amt,
Item_Score_Nbr,
Create_Ts,
Update_Ts,
Create_User_Id,
Update_User_Id,
DW_CREATE_TS ,
DW_LAST_UPDATE_TS ,
DW_LOGICAL_DELETE_IND,
DW_SOURCE_CREATE_NM,
DW_SOURCE_UPDATE_NM,
DW_CURRENT_VERSION_IND
from <<EDM_DB_NAME>>.DW_C_PRODUCT.OMS_Product_Group_Upc;
