--liquibase formatted sql
--changeset SYSTEM:Business_Partner_Reward_Reconciliation_Error runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_LOYALTY;

create or replace TABLE BUSINESS_PARTNER_REWARD_RECONCILIATION_ERROR (
	RECONCILATION_ERROR_TYPE_CD VARCHAR(50) NOT NULL COMMENT 'Reconcilation Error Type Code',
	RECONCILATION_ERROR_TYPE_DSC VARCHAR(250) COMMENT 'Reconcilation Error Type Description',
	RECONCILATION_ERROR_TYPE_SHORT_DSC VARCHAR(50) COMMENT 'Reconcilation Error Type Short Description',
	TRANSACTION_ID VARCHAR(100) NOT NULL COMMENT 'Transaction Id',
	DW_FIRST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW First Effective Dt',
	DW_LAST_EFFECTIVE_DT DATE NOT NULL COMMENT 'DW Last Effective Dt',
	BUSINESS_PARTNER_INTEGRATION_ID NUMBER(38,0) NOT NULL COMMENT 'Business Partner Integration Id',
	TRANSACTION_TS TIMESTAMP_LTZ(9) NOT NULL COMMENT 'Transaction Ts',
	SEQUENCE_NBR NUMBER(38,0) NOT NULL COMMENT 'Sequence Nbr',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW CREATE TS',
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW LAST UPDATE TS',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW LOGICAL DELETE IND',
	DW_SOURCE_CREATE_NM VARCHAR(255) COMMENT 'DW SOURCE CREATE NM',
	DW_SOURCE_UPDATE_NM VARCHAR(255) COMMENT 'DW SOURCE UPDATE NM',
	DW_CURRENT_VERSION_IND BOOLEAN COMMENT 'DW CURRENT VERSION IND',
	primary key (TRANSACTION_ID, RECONCILATION_ERROR_TYPE_CD, DW_FIRST_EFFECTIVE_DT, DW_LAST_EFFECTIVE_DT, BUSINESS_PARTNER_INTEGRATION_ID, TRANSACTION_TS, SEQUENCE_NBR)
);
