--liquibase formatted sql
--changeset SYSTEM:Business_Partner_Reward_Reconciliation_Error_Exceptions runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

create or replace TABLE BUSINESS_PARTNER_REWARD_RECONCILIATION_ERROR_EXCEPTIONS (
	TRANSACTION_ID VARCHAR(16777216) COMMENT 'Transaction_Id',
	RECONCILATION_ERROR_TYPE_CD VARCHAR(16777216) COMMENT 'Reconcilation_Error_Type_Cd',
	BUSINESS_PARTNER_INTEGRATION_ID VARCHAR(16777216) COMMENT 'Business_Partner_Integration_Id',
	TRANSACTION_TS VARCHAR(16777216) COMMENT 'Transaction_Ts',
	SEQUENCE_NBR VARCHAR(16777216) COMMENT 'Sequence_Nbr',
	RECONCILATION_ERROR_TYPE_DSC VARCHAR(16777216) COMMENT 'Reconcilation_Error_Type_Dsc',
	RECONCILATION_ERROR_TYPE_SHORT_DSC VARCHAR(16777216) COMMENT 'Reconcilation_Error_Type_Short_Dsc',
	PARTNER_PARTICIPANT_ID VARCHAR(16777216) COMMENT 'Partner_Participant_Id',
	PARTNER_SITE_ID VARCHAR(16777216) COMMENT 'Partner_Site_Id  ',
	PARTNER_ID VARCHAR(16777216) COMMENT 'Partner_Id',
	FILENAME VARCHAR(16777216) COMMENT 'FileName',
	DW_LOGICAL_DELETE_IND BOOLEAN COMMENT 'DW_Logical_delete_ind',
	CREATIONDT VARCHAR(16777216) COMMENT 'CREATIONDT',
	DML_TYPE VARCHAR(5) COMMENT 'DML_Type',
	SAMEDAY_CHG_IND BOOLEAN COMMENT 'Sameday_chg_ind',
	EXCEPTION_REASON VARCHAR(1000) COMMENT 'EXCEPTION_REASON',
	DW_CREATE_TS TIMESTAMP_LTZ(9) COMMENT 'DW_CREATE_TS'
);
