--liquibase formatted sql
--changeset SYSTEM:OCGP_PROGRAM_ATTRIBUTE_FLAT_RERUN_AND_WRK runOnChange:true splitStatements:false OBJECT_TYPE:TABLE

USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA DW_C_STAGE;

create or replace TRANSIENT TABLE OCGP_PROGRAM_STORE_FLAT_RERUN (
	PROGRAM_CD VARCHAR(16777216),
	RETAIL_STORE_ID VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	DW_CREATETS TIMESTAMP_TZ(9),
	METADATA$ACTION VARCHAR(10),
	METADATA$ISUPDATE BOOLEAN,
	METADATA$ROW_ID VARCHAR(40)
);

create or replace TRANSIENT TABLE OCGP_PROGRAM_STORE_TMP_WRK (
	PROGRAM_CD VARCHAR(16777216),
	RETAIL_STORE_ID VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	DW_CREATETS TIMESTAMP_TZ(9),
	METADATA$ACTION VARCHAR(10),
	METADATA$ISUPDATE BOOLEAN,
	METADATA$ROW_ID VARCHAR(40)
);

create or replace TRANSIENT TABLE OCGP_PROGRAM_STORE_WRK (
	PROGRAM_CD VARCHAR(16777216),
	RETAIL_STORE_ID VARCHAR(16777216),
	FILENAME VARCHAR(16777216),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DML_TYPE VARCHAR(1),
  DW_CREATE_TS TIMESTAMP_TZ(9)
);
