--liquibase formatted sql
--changeset SYSTEM:Create_Work_Table runOnChange:true splitStatements:false OBJECT_TYPE:TABLE
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_C_STAGE;

//Work Table
create or replace TRANSIENT TABLE OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_HEADER_SAVINGS_WRK (
	TRANSACTION_INTEGRATION_ID NUMBER(38,0),
	OFFER_ID NUMBER(38,0),
	DW_FIRST_EFFECTIVE_DT DATE,
	DW_LAST_EFFECTIVE_DT DATE,
	SAVING_DSC VARCHAR(16777216),
	SOURCE_SYSTEM_CD VARCHAR(16777216),
	REDEMPTION_AMT NUMBER(38,5),
	REDEMPTION_CNT NUMBER(38,0),
	NON_DIGITAL_OFFER_IND BOOLEAN,
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	CALCULATE_USAGE_IND BOOLEAN,
	DISCOUNT_MESSAGE_TXT VARCHAR(16777216),
	NET_PROMOTION_AMT NUMBER(38,5),
	USAGE_CNT NUMBER(38,0),
	DISCOUNT_TYPE_TXT VARCHAR(16777216),
	DISCOUNT_LEVEL_TXT VARCHAR(16777216),
	SAVINGS_CATEGORY_ID NUMBER(38,0),
	SAVINGS_CATEGORY_NM VARCHAR(16777216),
	PROGRAM_CD VARCHAR(16777216),
	START_DT DATE,
	END_DT DATE,
	EXTERNAL_OFFER_ID VARCHAR(16777216),
	PROMO_CD VARCHAR(16777216),
	METADATA$ACTION VARCHAR(6),
	METADATA$ISUPDATE BOOLEAN,
	METADATA$ROW_ID VARCHAR(40)
);



create or replace TRANSIENT TABLE OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_STREAM_ITEM_SAVINGS_WRK (
	TRANSACTION_INTEGRATION_ID NUMBER(38,0),
	UPC_NBR NUMBER(38,0),
	DW_FIRST_EFFECTIVE_DT DATE,
	DW_LAST_EFFECTIVE_DT DATE,
	OFFER_ID NUMBER(38,0),
	ITEM_SEQUENCE_ID NUMBER(38,0),
	SAVINGS_CATEGORY_NM VARCHAR(16777216),
	DISCOUNT_MESSAGE_TXT VARCHAR(16777216),
	SOURCE_SYSTEM_CD VARCHAR(16777216),
	DISCOUNT_TYPE_TXT VARCHAR(16777216),
	DISCOUNT_DSC VARCHAR(16777216),
	DISCOUNT_LEVEL_TXT VARCHAR(16777216),
	SAVINGS_CATEGORY_ID NUMBER(38,0),
	MIN_PURCHASE_QTY NUMBER(9,2),
	DISCOUNT_AMT NUMBER(38,5),
	DISCOUNT_QTY NUMBER(9,2),
	NON_DIGITAL_OFFER_IND BOOLEAN,
	DW_CREATE_TS TIMESTAMP_LTZ(9),
	DW_LAST_UPDATE_TS TIMESTAMP_LTZ(9),
	DW_LOGICAL_DELETE_IND BOOLEAN,
	DW_SOURCE_CREATE_NM VARCHAR(255),
	DW_SOURCE_UPDATE_NM VARCHAR(255),
	DW_CURRENT_VERSION_IND BOOLEAN,
	CALCULATE_USAGE_IND BOOLEAN,
	NET_PROMOTION_AMT NUMBER(38,5),
	USAGE_CNT NUMBER(38,0),
	PROGRAM_CD VARCHAR(16777216),
	START_DT DATE,
	END_DT DATE,
	EXTERNAL_OFFER_ID VARCHAR(16777216),
	PROMO_CD VARCHAR(16777216),
	METADATA$ACTION VARCHAR(6),
	METADATA$ISUPDATE BOOLEAN,
	METADATA$ROW_ID VARCHAR(40)
);

create or replace TRANSIENT TABLE OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_WRK (
	STORE VARCHAR(16777216),
	LANE VARCHAR(16777216),
	TRANSACTION_NUMBER NUMBER(38,0),
	HHID NUMBER(38,0),
	REDEMPTION_COUNT NUMBER(38,0),
	REDEMPTION_AMOUNT NUMBER(10,2),
	POINTS_AMOUNT NUMBER(10,2),
	POINTS_PROGRAMNAME VARCHAR(16777216),
	TRANSACTION_DATE TIMESTAMP_TZ(9),
	OFFER_ID VARCHAR(16777216),
	OFFER_START_DATE DATE,
	OFFER_END_DATE DATE,
	CLIPS_TOTALCOLUMN NUMBER(18,0),
	REDEMPTION_TOTALCOLUMN NUMBER(18,0),
	MARKDOWN_TOTALCOLUMN NUMBER(38,2),
	DW_CREATE_TS TIMESTAMP_LTZ(9)
);
