--liquibase formatted sql
--changeset SYSTEM:Create_TASK runOnChange:true splitStatements:false OBJECT_TYPE:SP
use database <<EDM_DB_NAME>>;
use schema <<EDM_DB_NAME>>.DW_APPL;

//Create Task
CREATE OR REPLACE TASK OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Task
WAREHOUSE = '<<WH>>'
SCHEDULE = '1 minutes'
WHEN
SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_HEADER_SAVINGS')
AS
call <<EDM_DB_NAME>>.DW_APPL.SP_LOAD_OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY();

CREATE OR REPLACE TASK OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Task_Item
WAREHOUSE = '<<WH>>'
SCHEDULE = '1 minutes'
WHEN
SYSTEM$STREAM_HAS_DATA('<<EDM_DB_NAME>>.DW_APPL.OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_ITEM_SAVINGS')
AS
call <<EDM_DB_NAME>>.DW_APPL.SP_LOAD_OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY();

//Task Resume
ALTER task OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Task resume ;
ALTER task OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Task_Item resume ;
