--liquibase formatted sql
--changeset SYSTEM:Create_STREAM runOnChange:true splitStatements:false OBJECT_TYPE:STREAM
USE DATABASE <<EDM_DB_NAME>>;
USE SCHEMA <<EDM_DB_NAME>>.DW_APPL;


// Create Stream 
CREATE OR REPLACE STREAM OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_HEADER_SAVINGS
ON TABLE <<EDM_DB_NAME>>.DW_C_RETAILSALE.EPE_TRANSACTION_HEADER_SAVINGS; 

CREATE OR REPLACE STREAM OFFER_REDEMPTION_REPORTING_DETAILED_SUMMARY_Stream_ITEM_SAVINGS
ON TABLE <<EDM_DB_NAME>>.DW_C_RETAILSALE.EPE_TRANSACTION_ITEM_SAVINGS; 
